### ISSUE TITLE
Some non-English localisations are missing

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#10]
http://forum.paradoxplaza.com/forum/showthread.php?707362-The-EU4-to-V2-Converter-Project&p=18969128&viewfull=1#post18969128

**Comment by Idhrendur** [comment]
The file blankMod\output\localisation\0_Names.csv is missing localisations for languages other than English. As it's a data file, I'll leave this to the community to remedy.

**Comment by Idhrendur** [comment]
The missing localisations have been replaced with English ones. This should be remedied by the community.

**Comment by derHochmeister** [comment]
This can be closed. Localisation is fully supported in all Vic2 languages now.

But the translation is done with Google Translate, anyway.

**Comment by Idhrendur** [comment]
Thanks for the reminder!

**Comment by derHochmeister** [comment]
Well, I made a github account to sometime give ideas. But still, I can't do
that much since I don't know programming.

2017-01-17 2:24 GMT+01:00 Idhrendur <notifications@github.com>:
