### ISSUE TITLE
Country colors are incorrect

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#107]
Country colors are correct in the files, but display improperly.

**Comment by Idhrendur** [comment]
Initially caused by this commit:
https://github.com/Idhrendur/paradoxGameConverters/commit/1c7df61c2fa7d5b289f1d3e6af58e600aa763d0a

The exact effects were changed by this commit:
https://github.com/Idhrendur/paradoxGameConverters/commit/d40806318d2bcf3da7dea87c3a023514762e0420

**Comment by Idhrendur** [comment]
Deferring this until after the 0.1 release.

**Comment by thatsgerman** [comment]
This should be fixed, Ill leave it to you if you think we can close

**Comment by Idhrendur** [comment]
Yep, I think so. :-)
