### ISSUE TITLE
Improve victory point conversion

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#115]
A method that can give results similar to HoI4 should be added.

**Comment by thatsgerman** [comment]
Should be given only to your own cores, problem now with Empires where they have to have every bit of land taken, including colonies, to capitulate

**Comment by Idhrendur** [comment]
Victory points are converted and named. However, their positioning within a state should be improved. Perhaps use the most populated province instead of the first one?
