### ISSUE TITLE
Convert radar stations

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#119]
They exist in default HoI4, so find a way to convert them. Or confirm we don't want to.

**Comment by thatsgerman** [comment]
Need to see how common the national radio broadcast invention is, that
might be a decent way to determine radar stations, also need to know how
common they are in HoI4

**Comment by Idhrendur** [comment]
I finally went and checked, and there are seven in 1936. I'm going to leave them out of conversion.
