### ISSUE TITLE
Add missing flags

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#121]
If you convert a game, you get a whole list of flags that are missing (the ones without an ideology-specific suffix are the most critical).

Flags are 93x64 tga (32-bit color, true color, if you have to set the option to specify the origin, it's in the bottom right). This means we can also use them for EU4 to Vic2. They're named according to the Vic2 tag.

As far as I understand, we can reuse flags from PDM as long as we credit them. You can double-check which of their flags apply and simply copy them into our data files as needed. But please verify that it really applies to the same country. They and we may be using the same tag to refer to different nations.

Flags missing from EU4 to Vic2 (and thus also Vic2 to HoI4) are:
EU4 - LDK (Ladakh) / Vic2 LDK (Ladakh)
EU4 - KOC (Kochin) / Vic2 VND (Venad)
EU4 - ANT (Antemoro) / needs a Vic2 tag
EU4 - BNY (Bunyoro) / needs a Vic2 tag
EU4 - BSG (Basoga) / needs a Vic2 tag
EU4 - BTS (Betsimisaraka) / needs a Vic2 tag
EU4 - BUG (Buganda) / needs a Vic2 tag
EU4 - BUU (Burundi) / needs a Vic2 tag
EU4 - CKW (Chokwe) / needs a Vic2 tag
EU4 - HSC (Highlands) / needs a Vic2 tag
EU4 - KIK (Kikondja) / needs a Vic2 tag
EU4 - KRW (Karagwe) / needs a Vic2 tag
EU4 - KSJ (Kasanje) / needs a Vic2 tag
EU4 - KUB (Kuba) / needs a Vic2 tag
EU4 - KZB (Kazembe) / needs a Vic2 tag
EU4 - LDU (Lundu) / needs a Vic2 tag
EU4 - LND (Lunda) / needs a Vic2 tag
EU4 - LUB (Luba) / needs a Vic2 tag
EU4 - MEM (Memmingen) / needs a Vic2 tag
EU4 - MFY (Mahafaly) / needs a Vic2 tag
EU4 - MIR (Merina) / needs a Vic2 tag
EU4 - MKU (Makua) / needs a Vic2 tag
EU4 - MRA (Maravi) / needs a Vic2 tag
EU4 - NKO (Nkore) / needs a Vic2 tag
EU4 - NUM (Nuremberg) / needs a Vic2 tag
EU4 - RVA (Ravensburg) / needs a Vic2 tag
EU4 - RWA (Rwanda) / needs a Vic2 tag
EU4 - RZW (Butua) / needs a Vic2 tag
EU4 - SKA (Sakalava) / needs a VIc2 tag
EU4 - SYO (Soyo) / needs a Vic2 tag
EU4 - TBK (Tumbuka) / needs a Vic2 tag
EU4 - UBH (Buha) / needs a Vic2 tag
EU4 - YAK (Yaka) / needs a Vic2 tag

Flags missing from Vic2 to HoI4 (and that could be improved in EU4 to Vic2) are:
D01.tga - D50.tga

Any flags in the Vic2 to HoI4 data files folder that don't have ideology-specific variants need those created.

Flags missing for HPM conversions (needs review) are:
ABK.tga
AGC.tga
AIN.tga
ALT.tga
ANG.tga
AOT.tga
ASM.tga
ASR.tga
ASY.tga
AWS.tga
AZA.tga
BHP.tga
BHR.tga
BIH.tga
BIM.tga
BKV.tga
BLZ.tga
BMK.tga
BSQ.tga
BUG.tga
CAR.tga
CGO.tga
CLC.tga
CMR.tga
CPL.tga
CRL.tga
CRS.tga
DAG.tga
DAM.tga
DJA.tga
DLM.tga
DND.tga
DON.tga
DRA.tga
FIJ.tga
FIU.tga
FJN.tga
FRO.tga
GAB.tga
GBU.tga
GLM.tga
GMB.tga
GMJ.tga
GNE.tga
GNG.tga
GRN.tga
HNN.tga
HUI.tga
INO.tga
IVC.tga
JAM.tga
JOR.tga
KCH.tga
KDS.tga
KLM.tga
KMK.tga
KML.tga
KNY.tga
KRL.tga
KRN.tga
KUB.tga
KWT.tga
KYR.tga
KZB.tga
LBA.tga
LBN.tga
LBY.tga
LOS.tga
MAS.tga
MAT.tga
MCD.tga
MDV.tga
MLT.tga
MLY.tga
MNP.tga
MOZ.tga
MRT.tga
MRU.tga
NGR.tga
NIG.tga
NMB.tga
NYE.tga
OCC.tga
PBC.tga
PGG.tga
PHL.tga
PLS.tga
PML.tga
PNB.tga
PNJ.tga
PRI.tga
PZN.tga
QAT.tga
RGR.tga
RGS.tga
RWA.tga
SEG.tga
SHK.tga
SID.tga
SLE.tga
SLS.tga
SLW.tga
SNG.tga
SOM.tga
SPC.tga
SPU.tga
SRI.tga
SUA.tga
SUD.tga
SWK.tga
SYL.tga
SZC.tga
TAJ.tga
TGA.tga
TIG.tga
TKM.tga
TMR.tga
TNZ.tga
TOG.tga
TOO.tga
TRZ.tga
TSW.tga
TTB.tga
URA.tga
UYG.tga
UZB.tga
WAD.tga
WHA.tga
WOL.tga
WRI.tga
XHO.tga
YAK.tga
ZAM.tga

**Comment by thatsgerman** [comment]
This shoudl be fixed, I added a check that if the flag path is null when looking in Release/flags, it will check Configuration::Vic2Directory/gfx/flags (or something along those lines). I think I commited it.

**Comment by Idhrendur** [comment]
You did, and it's an elegant bit of code. But it doesn't fix the underlying problem of copyright on the flags.  I'm still convinced we can't use the default Vic2 flags.

In any case, I created this issue in response to someone who volunteered to make flags. That would be the ideal (and it turns out we only seem to be missing a handful of the normal Vic2 ones).

**Comment by twentyitalians** [comment]
Idhrendur, you really need Johan's input regarding the copyright. Or, do
you want me to tweet Fredrik Wester on Twitter? Or both of them?

On Jul 29, 2016 3:39 PM, "Idhrendur" <notifications@github.com> wrote:

You did, and it's an elegant bit of code. But it doesn't fix the underlying
problem of copyright on the flags. I'm still convinced we can't use the
default Vic2 flags.

In any case, I created this issue in response to someone who volunteered to
make flags. That would be the ideal (and it turns out we only seem to be
missing a handful of the normal Vic2 ones).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Idhrendur/paradoxGameConverters/issues/121#issuecomment-236274099>,
or mute the thread

**Comment by thatsgerman** [comment]
I think that would be a great idea, if we can get a confirmation from Pdox themselves that it is ok it would save the artist a ton of time creating 100 countriesish * 4 types of flags.

**Comment by Idhrendur** [comment]
It's probably better to keep this discussion to the forums, so I've put my thoughts on a post there:
https://forum.paradoxplaza.com/forum/index.php?threads/the-vic2-to-hoi4-converter-project-development-thread.915440/page-24#post-21642678

**Comment by Idhrendur** [comment]
This is mostly done now. The dynamic flags (D01-D50) still need doing.

**Comment by Idhrendur** [comment]
I've updated this with flags missing from EU4 to Vic2, and removed some that had been done for Vic2 to HoI4.
