### ISSUE TITLE
Add ideology-specific flags

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#122]
Once the base flags have all been added, ideology-specific flags would make for a lot more flavor in a conversion (the base flag for a country is used if the ideology-specific one can't be found). These are the ones that show up as missing in a test conversion:

ABU_communist.tga
ABU_fascist.tga
ABU_communist.tga
ABU_republic.tga
ABU_republic.tga
ABU_monarchy.tga
AFG_communist.tga
AFG_fascist.tga
AFG_communist.tga
AFG_republic.tga
AFG_republic.tga
AFG_monarchy.tga
ALB_communist.tga
ALB_fascist.tga
ALB_communist.tga
ALB_republic.tga
ALB_republic.tga
ALB_monarchy.tga
ALD_communist.tga
ALD_fascist.tga
ALD_communist.tga
ALD_republic.tga
ALD_republic.tga
ALD_monarchy.tga
ANH_communist.tga
ANH_fascist.tga
ANH_communist.tga
ANH_republic.tga
ANH_republic.tga
ANH_monarchy.tga
ARG_communist.tga
ARG_fascist.tga
ARG_communist.tga
ARG_republic.tga
ARG_republic.tga
ARG_monarchy.tga
ARM_communist.tga
ARM_fascist.tga
ARM_communist.tga
ARM_republic.tga
ARM_republic.tga
ARM_monarchy.tga
ATJ_communist.tga
ATJ_fascist.tga
ATJ_communist.tga
ATJ_republic.tga
ATJ_republic.tga
ATJ_monarchy.tga
AUS_communist.tga
AUS_fascist.tga
AUS_communist.tga
AUS_republic.tga
AUS_republic.tga
AUS_monarchy.tga
AWA_communist.tga
AWA_fascist.tga
AWA_communist.tga
AWA_republic.tga
AWA_republic.tga
AWA_monarchy.tga
AZB_communist.tga
AZB_fascist.tga
AZB_communist.tga
AZB_republic.tga
AZB_republic.tga
AZB_monarchy.tga
BAD_communist.tga
BAD_fascist.tga
BAD_communist.tga
BAD_republic.tga
BAD_republic.tga
BAD_monarchy.tga
BAL_communist.tga
BAL_fascist.tga
BAL_communist.tga
BAL_republic.tga
BAL_republic.tga
BAL_monarchy.tga
BAS_communist.tga
BAS_fascist.tga
BAS_communist.tga
BAS_republic.tga
BAS_republic.tga
BAS_monarchy.tga
BAV_communist.tga
BAV_fascist.tga
BAV_communist.tga
BAV_republic.tga
BAV_republic.tga
BAV_monarchy.tga
BEL_communist.tga
BEL_fascist.tga
BEL_communist.tga
BEL_republic.tga
BEL_republic.tga
BEL_monarchy.tga
BER_communist.tga
BER_fascist.tga
BER_communist.tga
BER_republic.tga
BER_republic.tga
BER_monarchy.tga
BHO_communist.tga
BHO_fascist.tga
BHO_communist.tga
BHO_republic.tga
BHO_republic.tga
BHO_monarchy.tga
BHU_communist.tga
BHU_fascist.tga
BHU_communist.tga
BHU_republic.tga
BHU_republic.tga
BHU_monarchy.tga
BIK_communist.tga
BIK_fascist.tga
BIK_communist.tga
BIK_republic.tga
BIK_republic.tga
BIK_monarchy.tga
BOH_communist.tga
BOH_fascist.tga
BOH_communist.tga
BOH_republic.tga
BOH_republic.tga
BOH_monarchy.tga
BOL_communist.tga
BOL_fascist.tga
BOL_communist.tga
BOL_republic.tga
BOL_republic.tga
BOL_monarchy.tga
BOS_communist.tga
BOS_fascist.tga
BOS_communist.tga
BOS_republic.tga
BOS_republic.tga
BOS_monarchy.tga
BRA_communist.tga
BRA_fascist.tga
BRA_communist.tga
BRA_republic.tga
BRA_republic.tga
BRA_monarchy.tga
BRE_communist.tga
BRE_fascist.tga
BRE_communist.tga
BRE_republic.tga
BRE_republic.tga
BRE_monarchy.tga
BRU_communist.tga
BRU_fascist.tga
BRU_communist.tga
BRU_republic.tga
BRU_republic.tga
BRU_monarchy.tga
BUK_communist.tga
BUK_fascist.tga
BUK_communist.tga
BUK_republic.tga
BUK_republic.tga
BUK_monarchy.tga
BUL_communist.tga
BUL_fascist.tga
BUL_communist.tga
BUL_republic.tga
BUL_republic.tga
BUL_monarchy.tga
BUN_communist.tga
BUN_fascist.tga
BUN_communist.tga
BUN_republic.tga
BUN_republic.tga
BUN_monarchy.tga
BUR_communist.tga
BUR_fascist.tga
BUR_communist.tga
BUR_republic.tga
BUR_republic.tga
BUR_monarchy.tga
BYE_communist.tga
BYE_fascist.tga
BYE_communist.tga
BYE_republic.tga
BYE_republic.tga
BYE_monarchy.tga
CAL_communist.tga
CAL_fascist.tga
CAL_communist.tga
CAL_republic.tga
CAL_republic.tga
CAL_monarchy.tga
CAM_communist.tga
CAM_fascist.tga
CAM_communist.tga
CAM_republic.tga
CAM_republic.tga
CAM_monarchy.tga
CAN_communist.tga
CAN_fascist.tga
CAN_communist.tga
CAN_republic.tga
CAN_republic.tga
CAN_monarchy.tga
CAT_communist.tga
CAT_fascist.tga
CAT_communist.tga
CAT_republic.tga
CAT_republic.tga
CAT_monarchy.tga
CHE_communist.tga
CHE_fascist.tga
CHE_communist.tga
CHE_republic.tga
CHE_republic.tga
CHE_monarchy.tga
CHI_communist.tga
CHI_fascist.tga
CHI_communist.tga
CHI_republic.tga
CHI_republic.tga
CHI_monarchy.tga
CLM_communist.tga
CLM_fascist.tga
CLM_communist.tga
CLM_republic.tga
CLM_republic.tga
CLM_monarchy.tga
COB_communist.tga
COB_fascist.tga
COB_communist.tga
COB_republic.tga
COB_republic.tga
COB_monarchy.tga
COS_communist.tga
COS_fascist.tga
COS_communist.tga
COS_republic.tga
COS_republic.tga
COS_monarchy.tga
CRE_communist.tga
CRE_fascist.tga
CRE_communist.tga
CRE_republic.tga
CRE_republic.tga
CRE_monarchy.tga
CRI_communist.tga
CRI_fascist.tga
CRI_communist.tga
CRI_republic.tga
CRI_republic.tga
CRI_monarchy.tga
CRO_communist.tga
CRO_fascist.tga
CRO_communist.tga
CRO_republic.tga
CRO_republic.tga
CRO_monarchy.tga
CSA_communist.tga
CSA_fascist.tga
CSA_communist.tga
CSA_republic.tga
CSA_republic.tga
CSA_monarchy.tga
CYP_communist.tga
CYP_fascist.tga
CYP_communist.tga
CYP_republic.tga
CYP_republic.tga
CYP_monarchy.tga
CZH_communist.tga
CZH_fascist.tga
CZH_communist.tga
CZH_republic.tga
CZH_republic.tga
CZH_monarchy.tga
DAI_communist.tga
DAI_fascist.tga
DAI_communist.tga
DAI_republic.tga
DAI_republic.tga
DAI_monarchy.tga
DEN_communist.tga
DEN_fascist.tga
DEN_communist.tga
DEN_republic.tga
DEN_republic.tga
DEN_monarchy.tga
DES_communist.tga
DES_fascist.tga
DES_communist.tga
DES_republic.tga
DES_republic.tga
DES_monarchy.tga
DOM_communist.tga
DOM_fascist.tga
DOM_communist.tga
DOM_republic.tga
DOM_republic.tga
DOM_monarchy.tga
DZG_communist.tga
DZG_fascist.tga
DZG_communist.tga
DZG_republic.tga
DZG_republic.tga
DZG_monarchy.tga
ECU_communist.tga
ECU_fascist.tga
ECU_communist.tga
ECU_republic.tga
ECU_republic.tga
ECU_monarchy.tga
EGY_communist.tga
EGY_fascist.tga
EGY_communist.tga
EGY_republic.tga
EGY_republic.tga
EGY_monarchy.tga
ELS_communist.tga
ELS_fascist.tga
ELS_communist.tga
ELS_republic.tga
ELS_republic.tga
ELS_monarchy.tga
ENG_communist.tga
ENG_fascist.tga
ENG_communist.tga
ENG_republic.tga
ENG_republic.tga
ENG_monarchy.tga
EST_communist.tga
EST_fascist.tga
EST_communist.tga
EST_republic.tga
EST_republic.tga
EST_monarchy.tga
ETH_communist.tga
ETH_fascist.tga
ETH_communist.tga
ETH_republic.tga
ETH_republic.tga
ETH_monarchy.tga
FIN_communist.tga
FIN_fascist.tga
FIN_communist.tga
FIN_republic.tga
FIN_republic.tga
FIN_monarchy.tga
FLA_communist.tga
FLA_fascist.tga
FLA_communist.tga
FLA_republic.tga
FLA_republic.tga
FLA_monarchy.tga
FRA_communist.tga
FRA_fascist.tga
FRA_communist.tga
FRA_republic.tga
FRA_republic.tga
FRA_monarchy.tga
FRM_communist.tga
FRM_fascist.tga
FRM_communist.tga
FRM_republic.tga
FRM_republic.tga
FRM_monarchy.tga
GCO_communist.tga
GCO_fascist.tga
GCO_communist.tga
GCO_republic.tga
GCO_republic.tga
GCO_monarchy.tga
GEO_communist.tga
GEO_fascist.tga
GEO_communist.tga
GEO_republic.tga
GEO_republic.tga
GEO_monarchy.tga
GER_communist.tga
GER_fascist.tga
GER_communist.tga
GER_republic.tga
GER_republic.tga
GER_monarchy.tga
GRE_communist.tga
GRE_fascist.tga
GRE_communist.tga
GRE_republic.tga
GRE_republic.tga
GRE_monarchy.tga
GWA_communist.tga
GWA_fascist.tga
GWA_communist.tga
GWA_republic.tga
GWA_republic.tga
GWA_monarchy.tga
GXI_communist.tga
GXI_fascist.tga
GXI_communist.tga
GXI_republic.tga
GXI_republic.tga
GXI_monarchy.tga
HAI_communist.tga
HAI_fascist.tga
HAI_communist.tga
HAI_republic.tga
HAI_republic.tga
HAI_monarchy.tga
HAM_communist.tga
HAM_fascist.tga
HAM_communist.tga
HAM_republic.tga
HAM_republic.tga
HAM_monarchy.tga
HAN_communist.tga
HAN_fascist.tga
HAN_communist.tga
HAN_republic.tga
HAN_republic.tga
HAN_monarchy.tga
HAW_communist.tga
HAW_fascist.tga
HAW_communist.tga
HAW_republic.tga
HAW_republic.tga
HAW_monarchy.tga
HDJ_communist.tga
HDJ_fascist.tga
HDJ_communist.tga
HDJ_republic.tga
HDJ_republic.tga
HDJ_monarchy.tga
HEK_communist.tga
HEK_fascist.tga
HEK_communist.tga
HEK_republic.tga
HEK_republic.tga
HEK_monarchy.tga
HES_communist.tga
HES_fascist.tga
HES_communist.tga
HES_republic.tga
HES_republic.tga
HES_monarchy.tga
HND_communist.tga
HND_fascist.tga
HND_communist.tga
HND_republic.tga
HND_republic.tga
HND_monarchy.tga
HOL_communist.tga
HOL_fascist.tga
HOL_communist.tga
HOL_republic.tga
HOL_republic.tga
HOL_monarchy.tga
HON_communist.tga
HON_fascist.tga
HON_communist.tga
HON_republic.tga
HON_republic.tga
HON_monarchy.tga
HUN_communist.tga
HUN_fascist.tga
HUN_communist.tga
HUN_republic.tga
HUN_republic.tga
HUN_monarchy.tga
HYD_communist.tga
HYD_fascist.tga
HYD_communist.tga
HYD_republic.tga
HYD_republic.tga
HYD_monarchy.tga
ICL_communist.tga
ICL_fascist.tga
ICL_communist.tga
ICL_republic.tga
ICL_republic.tga
ICL_monarchy.tga
IND_communist.tga
IND_fascist.tga
IND_communist.tga
IND_republic.tga
IND_republic.tga
IND_monarchy.tga
ION_communist.tga
ION_fascist.tga
ION_communist.tga
ION_republic.tga
ION_republic.tga
ION_monarchy.tga
IRE_communist.tga
IRE_fascist.tga
IRE_communist.tga
IRE_republic.tga
IRE_republic.tga
IRE_monarchy.tga
IRQ_communist.tga
IRQ_fascist.tga
IRQ_communist.tga
IRQ_republic.tga
IRQ_republic.tga
IRQ_monarchy.tga
ITA_communist.tga
ITA_fascist.tga
ITA_communist.tga
ITA_republic.tga
ITA_republic.tga
ITA_monarchy.tga
JAI_communist.tga
JAI_fascist.tga
JAI_communist.tga
JAI_republic.tga
JAI_republic.tga
JAI_monarchy.tga
JAN_communist.tga
JAN_fascist.tga
JAN_communist.tga
JAN_republic.tga
JAN_republic.tga
JAN_monarchy.tga
JAP_communist.tga
JAP_fascist.tga
JAP_communist.tga
JAP_republic.tga
JAP_republic.tga
JAP_monarchy.tga
JAS_communist.tga
JAS_fascist.tga
JAS_communist.tga
JAS_republic.tga
JAS_republic.tga
JAS_monarchy.tga
JAV_communist.tga
JAV_fascist.tga
JAV_communist.tga
JAV_republic.tga
JAV_republic.tga
JAV_monarchy.tga
JOD_communist.tga
JOD_fascist.tga
JOD_communist.tga
JOD_republic.tga
JOD_republic.tga
JOD_monarchy.tga
JOH_communist.tga
JOH_fascist.tga
JOH_communist.tga
JOH_republic.tga
JOH_republic.tga
JOH_monarchy.tga
KAL_communist.tga
KAL_fascist.tga
KAL_communist.tga
KAL_republic.tga
KAL_republic.tga
KAL_monarchy.tga
KAS_communist.tga
KAS_fascist.tga
KAS_communist.tga
KAS_republic.tga
KAS_republic.tga
KAS_monarchy.tga
KHI_communist.tga
KHI_fascist.tga
KHI_communist.tga
KHI_republic.tga
KHI_republic.tga
KHI_monarchy.tga
KOK_communist.tga
KOK_fascist.tga
KOK_communist.tga
KOK_republic.tga
KOK_republic.tga
KOK_monarchy.tga
KOR_communist.tga
KOR_fascist.tga
KOR_communist.tga
KOR_republic.tga
KOR_republic.tga
KOR_monarchy.tga
KRA_communist.tga
KRA_fascist.tga
KRA_communist.tga
KRA_republic.tga
KRA_republic.tga
KRA_monarchy.tga
KUK_communist.tga
KUK_fascist.tga
KUK_communist.tga
KUK_republic.tga
KUK_republic.tga
KUK_monarchy.tga
KUT_communist.tga
KUT_fascist.tga
KUT_communist.tga
KUT_republic.tga
KUT_republic.tga
KUT_monarchy.tga
LAD_communist.tga
LAD_fascist.tga
LAD_communist.tga
LAD_republic.tga
LAD_republic.tga
LAD_monarchy.tga
LAT_communist.tga
LAT_fascist.tga
LAT_communist.tga
LAT_republic.tga
LAT_republic.tga
LAT_monarchy.tga
LIB_communist.tga
LIB_fascist.tga
LIB_communist.tga
LIB_republic.tga
LIB_republic.tga
LIB_monarchy.tga
LIP_communist.tga
LIP_fascist.tga
LIP_communist.tga
LIP_republic.tga
LIP_republic.tga
LIP_monarchy.tga
LIT_communist.tga
LIT_fascist.tga
LIT_communist.tga
LIT_republic.tga
LIT_republic.tga
LIT_monarchy.tga
LOM_communist.tga
LOM_fascist.tga
LOM_communist.tga
LOM_republic.tga
LOM_republic.tga
LOM_monarchy.tga
LUA_communist.tga
LUA_fascist.tga
LUA_communist.tga
LUA_republic.tga
LUA_republic.tga
LUA_monarchy.tga
LUB_communist.tga
LUB_fascist.tga
LUB_communist.tga
LUB_republic.tga
LUB_republic.tga
LUB_monarchy.tga
LUC_communist.tga
LUC_fascist.tga
LUC_communist.tga
LUC_republic.tga
LUC_republic.tga
LUC_monarchy.tga
LUX_communist.tga
LUX_fascist.tga
LUX_communist.tga
LUX_republic.tga
LUX_republic.tga
LUX_monarchy.tga
MAD_communist.tga
MAD_fascist.tga
MAD_communist.tga
MAD_republic.tga
MAD_republic.tga
MAD_monarchy.tga
MAK_communist.tga
MAK_fascist.tga
MAK_communist.tga
MAK_republic.tga
MAK_republic.tga
MAK_monarchy.tga
MAN_communist.tga
MAN_fascist.tga
MAN_communist.tga
MAN_republic.tga
MAN_republic.tga
MAN_monarchy.tga
MCK_communist.tga
MCK_fascist.tga
MCK_communist.tga
MCK_republic.tga
MCK_republic.tga
MCK_monarchy.tga
MEC_communist.tga
MEC_fascist.tga
MEC_communist.tga
MEC_republic.tga
MEC_republic.tga
MEC_monarchy.tga
MEW_communist.tga
MEW_fascist.tga
MEW_communist.tga
MEW_republic.tga
MEW_republic.tga
MEW_monarchy.tga
MGL_communist.tga
MGL_fascist.tga
MGL_communist.tga
MGL_republic.tga
MGL_republic.tga
MGL_monarchy.tga
MOD_communist.tga
MOD_fascist.tga
MOD_communist.tga
MOD_republic.tga
MOD_republic.tga
MOD_monarchy.tga
MOL_communist.tga
MOL_fascist.tga
MOL_communist.tga
MOL_republic.tga
MOL_republic.tga
MOL_monarchy.tga
MON_communist.tga
MON_fascist.tga
MON_communist.tga
MON_republic.tga
MON_republic.tga
MON_monarchy.tga
MOR_communist.tga
MOR_fascist.tga
MOR_communist.tga
MOR_republic.tga
MOR_republic.tga
MOR_monarchy.tga
MTC_communist.tga
MTC_fascist.tga
MTC_communist.tga
MTC_republic.tga
MTC_republic.tga
MTC_monarchy.tga
MUG_communist.tga
MUG_fascist.tga
MUG_communist.tga
MUG_republic.tga
MUG_republic.tga
MUG_monarchy.tga
MYS_communist.tga
MYS_fascist.tga
MYS_communist.tga
MYS_republic.tga
MYS_republic.tga
MYS_monarchy.tga
NAG_communist.tga
NAG_fascist.tga
NAG_communist.tga
NAG_republic.tga
NAG_republic.tga
NAG_monarchy.tga
NAL_communist.tga
NAL_fascist.tga
NAL_communist.tga
NAL_republic.tga
NAL_republic.tga
NAL_monarchy.tga
NAS_communist.tga
NAS_fascist.tga
NAS_communist.tga
NAS_republic.tga
NAS_republic.tga
NAS_monarchy.tga
NEJ_communist.tga
NEJ_fascist.tga
NEJ_communist.tga
NEJ_republic.tga
NEJ_republic.tga
NEJ_monarchy.tga
NEN_communist.tga
NEN_fascist.tga
NEN_communist.tga
NEN_republic.tga
NEN_republic.tga
NEN_monarchy.tga
NEP_communist.tga
NEP_fascist.tga
NEP_communist.tga
NEP_republic.tga
NEP_republic.tga
NEP_monarchy.tga
NET_communist.tga
NET_fascist.tga
NET_communist.tga
NET_republic.tga
NET_republic.tga
NET_monarchy.tga
NEW_communist.tga
NEW_fascist.tga
NEW_communist.tga
NEW_republic.tga
NEW_republic.tga
NEW_monarchy.tga
NGF_communist.tga
NGF_fascist.tga
NGF_communist.tga
NGF_republic.tga
NGF_republic.tga
NGF_monarchy.tga
NIC_communist.tga
NIC_fascist.tga
NIC_communist.tga
NIC_republic.tga
NIC_republic.tga
NIC_monarchy.tga
NOR_communist.tga
NOR_fascist.tga
NOR_communist.tga
NOR_republic.tga
NOR_republic.tga
NOR_monarchy.tga
NZL_communist.tga
NZL_fascist.tga
NZL_communist.tga
NZL_republic.tga
NZL_republic.tga
NZL_monarchy.tga
OLD_communist.tga
OLD_fascist.tga
OLD_communist.tga
OLD_republic.tga
OLD_republic.tga
OLD_monarchy.tga
OMA_communist.tga
OMA_fascist.tga
OMA_communist.tga
OMA_republic.tga
OMA_republic.tga
OMA_monarchy.tga
ORA_communist.tga
ORA_fascist.tga
ORA_communist.tga
ORA_republic.tga
ORA_republic.tga
ORA_monarchy.tga
ORI_communist.tga
ORI_fascist.tga
ORI_communist.tga
ORI_republic.tga
ORI_republic.tga
ORI_monarchy.tga
PAN_communist.tga
PAN_fascist.tga
PAN_communist.tga
PAN_republic.tga
PAN_republic.tga
PAN_monarchy.tga
PAP_communist.tga
PAP_fascist.tga
PAP_communist.tga
PAP_republic.tga
PAP_republic.tga
PAP_monarchy.tga
PAR_communist.tga
PAR_fascist.tga
PAR_communist.tga
PAR_republic.tga
PAR_republic.tga
PAR_monarchy.tga
PER_communist.tga
PER_fascist.tga
PER_communist.tga
PER_republic.tga
PER_republic.tga
PER_monarchy.tga
PHI_communist.tga
PHI_fascist.tga
PHI_communist.tga
PHI_republic.tga
PHI_republic.tga
PHI_monarchy.tga
PLC_communist.tga
PLC_fascist.tga
PLC_communist.tga
PLC_republic.tga
PLC_republic.tga
PLC_monarchy.tga
PNM_communist.tga
PNM_fascist.tga
PNM_communist.tga
PNM_republic.tga
PNM_republic.tga
PNM_monarchy.tga
POL_communist.tga
POL_fascist.tga
POL_communist.tga
POL_republic.tga
POL_republic.tga
POL_monarchy.tga
POR_communist.tga
POR_fascist.tga
POR_communist.tga
POR_republic.tga
POR_republic.tga
POR_monarchy.tga
PRU_communist.tga
PRU_fascist.tga
PRU_communist.tga
PRU_republic.tga
PRU_republic.tga
PRU_monarchy.tga
QUE_communist.tga
QUE_fascist.tga
QUE_communist.tga
QUE_republic.tga
QUE_republic.tga
QUE_monarchy.tga
ROM_communist.tga
ROM_fascist.tga
ROM_communist.tga
ROM_republic.tga
ROM_republic.tga
ROM_monarchy.tga
RUS_communist.tga
RUS_fascist.tga
RUS_communist.tga
RUS_republic.tga
RUS_republic.tga
RUS_monarchy.tga
RUT_communist.tga
RUT_fascist.tga
RUT_communist.tga
RUT_republic.tga
RUT_republic.tga
RUT_monarchy.tga
SAF_communist.tga
SAF_fascist.tga
SAF_communist.tga
SAF_republic.tga
SAF_republic.tga
SAF_monarchy.tga
SAR_communist.tga
SAR_fascist.tga
SAR_communist.tga
SAR_republic.tga
SAR_republic.tga
SAR_monarchy.tga
SAX_communist.tga
SAX_fascist.tga
SAX_communist.tga
SAX_republic.tga
SAX_republic.tga
SAX_monarchy.tga
SCA_communist.tga
SCA_fascist.tga
SCA_communist.tga
SCA_republic.tga
SCA_republic.tga
SCA_monarchy.tga
SCH_communist.tga
SCH_fascist.tga
SCH_communist.tga
SCH_republic.tga
SCH_republic.tga
SCH_monarchy.tga
SCO_communist.tga
SCO_fascist.tga
SCO_communist.tga
SCO_republic.tga
SCO_republic.tga
SCO_monarchy.tga
SER_communist.tga
SER_fascist.tga
SER_communist.tga
SER_republic.tga
SER_republic.tga
SER_monarchy.tga
SHI_communist.tga
SHI_fascist.tga
SHI_communist.tga
SHI_republic.tga
SHI_republic.tga
SHI_monarchy.tga
SIA_communist.tga
SIA_fascist.tga
SIA_communist.tga
SIA_republic.tga
SIA_republic.tga
SIA_monarchy.tga
SIC_communist.tga
SIC_fascist.tga
SIC_communist.tga
SIC_republic.tga
SIC_republic.tga
SIC_monarchy.tga
SIE_communist.tga
SIE_fascist.tga
SIE_communist.tga
SIE_republic.tga
SIE_republic.tga
SIE_monarchy.tga
SIK_communist.tga
SIK_fascist.tga
SIK_communist.tga
SIK_republic.tga
SIK_republic.tga
SIK_monarchy.tga
SIN_communist.tga
SIN_fascist.tga
SIN_communist.tga
SIN_republic.tga
SIN_republic.tga
SIN_monarchy.tga
SLO_communist.tga
SLO_fascist.tga
SLO_communist.tga
SLO_republic.tga
SLO_republic.tga
SLO_monarchy.tga
SLV_communist.tga
SLV_fascist.tga
SLV_communist.tga
SLV_republic.tga
SLV_republic.tga
SLV_monarchy.tga
SOK_communist.tga
SOK_fascist.tga
SOK_communist.tga
SOK_republic.tga
SOK_republic.tga
SOK_monarchy.tga
SPA_communist.tga
SPA_fascist.tga
SPA_communist.tga
SPA_republic.tga
SPA_republic.tga
SPA_monarchy.tga
SWE_communist.tga
SWE_fascist.tga
SWE_communist.tga
SWE_republic.tga
SWE_republic.tga
SWE_monarchy.tga
SWI_communist.tga
SWI_fascist.tga
SWI_communist.tga
SWI_republic.tga
SWI_republic.tga
SWI_monarchy.tga
SXI_communist.tga
SXI_fascist.tga
SXI_communist.tga
SXI_republic.tga
SXI_republic.tga
SXI_monarchy.tga
TIB_communist.tga
TIB_fascist.tga
TIB_communist.tga
TIB_republic.tga
TIB_republic.tga
TIB_monarchy.tga
TPG_communist.tga
TPG_fascist.tga
TPG_communist.tga
TPG_republic.tga
TPG_republic.tga
TPG_monarchy.tga
TRA_communist.tga
TRA_fascist.tga
TRA_communist.tga
TRA_republic.tga
TRA_republic.tga
TRA_monarchy.tga
TRE_communist.tga
TRE_fascist.tga
TRE_communist.tga
TRE_republic.tga
TRE_republic.tga
TRE_monarchy.tga
TRI_communist.tga
TRI_fascist.tga
TRI_communist.tga
TRI_republic.tga
TRI_republic.tga
TRI_monarchy.tga
TRN_communist.tga
TRN_fascist.tga
TRN_communist.tga
TRN_republic.tga
TRN_republic.tga
TRN_monarchy.tga
TUN_communist.tga
TUN_fascist.tga
TUN_communist.tga
TUN_republic.tga
TUN_republic.tga
TUN_monarchy.tga
TUR_communist.tga
TUR_fascist.tga
TUR_communist.tga
TUR_republic.tga
TUR_republic.tga
TUR_monarchy.tga
TUS_communist.tga
TUS_fascist.tga
TUS_communist.tga
TUS_republic.tga
TUS_republic.tga
TUS_monarchy.tga
UBD_communist.tga
UBD_fascist.tga
UBD_communist.tga
UBD_republic.tga
UBD_republic.tga
UBD_monarchy.tga
UCA_communist.tga
UCA_fascist.tga
UCA_communist.tga
UCA_republic.tga
UCA_republic.tga
UCA_monarchy.tga
UKR_communist.tga
UKR_fascist.tga
UKR_communist.tga
UKR_republic.tga
UKR_republic.tga
UKR_monarchy.tga
URU_communist.tga
URU_fascist.tga
URU_communist.tga
URU_republic.tga
URU_republic.tga
URU_monarchy.tga
USA_communist.tga
USA_fascist.tga
USA_communist.tga
USA_republic.tga
USA_republic.tga
USA_monarchy.tga
VEN_communist.tga
VEN_fascist.tga
VEN_communist.tga
VEN_republic.tga
VEN_republic.tga
VEN_monarchy.tga
VNZ_communist.tga
VNZ_fascist.tga
VNZ_communist.tga
VNZ_republic.tga
VNZ_republic.tga
VNZ_monarchy.tga
WAL_communist.tga
WAL_fascist.tga
WAL_communist.tga
WAL_republic.tga
WAL_republic.tga
WAL_monarchy.tga
WEI_communist.tga
WEI_fascist.tga
WEI_communist.tga
WEI_republic.tga
WEI_republic.tga
WEI_monarchy.tga
WIA_communist.tga
WIA_fascist.tga
WIA_communist.tga
WIA_republic.tga
WIA_republic.tga
WIA_monarchy.tga
WLL_communist.tga
WLL_fascist.tga
WLL_communist.tga
WLL_republic.tga
WLL_republic.tga
WLL_monarchy.tga
WUR_communist.tga
WUR_fascist.tga
WUR_communist.tga
WUR_republic.tga
WUR_republic.tga
WUR_monarchy.tga
XBI_communist.tga
XBI_fascist.tga
XBI_communist.tga
XBI_republic.tga
XBI_republic.tga
XBI_monarchy.tga
XIN_communist.tga
XIN_fascist.tga
XIN_communist.tga
XIN_republic.tga
XIN_republic.tga
XIN_monarchy.tga
YEM_communist.tga
YEM_fascist.tga
YEM_communist.tga
YEM_republic.tga
YEM_republic.tga
YEM_monarchy.tga
YNN_communist.tga
YNN_fascist.tga
YNN_communist.tga
YNN_republic.tga
YNN_republic.tga
YNN_monarchy.tga
YUG_communist.tga
YUG_fascist.tga
YUG_communist.tga
YUG_republic.tga
YUG_republic.tga
YUG_monarchy.tga
ZUL_communist.tga
ZUL_fascist.tga
ZUL_communist.tga
ZUL_republic.tga
ZUL_republic.tga
ZUL_monarchy.tga

**Comment by derHochmeister** [comment]
I gave you the files in PM via reddit but since HoI4 and IRL flags sometime are the same as Vic2's, there's not much work that could be done.
