### ISSUE TITLE
Improve AI Division Designs

### ISSUE THREAD

**Issue by thatsgerman** [Idhrendur/paradoxGameConverters#126]
Sometimes AI will ignore the given infantry designs and will make 3 Art + 5 Inf Devisions, for larger nations this means they build a ton of these divisions and might cause lag on weaker computers since they will have 150+ units by 1939.
It will also only build those troops and not build tanks, mechanized, ect. The default AI could  be improved in this regard.

**Comment by derHochmeister** [comment]
It'd be awesome if we could mod AI behaviour but, for the moment, we can only rely on the vanilla one, to avoid screwings.
