### ISSUE TITLE
AI Cant Naval Invade

### ISSUE THREAD

**Issue by thatsgerman** [Idhrendur/paradoxGameConverters#127]
95% of the time the AI has trouble with naval invasions, this might be caused by the new strategic regions but not sure.
The issue is they set up naval invasions and plans for conquest but will not get the naval or air superiority over the regions needed to get the invasions started.
Out of the 10+ games I have played, Japan naval invaded Korea once.
UK cannot invade Normandy.
UK could not invade Sicily from Malta.
USA doesnt even attempt to conquer UK when at war with them.

**Comment by Idhrendur** [comment]
Haven't heard reports of this in a while, I think it may be better now. Will reopen if necessary.
