### ISSUE TITLE
Crash on the day after the game

### ISSUE THREAD

**Issue by Asmodaus** [Idhrendur/paradoxGameConverters#128]
Game Version 1.0.1
Converter Version 0.1
Crash occurs approximately at 2:00 the next day

**Comment by Idhrendur** [comment]
This should be reported on the converter release thread (it might be a bug we already know about): https://forum.paradoxplaza.com/forum/index.php?threads/vic2-to-hoi4-converter-release-thread.948992/

Could you upload your log.txt to pastebin and your Vic2 save to a file upload site and then share the links there? Thanks!

**Comment by Asmodaus** [comment]
Im upgrade game to HoI 1.1.0 and its work!

**Comment by Idhrendur** [comment]
Ah, glad to hear it!
