### ISSUE TITLE
Convert national unity

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#131]
See the discussions below for ideas:
https://forum.paradoxplaza.com/forum/index.php?threads/the-vic2-to-hoi4-converter-project-development-thread.915440/page-28#post-21688924
https://forum.paradoxplaza.com/forum/index.php?threads/the-vic2-to-hoi4-converter-project-development-thread.915440/page-28#post-21690653
https://forum.paradoxplaza.com/forum/index.php?threads/the-vic2-to-hoi4-converter-project-development-thread.915440/page-28#post-21692784

**Comment by derHochmeister** [comment]
(10 - consciousness) * (10 - militancy) should do the trick. In fact, consciousness means how much your citizens aren't trusting your government and militancy means how much they would kill your country up.

However, it is better to set a minimum of 50% NU and a maximum of 90% NU, to avoid weird results.

**Comment by derHochmeister** [comment]
According to this repository, we used a system in HoI3. Maybe we should recycle it?

> National unity is set at `70 + revanchism * 20 - war_exhaustion / 2.5`

https://github.com/Idhrendur/paradoxGameConverters/wiki/Vic2-To-HoI3:-National-Unity

**Comment by Idhrendur** [comment]
Yep, that code is still there, in fact! But I need to make sure that it puts NU in a realistic range for HoI4 and that it properly outputs it.

**Comment by derHochmeister** [comment]
In Vanilla HoI4, NU can range from 90% (Germany) to 40% (France). I think that code goes better if we change the starting 70 to a 60.

**Comment by Idhrendur** [comment]
That's a wide range! Is that largely driven via NS, or is it coded that way? And what does the distribution look like?

**Comment by derHochmeister** [comment]
I think France is more a developer's joke but the range is actually coded so large at start, without any NS involved.

http://www.hoi4wiki.com/Government#National_Unity
