### ISSUE TITLE
National Focus descriptions and titles are missing

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#134]
"The National Focus tree is broken @thatsgerman This may already be known but the descriptions come over as the script title. Instead of Large Navy it reads: large_navy01 Which is a problem because the next NF after Large Navy is Cruiser Effort (or cruiser_effort01 in the conversion). Cruiser Effort requires Large Navy NF but because the NF is large_navy01 you can't select it (but you CAN select Submarine Effort - a dotted line connection). Very frustrating. Also, none of the NFs had descriptions."

**Comment by derHochmeister** [comment]
The converter should generate a localisation file in which include ALSO the generated national foci, not just state and VPs names.
