### ISSUE TITLE
Improve localisations for Vic2 dynamic nations

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#139]
Vic2 dynamic nations have localisations for their name and adjective generated from the D01-D50 localisations in darkness_3_01.csv. The use of these should be better replicated in the converter.

**Comment by derHochmeister** [comment]
The converter now converts them fine.

**Comment by Hamiller78** [comment]
Some progress here. I can update the country names in V2Localisations with $REGION$ placeholders. I just wonder if the dominion names are localized as well. Because now I have a Kingdom of Western Australia and in German it would be "Königreich von Western Australia" with the english Western Australia in it.

**Comment by Hamiller78** [comment]
The domain names are of course not localized because they are in the language of the save game file. I could try to switch Victroia 2 to german and test this.
Anyway, the fix seems fine in-game, it looks much better. Now the dynamic countries need some flags.

**Comment by derHochmeister** [comment]
I'd like to give flags but copyright makes it impossible, for those flags
being totally Paradox OC.

**Comment by derHochmeister** [comment]
The flags are a new issue but localization of dominions in other languages
is still to code.

**Comment by Hamiller78** [comment]
The rest is very low priority IMHO. Then domain name is taken from the save file, which contains the name only in one language. I assume that Vic2 saves the domain name in the language you're playing. So we only have a problem when someone decides to play HoI4 and Victoria 2 in different languages.
To fix this the converter would have to take the domain name from the save file, search the localisation texts of regions to find all localisations of the correct one and put them in the country localisation file. At least I think it would work like this.
I would open a new issue for later or remove this from the 0.3 milestones. The localisation is missing completely for the focus trees for example, that's higher priority.

**Comment by Idhrendur** [comment]
I opened issue #310 for that, then. It's also a 0.3 one for now, but if we get everything else done, I'll bump it to 0.4.
