### ISSUE TITLE
Check if .png flags are supported (and respond appropriately)

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#153]
If png files are supported for flags, more flags from EU4 to Vic2 can be used.

**Comment by derHochmeister** [comment]
.png flags are not supported. The converter will seek for a .tga file and, not finding it, will give nothing. Better to convert the remaining .png's into .tga's

**Comment by Idhrendur** [comment]
I know the converter doesn't handle .png files, I wrote the code. But does HoI4 handle them? That's what determines what I can do with Vic2 files.

**Comment by derHochmeister** [comment]
HoI4 doesn't handle .png flags because it'll look for .tga files.

**Comment by Idhrendur** [comment]
Bummer.
