### ISSUE TITLE
Add Troubleshooting view

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#16]
Adding a view/page with troubleshooting help might cut down on the support requests.
It could contain a list of symptoms and, depending on the issue, either a button that fixes it (deleting map cache) or links to a forum post where someone explains how to fix the issue.
Some of the items in this list could be read from xml (if all they do is list symptoms and a link to a fix) but any automated fixes will probably have to be hard coded.
Furthermore, this should preferably be built in a way that supports the whole idea about not locking the frontend to any particular games.
Suggested items for troubleshooting list:
Clearing map cache for V2.
Crashing at converting history. See FAQ/First post.
MSVCP120.dll. See FAQ/First post.
Ironman save. 
Compressed save. 
Functionality for removing previous mods? See http://forum.paradoxplaza.com/forum/showthread.php?707362-The-EU4-to-V2-Converter-Project&p=18851512&viewfull=1#post18851512
Open for more suggestions.

**Comment by kwsdev** [comment]
I've already added support for automatically uncompressing compressed saves, so that point can probably be removed from the list.

**Comment by derHochmeister** [comment]
I think this is closed

**Comment by Idhrendur** [comment]
Most of these are done, actually.
