### ISSUE TITLE
Some empty directories in the EU4ToV2 Blank mod are not in the repository.

### ISSUE THREAD

**Issue by RonWeber** [Idhrendur/paradoxGameConverters#165]
Specifically the many empty directories in EU4ToVic2/Data_Files/blankMod/output/history/provinces are required for the converter but git doesn't upload them.  Thanks, git.

**Comment by Idhrendur** [comment]
Ah, and I never noticed because they're fine on my machine. It'll probably be best to have copy_files.bat recreate them.

**Comment by Idhrendur** [comment]
And actually, it looks as if if already should be doing so. Is it not accomplishing this on your system?

**Comment by Prem-is-bored** [comment]
I think I have a bit of an outdated version of 1.0D
