### ISSUE TITLE
Support grammar of new area.txt

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#170]
map/area.txt now has color definitions in some areas (Brittany in particular). The parser can't handle reading these followed by the list of province numbers. The parser needs updating in order to do so.

**Comment by Prem-is-bored** [comment]
Good that the bug was noticed. I really want to work on a grand campaign from CKII to HOI3 and stuff like this is annoying to both the consumer **and** programmer. Hope this gets fixed...

**Comment by Idhrendur** [comment]
Because of the area.txt problem, I'm putting this converter on indefinite hold.

**Comment by Idhrendur** [comment]
I was provided a workaround: copy the file and remove all lines that reference colors, then parse the copy.

It works, but will probably break if ever one of those become multi-line.
