### ISSUE TITLE
Paradox parser problems

### ISSUE THREAD

**Issue by wzh190015** [Idhrendur/paradoxGameConverters#173]
Here follows the origin text in save file and output of
```C++
LOG(LogLevel::Debug) << "stateBuildings:\t" << stateBuildingsObj.toString();
```

origin1
```
		state_buildings=
		{
			building="furniture_factory"
			level=1
			stockpile=
			{
				timber=9.28723
				cement=0.23096
				machine_parts=0.02307
				lumber=9.23886
			}
			employment=
			{
				state_province_id=294
				employees=
				{

					{
						province_pop_id=
						{
						province_id=300
						index=0
						type=7
						}
						count=5423
					}

					{
						province_pop_id=
						{
						province_id=300
						index=0
						type=6
						}
						count=1356
					}
				}
			}
			money=238093.61966
			last_spending=22016.23535
			last_income=41099.27368
			pops_paychecks=1140.85913
			last_investment=18999.93896
			unprofitable_days=0
			leftover=0.01611
			injected_money=113999.63379
			injected_days=6
			produces=8.37253
			profit_history_days=2
			profit_history_current=2
			profit_history_entry=
			{
31.55133 15.20605 			}
		}
```

output1
```
2016-12-07 21:48:52   [DEBUG]     stateBuildings:	state_buildings=
{
	building=furniture_factory
	level=1
	stockpile=
	{
		timber=9.28723
		cement=0.23096
		machine_parts=0.02307
		lumber=9.23886
	}
	employment=
	{
		state_province_id=294
		employees=
		{
			objlist={ }
			objlist={ }
		}
	}
	money=238093.61966
	last_spending=22016.23535
	last_income=41099.27368
	pops_paychecks=1140.85913
	last_investment=18999.93896
	unprofitable_days=0
	leftover=0.01611
	injected_money=113999.63379
	injected_days=6
	produces=8.37253
	profit_history_days=2
	profit_history_current=2
	profit_history_entry={"31.55133" "15.20605" }
}
```

origin2
```
		state_buildings=
		{
			building="paper_mill"
			level=1
			stockpile=
			{
				timber=24.78598
				cement=0.24783
				machine_parts=0.02475
			}
			employment=
			{
				state_province_id=294
				employees=
				{

					annoymous={
						province_pop_id=
						{
						province_id=300
						index=0
						type=7
						}
						count=5989
					}

					annoymous={
						province_pop_id=
						{
						province_id=300
						index=0
						type=6
						}
						count=1497
					}
				}
			}
			money=281262.24252
			last_spending=27666.80908
			last_income=37634.06372
			pops_paychecks=702.34344
			last_investment=22499.84741
			unprofitable_days=0
			leftover=1.19815
			injected_money=134999.08447
			injected_days=6
			produces=12.07645
			profit_history_days=2
			profit_history_current=2
			profit_history_entry=
			{
33.83487 34.25629 			}
		}
```

output2
```
2016-12-07 21:48:52   [DEBUG]     stateBuildings:	state_buildings=
{
	building=paper_mill
	level=1
	stockpile=
	{
		timber=24.78598
		cement=0.24783
		machine_parts=0.02475
	}
	employment=
	{
		state_province_id=294
		employees=
		{
			annoymous=
			{
				province_pop_id=
				{
					province_id=300
					index=0
					type=7
				}
				count=5989
			}
			annoymous=
			{
				province_pop_id=
				{
					province_id=300
					index=0
					type=6
				}
				count=1497
			}
		}
	}
	money=281262.24252
	last_spending=27666.80908
	last_income=37634.06372
	pops_paychecks=702.34344
	last_investment=22499.84741
	unprofitable_days=0
	leftover=1.19815
	injected_money=134999.08447
	injected_days=6
	produces=12.07645
	profit_history_days=2
	profit_history_current=2
	profit_history_entry={"33.83487" "34.25629" }
}
```

notice the difference in state_buildings/employment/employees
the parser cannot parse objects with no names correctly

**Comment by wzh190015** [comment]
We can make a pretreatment on save files and add a name for all anonymous objects

**Comment by Idhrendur** [comment]
Yep, it's a pernicious problem with the parser that I've never been able to solve. It was the original reason for not using employed workers for industry conversion (I've since been convinced that it's a good idea regardless).

Your idea of pre-treating the save has merit. THough fixing the grammar would be even better. :-)

**Comment by dtremenak** [comment]
The grammar is fine...it's a nested object inside an object list.  The storage logic in the parser can't handle that, but it's not a grammar problem.

An object in an object list uses the inObjList flag to figure out where to put its leaves.  That doesn't work when the object contains a nested object (the leaves in the nested object end up written to the previous object at the parent's level, or in this case, since it's the first object, just discarded).  It really needs to be another stack instead of a single flag...that would also allow object lists to nest inside other object lists, which I'm pretty sure Paradox can do but our parser grammar currently omits because it would cause a similar problem with the storage logic to the one you see here.

**Comment by dtremenak** [comment]
Actually I'm not really sure why we use more than one object stack at all.  Keeping the object lists in the same stack would simplify things and probably resolve the nesting problems too.  Just a thought.

**Comment by Idhrendur** [comment]
I think I followed that. Any thoughts on why the parser can't handle generic_ideas.txt from HoI4? Or the new areas and regions files in the latest EU4 patch? :-)

**Comment by dtremenak** [comment]
I don't see a generic_ideas.txt in HoI4. and the nearest file I can find (ideas/zzz_generic.txt) should parse OK on initial readthrough (the "traits = { suchandsuch }" construction is strange but technically legal in our grammar, I think...it would end up as a single-element taglist).

Current EU4 area.txt is definitely illegal in our grammar.  This thing:
bourgogne_area = { #4
	color = { 144 0 32 }
	191 192 193 1877
}
is no bueno.  Objects inside of taglists?  Or "naked" taglists at the trailing end of objects?  Either way, that's new and different.  Offhand I have no good idea for how to adequately represent that in the grammar....I'll think about it.

Current EU4 region.txt looks OK at first glance.  Should end up with a bunch of single-taglist objects from it.  What does it actually do?

This is all without actually TRYING any of those files...I can try to make some time this weekend to run some tests.

**Comment by wzh190015** [comment]
I write a  simple [paradox parser](https://github.com/wzh190015/ParadoxParser) by C#. It does well in parsing my Vic2 save file. Nested objects are parsed correctly.

**Comment by Idhrendur** [comment]
Those were the files (sorry I was more specific, I was shutting things down to go to bed). The ideas does choke, and I think it was traits that caused the problem. I can't remember off the top of my head, but it's obvious if you try to run it.

**Comment by Idhrendur** [comment]
Area.txt is actually in this issue: https://github.com/Idhrendur/paradoxGameConverters/issues/170

I should have just linked you there.

**Comment by Idhrendur** [comment]
Whz190015: Well, I'd rather try to fix our existing one than try to integrate a new one in a different language (that's a lot of work). But maybe you'll have some insight into ours if you look at it. As you can tell, I'm not that great with the parser, despite doing really well in that class in college. :-D

**Comment by Prem-is-bored** [comment]
wzh190015, is it possible to put your parser into the converter?

**Comment by Prem-is-bored** [comment]
I personally noticed that it says:
```
Clearing stack size 3 - this should not happen in normal operation
brittany_area= 
{
	color={"118" "99" "151" }
}

169=
{
}

169=
{
}

```
This means that the parser may have issues to do with stack sizes (but it may still have issues with leader traits).

**Comment by Idhrendur** [comment]
Yep, that's the area.txt problem above. The stack is used to construct the parse tree and if the file doesn't match the grammar, it clears the stack so it can try to continue.

**Comment by wzh190015** [comment]
Any tutorial for boost::spirit::qi or it's EBNF grammar? The official tutorial is too brief.

**Comment by Idhrendur** [comment]
No good ones I've found. That's half my problem, I think. It wouldn't be so bad if the lexing and parsing components were separated, but instead they're blended so you can't always tell if you're just not generating a token or if the grammar itself is failing.

**Comment by Idhrendur** [comment]
And the problem is resolved just a day later. Indefinite hold was short.
