### ISSUE TITLE
Support updated generic focus tree

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#176]
1.3 changed the generic focus tree. The new one should be supported, but the old one kept when converting to older versions.

**Comment by wzh190015** [comment]
Maybe great powers should get more powerful focus tree. Nations should have focus to retake foreign cores.

**Comment by Idhrendur** [comment]
That's a whole different consideration. :-)

We're adding to the generic tree for when we customize NFs, and the generics changed a little for 1.3. This change is just making sure we can match it, not updating the bits we add. That'll be some time in the future.

Also, just wrapped this up.
