### ISSUE TITLE
Some problems about China in EU4-Vic2 converted mod

### ISSUE THREAD

**Issue by wzh190015** [Idhrendur/paradoxGameConverters#179]
- Beijing in EU4 is converted to Tangshan in Vic2.
- Wu and Jianghuai in EU4 should be converted to Nanfaren in Vic2.
- Bai in EU4 is converted to Asian Minor in Vic2,I think it's better to create a new cultrue in Vic2.
- The countrie Xi in EU4 is converted to Xia in Vic2.
- The character on the Yue's flag is '越',but it should be '粤'.They all read 'yue' but '越' means South Zhejiang or Vietnam and '粤' means Guangdong

**Comment by Idhrendur** [comment]
- For Beijing, could you use the province mapping tool to fix that issue? It can be found in the releases section.
- You fixed Wu and Jianghuai
- I've added Bai, though you might double-check my work
- I fixed Xi, it should be auto-generated now
- I reported the flag to the person who tends to work on them. I'm not sure if the characters got copied right (they don't display at all on my computer), so you might want to head to this forum post to verify: https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-v2-converter-flags.790645/page-9#post-22270901
