### ISSUE TITLE
V2toHoI4: Conservative/democratic not converting correctly

### ISSUE THREAD

**Issue by Glanzor** [Idhrendur/paradoxGameConverters#182]
I noticed that in all the Vic2 games I converted to HoI4 so far there is a curious absence of conservative/democratic parties in most nations' parlaments. Especially strange since that seems to be the strongest ideology in Vic2 most of the time.

So I took a closer look at the game files of my last converted game.

This is the upper house of my nation in the converted Vic2 save:

```
fascist=0.15671
reactionary=0.19943
conservative=0.13577
socialist=0.20157
communist=0.08246
liberal=0.14053
anarcho_liberal=0.08340
```

And this is how it ended up looking in the HoI4-history file:

```
democratic = { 
            popularity = 0
        }

liberal = {
            popularity = 8
        }
        
socialist = {
            popularity = 20
        }
        
syndicalism = {
            popularity = 0
        }
        
ancap = {
            popularity = 8
        }
        
fascism = {
            popularity = 16
        }
        
communism = {
            popularity = 8
        }
        
autocratic = {
            popularity = 14
        }
        
neutrality = { 
            popularity = 0
        }
```

All the other parties are there with mostly the same numbers but something has obviously gone wrong with the conservatives.

I don't now enough about programming to find out what, but maybe someone else can take a look at that?

**Comment by Idhrendur** [comment]
Thanks, it's been labeled so I can address it when I work on Vic2 to HoI4 next.

**Comment by Idhrendur** [comment]
Looking at the code, I'm not surprised things are going awry. The code is a complete mess. I'm not going to be able to address it for awhile, so I'm going to close this out until I start working on country internals.
