### ISSUE TITLE
Improve ruler generation

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#183]
"I know how we could improve ruler generation. /u/idhrendur
Generate a /common/names/00_names.txt and give each country cultural names based on Vic2 ones. Do this as well for /common/portraits/00_portraits.txt
Then, do NOT create a country ruler in history. Just leave no commander. As soon as you click play, it'll generate a new ruler based on the culture and portrait pool of the two files above."

https://www.reddit.com/r/paradoxplaza/comments/5juvsc/vic2_to_hoi4_converter_01b_now_released/dbkwq3e/

**Comment by wzh190015** [comment]
Should the ruler be generated randomly or use a rule the generate?

**Comment by derHochmeister** [comment]
The game itself will generate the ruler, not the converter. But still, it'd be better to add a historical ruler option that, based on culture and ideology, may give certain countries their historical rulers, like it was in HoI3 conversion.

**Comment by Idhrendur** [comment]
It didn't seem to work as well as I hoped, so I set the converter to generate specific leaders from the name lists it creates. For now it uses the 'unknown leader' portrait, until I do some more work with portraits.
