### ISSUE TITLE
Make an option for civilized/unciv

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#186]
Make it optional whether it uses institutions or tech group.

**Comment by wzh190015** [comment]
There are too many civilized nations in converted mod. Even american and african tribes become civilized

**Comment by derHochmeister** [comment]
Add an option at configuration. You can choose between Tech Group, TG+vanishing Africa and Institutions.

Tech Group: countries are converted to civilization values according to the old system (groups => civilization level)

Tech Group + vanishing Africa: still the old system (groups => civ level), but countries of certain tech groups vanish if they are over 3 techs behind (such groups being West African, Central African, Mesoamerican, Andean, North American and South American)

Institution: current system, based on how many institutions a country has embraced

**Comment by Idhrendur** [comment]
Over on the forums, kratostatic gave a whole proposal for fixing this. Heck, there's a good chance he's got a solution coded up.

**Comment by derHochmeister** [comment]
May I please have a screen of it? I can't access forums.

**Comment by Idhrendur** [comment]
"Ok, so as I'm sure a lot of users of the converter have noted the converted mods tend to have all or nearly all the world civilised at 1836. I've been saying for a while I'd do a post on this so here we go.

First of all a quick discussion of how it works currently. The way that the converter converts currently is based primarily on the number of institutions and the tech group (only the latter for saves pre-1.18/Prussia), with some input from isolationism.

Spoiler: More detailed description
If a nation has all 7 institutions embraced then it is 100% civilised
If a nation has 6 institutions embraced then it is 44% civilised, unless it has the lowest isolationism in which case it is 50% civilised.
If a nation has 5 institutions embraced then it is 36% civilised.
If a nation has 4 institutions embraced then it is 20% civilised.
If a nation has 3 or fewer institutions embraced then it is 0% civilised

Western, Eastern, Ottoman and High American tech group nations are 100% civilised.
Muslim tech group nations are 44% civilised.
Indian tech group nations are 40% civilised, as are countries with the lowest isolationism.
Chinese tech group nations are 36% civilised.
Nomad tech group nations are 30% civilised.
Nations in the African tech groups are 20% civilised.
Nations in the American tech groups are 0% civilised.

Note that in the case of conflicts the higher level is used. So an Inca with 6 institutions has a civilisation level of 44%, not 0%, and if you somehow get a Shinto Inca with 0 isolationism then it would be 50% civilised. A Morocco with 4 institutions would have a civilisation level of 44% rather than 20%.

Now the main issue is that all 7 institutions tend to be embraced by most countries by the end of a typical EU4 game, and any nation which has embraced these institutions would be considered 100% civilised.

My proposed solution would be to also take into account the actual tech level of a given nation. Basically my intention would be to create a series of cut-offs so that if a nation was more than, say, 6 techs behind in total (i.e. tech level 30/30/30 or 26/32/32) then it would convert with a civilisation level of 50%. At 12 techs behind it would be 45% and so on. All numbers are purely for illustration and may well change in the actual version of the converter. A nation which is behind on institutions but has kept up on tech will be considered civilised; the reverse is not necessarily true.

My other thoughts are to decouple this entirely from tech groups in saves from 1.18 onwards - basically make it possible to have a bit of a Scramble for Europe. I'm not completely sure if this is the best option though.

Now I have a few saves which I can use to test this. What I would like is a save where the highest tech nations are not in Europe, so I can test what happens in this case.

Thoughts? Other ideas?"

**Comment by kratostatic** [comment]
4fb8a7e14d7b4855d709608062ac2041e9a4904e fixes the issue, or is at least most of the way there.
