### ISSUE TITLE
Convert graphical cultures

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#195]

**Comment by derHochmeister** [comment]
I can just give here the mappings themselves.

**Vic2** -> _Hoi4 _gfx and _2d_

**RussianGC,  EuropeanGC, Generic** -> _eastern_european_gfx, - eastern_european_2d_

**FrenchGC, USGC, AustriaHungaryGC, PrussiaGC, ItalianGC, ConfederateGC, SwedishGC, SpanishGC** -> _western_european_gfx, western_european_2d_

**OttomanGC, MiddleEasternGC, MoroccoGC** -> _middle_eastern_gfx, middle_eastern_2d_

**JapaneseGC, ChineseGC, AsianGC** -> _asian_gfx, asian_2d_

**SouthAmericanGC** -> _southamerican_gfx, southamerican_2d_

**BritishGC, IndianGC** -> _commowealth_gfx, commonwealth_2d_

**ZuluGC, AfricanGC** -> _african_gfx_

**Comment by Idhrendur** [comment]
Thanks!

**Comment by derHochmeister** [comment]
I think we could reuse the culture_map.txt file in this way

`gfx_map = {`

`  link = { vic2 = RussianGC vic2 = EuropeanGC vic2 = Generic hoi4 = eastern_european_gfx`

 ` ...`

`}`

`2d_map = {`

`  link = { vic2 = RussianGC vic2 = EuropeanGC vic2 = Generic hoi4 = eastern_european_2nd`

 ` ...`

`}`
