### ISSUE TITLE
Consider adding older tech to the tech tree

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#196]

**Comment by derHochmeister** [comment]
Do you mean modding new HoI4 techs? I don't think this could work well, considering how difficult it is to mod tech in HoI4.

**Comment by Idhrendur** [comment]
That was the idea. This is mostly an issue with naval techs: it's easy to have no naval techs whatsoever on conversion, and therefore no fleet. Some earlier (and weaker) naval techs would better capture the conversion.

At least the idea. I have to do more research to be sure. This issue is mostly a placeholder to remind myself to do the research.

**Comment by derHochmeister** [comment]
I think modding new techs to the tree would screw it up. To add previous techs, you have to move up all the other ones...

**Comment by Idhrendur** [comment]
After discussion on the forums, we've decided that all nations will get some basic techs so the AI doesn't get confused. Beyond that, there's not a lot of need for older techs.
