### ISSUE TITLE
Review tech mappings

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#197]

**Comment by derHochmeister** [comment]
I'm reviewing them for the next release. To make things work good enough, I dug up HoI4 country history files, to be sure we forget no tech.

**Comment by Idhrendur** [comment]
New tech mappings have been proposed here: https://forum.paradoxplaza.com/forum/index.php?threads/the-vic2-to-hoi4-converter-project-development-thread.915440/page-43#post-23012857

**Comment by Idhrendur** [comment]
https://forum.paradoxplaza.com/forum/index.php?threads/the-vic2-to-hoi4-converter-project-development-thread.915440/page-43#post-23013689

Radu:
"Addendum to Conversion of Tanks, Aircraft and Naval Vessels :

Due to the difference in systems between Vic2 and HoI4, representing the different tech levels of a nations' Tank/Aircraft/Naval Vessel inventory is a tricky affair.

One course of action could be :

= Tanks =

In real-life Great War tanks had been phased out by all major powers by the early '30s. In 1936 most nations had a combination of Tankettes/MG-armed tanks and Light Tanks/Cannon-armed tanks. As a result :

Nation only has Great War Tank researched => All Tanks in inventory are Great War Tanks
Nation has Light Tank I researched => All Tanks in inventory are Light Tank I
Nation has Light Tank II researched => Half of Tanks in inventory are Light Tank I, half are Light Tank II

= Aircraft =

Much like tanks above, converted techs also result in a set ratio of the aircraft in the inventory being converted to specific types.

If Nation has both Fighter and Tac Bomber techs researched => Half of the inventory are fighters, half are bombers
Nation has Fighter I tech researched => Half of Fighter inventory are Interwar Fighter, half are Fighter I
Nation has Tac Bomber I tech researched => Half of Bomber inventory are Interwar Bomber, half are Tac Bomber I

= Navy =

Nation has Destroyer II tech researched => Half of the inventory are Destroyer I, half are Destroyer II
Nation has Light Cruiser II tech researched => Half of the inventory are Light Cruiser I, half are Light Cruiser II
Nation has Battleship II tech researched => Half of inventory are Battleship I, half are Battleship II
Nation has Super-Heavy Battleship I tech researched => Half of Battleship II inventory become Super-Heavy Battleship I"

**Comment by derHochmeister** [comment]
This is about how to convert stockpile, not tech level

**Comment by Idhrendur** [comment]
Recently updated, and seems to be working well.
