### ISSUE TITLE
Review research slot conversion

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#198]
Alternately, edit the national focuses of powerful nations so they don't end up with too many.

**Comment by derHochmeister** [comment]
Remove one slot from the Great Powers. They already have a powerful tech research bonus with the Great Power NS. This would ensure they don't have an excessive advantage over minors.

**Comment by Idhrendur** [comment]
I was planning on pulling it from the NS, actually. But I need to do research and see what countries have how many tech slots in vanilla HoI4. I know the USA has four, and some have two, but more detail would help me figure out a better system. It's probably listed on the wiki, but I've been focusing on other issues first.

**Comment by derHochmeister** [comment]
Default research slots are 2. Great Powers in HoI4 have 4.

To ensure that the Great Powers don't get a such huge bonus, maybe we should remove the research bonus from the NS.

**Comment by Johuotar** [comment]
I checked the hoi4 wiki:
USA: 4+2
Germany, Italy, Japan, United Kingdom: 4+1
France, Soviet Union: 3+2
Most European minors, Canada: 3+2
Most minors outside of Europe, Luxembourg, Bulgaria and Albania: 2+3
New Zealand: 2+4
British subjects require independence to get focuses for two last slots.

Most common max slot amount is 5. Max of 6 is reserved for special cases. Most majors start with 4 unless they are a bit backwards and then they start with 3. 3 is also start for European minors unless they are very weak. Non Euro-minors have 2 except Canada.

My suggestion:
4+1 for high industrial nations that are also large
3+2 for high or average industrial nations
2+3 for low industrial nations or high & average industrial nations of very small size
Uncivilized get 2+3 but have research speed penalty from uncivilized

**Comment by Idhrendur** [comment]
This is what I did:
* Great powers start with four research slots, and get an additional one from a national focus (one less than the generic tree)
* Regular nations start with three research slots, and get two additional ones from national focuses (the second requires more than fifty factories)
* Uncivilized nations start with two research slots, get two additional ones from regular focuses, and one more from the technology sharing focus (instead of research bonuses)
