### ISSUE TITLE
Review political party conversion

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#199]

**Comment by derHochmeister** [comment]
I think we should add a data file to which the converter should look for generation of parties and (if option turned on) historical leaders.

A csv file like this (example below):
(Vic2 tag);(Vic2 ideology);(party name);(historical leader);(historical leader potrait if any)
GER;fascist;NSDAP;Adolf Hitler;Portrait_Germany_Adolf_Hitler.dds
BHU;autocracy;Wangchuck dynasty;Jigme Wangchuck;gfx/leaders/Asia/Portrait_Asia_Generic_2.dds

**Comment by Idhrendur** [comment]
No need for that, historical leaders can be figured out from the ideologies and the HoI4 data files.

**Comment by derHochmeister** [comment]
But still, better to add a csv files for parties.

**Comment by Idhrendur** [comment]
What does it gain us that we wouldn't already know from the data files?

**Comment by derHochmeister** [comment]
It could work for countries that don't exist in HoI4 and have a party in Vic2. Or we could also edit the file to add here the list of alternate country names (e.g. German Reich, Soviet Union, ...)

**Comment by Idhrendur** [comment]
Well, maybe then. But bring it up again when I'm to the point of implementing features that'll create countries that didn't exist in Vic2. It's not relevant until then, and it'll be awhile before I get to that point.
