### ISSUE TITLE
Does not handle special characters inside configuration.txt

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#20]
Specifically, š and ć seem to be causing a converter to not recognize folders, preventing some users from using the converters.

**Comment by Romag** [comment]
Converter also doesn`t recognise cyrillic script in the path to folders. Got some issues with converting because of this.

**Comment by Idhrendur** [comment]
This is because the parser does not handle UTF-8. A version of the parser that handles UTF-8 should be created and used to read in configuration.txt (and any game files using UTF-8).

**Comment by Idhrendur** [comment]
This was done a while back.
