### ISSUE TITLE
Look into converting military leaders

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#201]

**Comment by derHochmeister** [comment]
Vic2 has too many generals and navy leaders, it'd be useless to convert them all.

We should probably set that for how many leaders you have (X generals, Y admirals), you get random generated leaders in HoI4, but in a lower number (X/5 generals, Y/5 admirals)

**Comment by Idhrendur** [comment]
Yeah, that's the big problem. For HoI3, we didn't have enough and had to generate new ones. For HoI4, we have too many and have to eliminate some. Or just leave them out and let the game generate them by itself.

And as always, the devil is in the details.
