### ISSUE TITLE
Enable country mappings

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#205]

**Comment by derHochmeister** [comment]
If we enable them, I can write an event to make the Raj, Malaya and East Indies created as vassals, but we would still need some kind of post-conversion cores based on states, like in EU4Vic2

**Comment by Idhrendur** [comment]
That'll be part of the 0.3 series of changes, and I'll just create all the appropriate atonymous regions during that series. No need for events to do it.
