### ISSUE TITLE
Factions and puppets

### ISSUE THREAD

**Issue by derHochmeister** [Idhrendur/paradoxGameConverters#215]
I think Vic2HoI4 converter should transfer satellites and dominions as puppets, and spherelings and allies as faction members.

Also, about the factions, I think we should add some kind of .csv data file in this way for some special ones:
(Vic2culture or tag);(ideology);(faction name) e.g.:
GER;fascist;Axis
yankee;democratic;Allies
...

**Comment by Idhrendur** [comment]
Factions, puppets, and other diplomacy will all be part of the 0.3 series of updates. When we get to that point, it'll all be discussed on the forum.
