### ISSUE TITLE
Focuses that let great powers ally with each other are inconsistent

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#218]
"And some of the focuses which let great powers ally with each other work different. When the British ally with the Austrians all their faction members also join the Alliance of Austria, whilst when the Russians ally with the Italians the Alliance of Russia keeps existing just without Russia (Russia even ended up at war with the 'Alliance of Russia')."
https://forum.paradoxplaza.com/forum/index.php?threads/vic2-to-hoi4-converter-release-thread.948992/page-12#post-22396454

**Comment by Hamiller78** [comment]
I hope this is at least improved with commit #287. In the latter case in the example the Alliance of Russia would now be dissolved.
