### ISSUE TITLE
Coversion Failed after 26 sec

### ISSUE THREAD

**Issue by SleeplessJake** [Idhrendur/paradoxGameConverters#220]
Whenever trying to convert my EU4 file to Victoria the converter only takes around 30 seconds then fails under the name "Coversion Failed after 26 sec" or such, then follows with "Converting save.... Failed!"

**Comment by Idhrendur** [comment]
You should head over to the release thread on the forums or create a new reddit post on /r/paradoxplaza about this. Share log.txt from the EU4toVic2 subdirectory.
