### ISSUE TITLE
A fixed cultures.txt fixes some noculture problems

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#221]
Some of the weird noculture problems in Vic2 are fixed by this modification to cultures.txt:  https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-17#post-22397779

No idea why it works, but add it to the converter anyways.

**Comment by derHochmeister** [comment]
This issue can be closed. The converter now doesn't noculture anymore.
