### ISSUE TITLE
The annex union country decision can annex released colonies

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#225]
Events 60120 and 60130 are the culprits.

**Comment by derHochmeister** [comment]
Currently solving it in the next release.

The thing to do is to be sure that the sphereling's capital is in the Old World.

**Comment by derHochmeister** [comment]
Fixed in https://github.com/Idhrendur/paradoxGameConverters/issues/291

**Comment by kratostatic** [comment]
And implemented in 7b430c37f59fa7a4156d622f7c69eed6c599e6e0.
