### ISSUE TITLE
CSA and Taiping have no land

### ISSUE THREAD

**Issue by wzh190015** [Idhrendur/paradoxGameConverters#230]
USA and China,if exists,will fight with CSA and Taiping with no land,and the war will never end.

**Comment by derHochmeister** [comment]
`\events\Taiping.txt` Event 160001 and `\events\ACW.txt` Event 16000 are the problems.

Basically, because CSA and Taiping are coreless and those event base the territory to give 'em on their cores.

**Comment by derHochmeister** [comment]
The solution is to either ensure CSA and Taiping have always cores or to remove those events at all.

**Comment by Idhrendur** [comment]
Ah wait, is this an Eu4 to Vic2 issue? I thought it was a Vic2 to HoI4 one.

**Comment by derHochmeister** [comment]
Yes, Eu4Vic2 issue.

**Comment by derHochmeister** [comment]
Currently working to make the Postcolonial decision adding CSA cores through their OTL land and making Taiping have cores over the Nanking region (which they "owned" during the rebellion)

**Comment by derHochmeister** [comment]
Fixed in https://github.com/Idhrendur/paradoxGameConverters/issues/291

**Comment by kratostatic** [comment]
And implemented in dbe01df2729acd649eed786817885e194c5125be .
