### ISSUE TITLE
Convert world tension to HoI4

### ISSUE THREAD

**Issue by derHochmeister** [Idhrendur/paradoxGameConverters#231]
I think that Great Powers' badboy should be converted to HoI4 world tension, divided by 10.

**Comment by wzh190015** [comment]
May be it's better for all the nations' badboy got converted.

**Comment by derHochmeister** [comment]
Great powers should get a bigger world tension, to reflect how much important in the world peace they are.

As for naming the threat, I'd just say "Recent history of [country]"
