### ISSUE TITLE
"The Italian Question" can cause crashes

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#236]
The event "The Italian Question" can cause crashes. It should be edited or removed to avoid this problem.

**Comment by derHochmeister** [comment]
Can't find the event you're referring to. If I knew which one it is, I'd fix it immediatly.

**Comment by kratostatic** [comment]
Are we sure that's the exact name?  I just searched every localisation file for it with no luck.

**Comment by Idhrendur** [comment]
I tried looking for whatever reference convinced me to open this issue, but can't find it on the forum threads or on reddit. Closing, and if it comes up again we can deal with it then.
