### ISSUE TITLE
EU4 1.20 mechanics to convert

### ISSUE THREAD

**Issue by derHochmeister** [Idhrendur/paradoxGameConverters#237]
# Suggestions

- The three different monarchies of Victoria 2 should also be based on **absolutism** level in EU4 (as from 1.20 patch). I suggest adding an _absolutism_level > [value]_ and _absolutism_level < [value]_ in the government mapping file.

- The **mandate of Heaven** mechanics should work more or less like the HRE ones, thus giving you a faster option of unifying China if you have enough westernization level.

- **Isolationism** mechanics should be counted to generate westernization level, as well. Therefore, an ultra-isolated Japan should probably not be western.

# Notes

I can write the decisions and update the governmentmappings, as well as creating tags and flags for the new countries but I don't know how to code. Also, I'll be fixing the German unifying decisions to not force you to conquer Austria.

# Edits

- The flags to be used for Chinese Mandate of Heaven should be _emperor_heaven_ and _member_heaven_. At least, these are what I'm using in the events. I'm also adding news entries for the unification of HRE and for unification of MoH.

**Comment by TravisRidge** [comment]
How well does the absolutism actually map with the Victoria 2 governments though? EU4's seems to be more feudal vs centralized while Vic2 is more democratic vs autocratic. I'm not sure how the mechanics actually interact with the EU4 constitutional monarchy so I can't comment on that.

At the very least Prussian constitutionalism could map with low absolutism, since feudal rulers and upper class voting seem close enough to count.

**Comment by derHochmeister** [comment]
Prussian constitutionalism should be used by default by Prussian monarchy countries.
I think it should be so:
- below 20%, HM's government
- between 20% and 60%, Prussian constitutionalism
- over 60%, Absolute monarchy

**Comment by TravisRidge** [comment]
Prussian monarchy probably shouldn't convert to Prussian Constitutionalism by default, even in vanilla Vic2 Prussia starts as an Absolute Monarchy. It's a misleading name.

**Comment by derHochmeister** [comment]
Okay, Prussian monarchy won't get default-mapped to Prussian Constitutionalism but, still, if not enough Absolutist, it still will.

**Comment by wzh190015** [comment]
Japan should be united around the shogun or have a dicission to unite Japan.
Chinese tributary states should be in the sphere of China.

**Comment by wzh190015** [comment]
There are to many civilized countries after converted.
I think allow all the country in V2 should be allowed to establish a colony so we will not see so much blank provinces in the map.

**Comment by derHochmeister** [comment]
The converter has the 1.20 and the 1.21 update fixed.
