### ISSUE TITLE
Converter changes files codification

### ISSUE THREAD

**Issue by derHochmeister** [Idhrendur/paradoxGameConverters#239]
The EU4-Vic2 converter sadly changes files codification, making many cultures vanish and destroying any word with diacritics.

**Comment by Idhrendur** [comment]
Part of that is Vic2 using a different file encoding (8859-15), where EU4 uses UTF-8. Some of those are going to get destroyed no matter what we do, because Vic2 just can't represent them.

If you have particular examples of ones that still get missed though, I can try to fix them.

**Comment by derHochmeister** [comment]
Vic2 reads UTF-8 correctly. But the converter copies files decodified and
diacritics are all screwn up.
