### ISSUE TITLE
Remove owner cores on protectorate provinces

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#24]
"If I could make a suggestion cores located on provinces which would become protectorates upon conversion(in a situation where the core owner controls the province in question) should have said cores removed. This is more consistent with the logic of vanilla Vicky 2."

https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-145#post-19618784

**Comment by derHochmeister** [comment]
Make the core system work like the culture system: don't make provinces cored in least than 20 years (primary-cultured) or 50 years (non-primary-cultured) have such cores.

**Comment by kratostatic** [comment]
I'm not quite sure what is meant by "protectorate" here.  Does it refer to colonial protectorates (eg Canada for the UK) or satellite states (eg Wallachia for Ottomans)?

**Comment by Idhrendur** [comment]
I believe it's colonial protectorates. I'd suggest asking if it weren't a two-year-old post. Then again, the poster is still active, so they might recall what they meant.

**Comment by kratostatic** [comment]
That was what I thought, just thought I should confirm.  Thinking about it satellite states won't normally have cores from the overlord anyway so that's fine.

**Comment by kratostatic** [comment]
On thinking about this again, they probably meant the old EU4 subject type of protectorate, which hasn't been a thing in EU4 for a few versions now, so I think this can be safely closed.
