### ISSUE TITLE
Found a mod to fix flag flicking in HoI4 conversion

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#242]
https://steamcommunity.com/sharedfiles/filedetails/?id=850835220

If the creator agrees, we can add the code to the converter. It works with all countries but to the ones that the converter will find "flagless".

**Comment by Idhrendur** [comment]
I can double-check their work (it looks like they give tacit permission to just use it). But there was also an official method to fix it on the forums (with the drawback that it meant the mod couldn't work with some video cards).

**Comment by Idhrendur** [comment]
Found the link to the flag issue: https://forum.paradoxplaza.com/forum/index.php?threads/hoi4-dev-diary-squanching-them-bugs.995110/page-4#post-22333853

**Comment by derHochmeister** [comment]
Better checking the mod before, since the official temporary solution would melt the computers of manies.

**Comment by Idhrendur** [comment]
This is in the FAQ, so good enough for now.
