### ISSUE TITLE
Cleaning Africa

### ISSUE THREAD

**Issue by derHochmeister** [Idhrendur/paradoxGameConverters#244]
EU4Vic2 conversion bases country vanishing on geographical location, while it should be on tech group.

It'd make more sense to make West African countries disappear, instead of forcing UK to own the Gambia (maybe UK did not even exist) or, if an African country owned regions outside its coreland, to be weirdly exiled.

The tech groups that would get "removed" should be West African and Central African.

The converter should have options like:

* Keep all

* Clean West African only

* Clean East African only

* Clean both West and East African

* Province-based remotion

**Comment by wzh190015** [comment]
It's better to remove all the desert and jungle region but not the whole country.

**Comment by derHochmeister** [comment]
Better keep both options than forcing either British Gambia or no scramble
at all.
Il giorno 21/apr/2017 05:15, "Muchichu" <notifications@github.com> ha
scritto:

**Comment by derHochmeister** [comment]
My proposal is highly unpopular and would not satisfact enough converter users. Better to stick with the current system.
