### ISSUE TITLE
Special national spirits for converted countries

### ISSUE THREAD

**Issue by derHochmeister** [Idhrendur/paradoxGameConverters#249]
May this will just be an idea, but I think we could make the converter give national spirits at start like in vanilla:

*monarchies should get a `conv_is_monarchy` "King of [country]" NS, with the image `king_george_v`, whose effect is a +5% national unity

*great powers NS should get `generic_production_bonus` as image

*uncivilized nations should get a `conv_is_uncivilized` "Tribal country" NS, with the image `idea_generic_agrarian_society`, whose effects are the reverse of great power ones

If someone would like to code the converter to generate it, I'd be happy to create the needed data files for it.

**Comment by Idhrendur** [comment]
We've already got great power and uncivilized ones.

I don't have a problem with monarchies getting them, but if so then all governments should get specialized national spirits. I'll ask the forum thread for ideas.

**Comment by derHochmeister** [comment]
I was more trying to get NS like in Vanilla, where monarchies would have
their King as one to increase NU.
Il giorno 23/apr/2017 02:11, "Idhrendur" <notifications@github.com> ha
scritto:

**Comment by derHochmeister** [comment]
This issue is to be merged with other issue https://github.com/Idhrendur/paradoxGameConverters/issues/285

**Comment by Idhrendur** [comment]
Agreed.
