### ISSUE TITLE
Building World crash

### ISSUE THREAD

**Issue by Metriximor** [Idhrendur/paradoxGameConverters#252]
When converting from EU4 to Vic2 in a game from a converted CK2.

I set all directories that the game asked and all my preferences, but when I press save configuration and convert, the converter starts doing it's thing and then suddenly stops in the line Building World.
The log file doesn't say anything is wrong other than a warning in the first lines, (which I found was harmless)

So I tried manual conversion, and found out that when attempting to convert this save file(I am in version 1.19.2 using the version 1.0E of the converter) to Vic2 it goes just fine until the Building World, where the program crashes with a normal windows crash saying the program stopped working.

I checked with a normal save and it was fine, I also checked if it was any lack of memory problems but there is nothing wrong, it's just this save(or any save) from a converted file crashes

This is my first time in github, if I forgot something I am sorry, I will attempt to fix it

**Comment by derHochmeister** [comment]
The best I can suggest you to do is to upload your save and the CK2 export mod so we can see if it is a problem of the converter or of the save file.

**Comment by Metriximor** [comment]
OK, here is the ck2 export mod:
[mod.zip](https://github.com/Idhrendur/paradoxGameConverters/files/955241/mod.zip)

And here is the save file:
[savefile.zip](https://github.com/Idhrendur/paradoxGameConverters/files/955267/savefile.zip)

**Comment by derHochmeister** [comment]
Your file is probably corrupt because not even EU4 can handle it.

There's nothing more I can do.

**Comment by Metriximor** [comment]
my eu4 can open it? weird maybe it's because of the compression

**Comment by derHochmeister** [comment]
That's the file I used for conversion and for EU4. I also used the mod you gave.

I don't seriously know what on Earth is happening.

**Comment by Metriximor** [comment]
I'm gona clear the cache files and come back too see if my eu4 is broken or something.

**Comment by Metriximor** [comment]
Ok, here's what I gathered, to be able to play it I need to have all these mods:

**Comment by Metriximor** [comment]
Ok, after completely unninstalling and installing the game, and testing it in another 2 computers(I asked a friend) I came to the conclusion that to play this game I require 2 mods: the converter mod and Slvrbuu's Eu4 Cheat mod, is the converting problem related to this?

**Comment by Metriximor** [comment]
The problem is related to the mod and the save-file, it has nothing to do with the converter, therefore I am closing this issue.

I wanna thank derHorchmeister for helping me find the problem and the rest of the people that made the converter because it's an amazing piece of software :D
