### ISSUE TITLE
Refactor HoI4Localisation::CreateCountryLocalisations()

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#253]
It's way too big.

**Comment by Hamiller78** [comment]
Would that also include the country names generated from Victoria 2 regions? My vassal Kingdom of West Australia still loses its name in conversion. ;-)
Or is it worth it if I try to fix that before you do the refactoring?

**Comment by Idhrendur** [comment]
That's a good question. It's probably worth solving that (#139) first, just to see what it does to the code organization.

**Comment by Hamiller78** [comment]
I didn't see the other issue. If you are busy with other stuff I can take care of it.

**Comment by Idhrendur** [comment]
If you'd like. I'm going to try and get in the habit of assigning myself to an issue when I start working it to make it clear that I'm doing so. Which means that any issue I haven't assigned myself to is up for grabs.
