### ISSUE TITLE
Cultures sometimes are not converter when primary

### ISSUE THREAD

**Issue by derHochmeister** [Idhrendur/paradoxGameConverters#259]
EU4Vic2 converter doesn't consider if a culture is primary in a province. If I export a EU4 1821 bookmark into Vic2, the American culture spread all over the US is reduced to just a little New England province.

I think that the value to determine culture percentage should add a basic 50% when that is the province's culture anyway. Or else, you must play the game other 200 years to hope to get American culture in the Americas.

**Comment by Idhrendur** [comment]
Working as designed. As discussed many times over the course of this project, EU4 culture in a province only represents the 'upper crust' of society. You'll find that the upper classes and middle classes do convert at 50%, and that only the lower class is slower to do so.

**Comment by derHochmeister** [comment]
But the culture-based cores don't work this way.

**Comment by Idhrendur** [comment]
Also WAD. Culture-based cores are based on the overall population, which converts slower. So on conversion, you just might face the same pain many nations did as they transitioned into the 19th century and beyond. This is intentional.

**Comment by derHochmeister** [comment]
This is perfect in the old world. What I meant is in the Americas, for example, it is impossible to get US or CSA cores and this is bad as it makes colonial powers easier.

**Comment by Idhrendur** [comment]
Ah, that's this issue: https://github.com/Idhrendur/paradoxGameConverters/issues/146
