### ISSUE TITLE
Remove references to unused ideologies

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#260]
"My main complain is that the converter doesn't remove ideologies from the game if it doesn't convert them. It's confusing to see all fascist nations from Vic2 as non-aligned when fascism still exists in their parliaments and through advisers and foci. That is probably one of the main reason so many people in this threat report the non-conversion of minor ideologies as bugs - if they were completely removed the intent would be clearer and there would be less confusion. My suggestion is to put the ideologies (as well as the associated events, advisers and foci) all in separate files so the converter can only copy those over that are needed."

https://forum.paradoxplaza.com/forum/index.php?threads/vic2-to-hoi4-converter-release-thread.948992/page-18#post-22749744

**Comment by derHochmeister** [comment]
The converter now gives the choice between letting or remoting minors' ideologies. This issue is solved, isn't it?

**Comment by Idhrendur** [comment]
Nope! If you remove the minor ideologies, HoI4 will still display them. This change would make it so they don't appear in game at all.

**Comment by Idhrendur** [comment]
The first bit of this is done, but with the ideologies gone, some other data files have been affected.

**Comment by Idhrendur** [comment]
Phew, this is finally done! I haven't been able to test with saves that drop absolutism or democracy (as none of the sample saves do so), but it works for dropping the other ideologies.
