### ISSUE TITLE
Addition of Tibet in CK2 - new titles

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#268]
The soon-to-be addition of Tibet in CK2 will create new titles that will need to be converted.

I can design the flags and do the work all by myself, I just need to know how did you guys create the ck2mappingfile so easily so that I could possibly reduce the work needed for it from weeks to minutes.

**Comment by Idhrendur** [comment]
That file was created by @PTSnoop, I don't know if he had any tricks or not.

**Comment by derHochmeister** [comment]
Surely he had. The Papal States are not in the Pirate Empire in CK2.

**Comment by IohannesIohannium** [comment]
The patch is out. By a fortnight's time, there should be ready.

**Comment by kratostatic** [comment]
Implemented in 1.0H.
