### ISSUE TITLE
EU4ToVic2: Update port blacklist

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#28]
"Hi, I just used this converter for the first time, and Vic2 was crashing while converting history until I added the following to port_blacklist.txt: 2357

Seems to work flawlessly after that. Thanks to everyone who worked on this converter!"

-https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-152#post-19930314

**Comment by dtremenak** [comment]
Fixed blacklist/whitelist test mode, ran tests.  Port blacklist has been updated.
