### ISSUE TITLE
Improve elections

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#280]
The USA in the base game allows you to select whether the republicans or democrats win the election. Similar events should be generated for all converted countries, for extra flavor.

**Comment by derHochmeister** [comment]
We must first convert election and then we can think up how to add them flavor.

**Comment by Idhrendur** [comment]
I added elections the other day.

**Comment by derHochmeister** [comment]
Fantastic. Then, I'll try to get flavor events for republics.

**Comment by Idhrendur** [comment]
I had been thinking more of giving a choice between available Vic2 parties. It'd mean generating events dynamically, is all. Or am I misunderstanding the whole range of possible election events?

Were they just these events? http://www.hoi4wiki.com/Election_events
What needed changing to make them work again?

**Comment by derHochmeister** [comment]
Idhrendur, I also readded those events back. You simply completely blanked out the file they were from.

But I also added a new event whose work is like above.

**Comment by Idhrendur** [comment]
All election events are in and confirmed to be working. The only thing left is adding the localisations to all languages.

**Comment by Idhrendur** [comment]
All the default election events are in, but need localisations for non-English languages.

I still want to add ones like the default USA ones that allow you to select a party.

**Comment by IohannesIohannium** [comment]
Give me the English localizations file and I can try to translate it a bit.

**Comment by Idhrendur** [comment]
Thanks! It's just https://github.com/Idhrendur/paradoxGameConverters/blob/Vic2ToHoI4/Vic2ToHoI4/Data_Files/blankMod/output/localisation/events2_l_english.yml, starting at line 180. On the whole, it's just taken from the default localisations, but slightly edited at times for radical and absolutist.

**Comment by IohannesIohannium** [comment]
I give you pastebins with the translation that starts from that file's line 180. Obviously, it is machine translation and there may be errors.

- https://pastebin.com/eSEp3PRX (l_braz_por)
- https://pastebin.com/GGMLXd1P (l_french)
- https://pastebin.com/J7LrVSiY (l_german)
- https://pastebin.com/7Gvw5T6Y (l_polish)
- https://pastebin.com/V2hsS7pN (l_russian)
- https://pastebin.com/WEBP5ZrQ (l_spanish)

**Comment by Idhrendur** [comment]
Thanks! Now the only thing left is regarding the event that allows you to chose a party the wins the election. We're running across the issue where only so many options can fit on the event pop-up. I know others have complained about it, so I don't know how easy it is to fix, but it's pretty bad if we can't.

**Comment by kratostatic** [comment]
Just a suggestion on the event front - can't you just have one of the event options be a "see other options" trigger?  So the event would look something like (I don't quite know how you're implementing the parties exactly so with apologies to Monty Python for the examples):

- The Romans
- The Judean People's Front
- The People's Front of Judea
- See more options

The last option immediately triggering another event which has more parties:

- The Judean Popular Front
- The Judean Popular People's Front
- The United Judean Coalition Against Roman Occupation
- See yet more options/go back to first selection

That's how CK2 does changing council position so the engine shouldn't have any issues unless HOI4 is somehow worse at this, and if an actual Paradox can get away with this kind of UI clunkyness a mod conversion tool definitely can.

**Comment by Idhrendur** [comment]
@kratostatic That's a pretty good idea. Though I've been told on the forums that changing the event window size is actually quite easy, so it'll probably not be necessary. But thanks, just in case!
