### ISSUE TITLE
Spheres of influences in HoI4

### ISSUE THREAD

**Issue by derHochmeister** [Idhrendur/paradoxGameConverters#283]
Sphered countries in Vic2 should get converted to puppets in HoI4 according to some factors, rather than stopping having any ties.

- If a country is sphered, has the same primary culture as the overlord but is neither their neighbours or in their same continent, they should be converted with `autonomy_dominion`

- If a country is sphered, has not the same primary culture as the overlord, nor on their same continent/a neighbour, but they are civilized, they should be converted with `autonomy_colony`. If they are uncivilized, they should be annexed by their overlord in the conversion (like British Raj)

- Other sphered countries, that are in the same continent/a neighbour of the overlord, they should be converted as `autonomy_integrated_puppet`

These autonomies work only with who has the Together for Victory DLC, so things should be settled this way (this goes in the overlord history file):

`if = {`
`	limit = {`
`		has_dlc = "Together for Victory"`
`	}`
`	set_autonomy = {`
`		target = [puppet tag]`
`		autonomous_state = [autonomy_state, according to rules above]`
`	}`
`	else = {`
`		puppet = [puppet tag] #ONLY if puppet or colony; elseway, don't make this line at all`
`	}`
`}`

**Comment by Idhrendur** [comment]
Spheres have been discussed on the forums. Making them into puppets is far too strong a connection. We're thinking something more like a bonus to trade, a guarantee, and a bonus to diplomacy.

**Comment by derHochmeister** [comment]
What about `substate` and `vassal`? Shouldn't they be converted to puppets (or annexed if uncivilized)?

**Comment by Idhrendur** [comment]
Yep! Actually done back in this commit: https://github.com/Idhrendur/paradoxGameConverters/commit/c285e282d360ad3828e42f947704f4c3d91e141d
