### ISSUE TITLE
Some countries don't have a correct mapping equivalent

### ISSUE THREAD

**Issue by derHochmeister** [Idhrendur/paradoxGameConverters#289]
I discovered that in the EU4Vic2 conversion, some countries don't have a mapping equivalent. Some others, instead, have wrong mappings (Zhou=>Wu, Jangladesh=>Jan Mayen).

Furthermore, Qing, Qin and China are mixed up and the mapping file isn't always clear enough, as it should say always what country is being mapped in the line.

I'm going to fix it for the next release.

**Comment by derHochmeister** [comment]
Fixed in https://github.com/Idhrendur/paradoxGameConverters/issues/291

**Comment by kratostatic** [comment]
Ok, as this is fixed in #291 I'm going to close this.
