### ISSUE TITLE
Frontend can't decompress EU4 saves

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#298]
EU4 started using a new compression format, making the frontend unable to automatically decompress saves. Either the new format should be supported, or a more clear error message should be added instead.

**Comment by IohannesIohannium** [comment]
To decompress files, one should rename it to ".zip", open the archive and find there the savefile proper. Has it changed?

**Comment by kratostatic** [comment]
That is the change - I believe the frontend used to decompress automatically or at least give a slightly more informative error message.

Also I'm afraid I don't think I can do this one if it is in the frontend - I don't speak C#.

**Comment by Idhrendur** [comment]
@kratostatic Nailed it: the frontend tries to do it automatically for you, but it no longer works in newer EU4 patches. When I first looked at the error message everyone asks about in the forums, I saw that it looks like a library call. I'll dig more into this issue.

**Comment by kratostatic** [comment]
You mentioned this was done on the forum?

**Comment by Idhrendur** [comment]
Yes, I did. I don't know why I forgot to close the issue while I was at it.
