### ISSUE TITLE
HoI4 country name generation

### ISSUE THREAD

**Issue by derHochmeister** [Idhrendur/paradoxGameConverters#299]
HoI4 would use special name for any country and any ideology. I propose a generation of names based upon this:

- Neutrality: Kingdom of (country)
- Democracy: Republic of (country)
- Communist: SR (country)
- Fascist: (adjective) State/Reich
- Radical: Commonwealth of (country)
- Absolutist: (adjective) State/Reich

About adjectival forms, they all are the same. I suggest to have those names translated, however, so I made a pastebin to show how they would translate: https://pastebin.com/WFjw1CeU

By implementing this dynamic generation we ensure all countries have special names like they should. Vanilla HoI4 countries would, however, keep their HoI4 names if the country mappings file is left untouched.

About Vic2 special names, the one not present in HoI4 vanilla are:
- the Danubian Federation (communist Austria-Hungary)
- Bavarian Räterepublik (communist Bavaria)
- c̶̶̶o̶̶̶n̶̶̶v̶̶̶e̶̶̶r̶̶̶t̶̶̶e̶̶̶r̶̶̶'̶̶̶s̶̶̶ ̶̶̶s̶̶̶p̶̶̶e̶̶̶c̶̶̶i̶̶̶a̶̶̶l̶̶̶ ̶̶̶R̶̶̶o̶̶̶m̶̶̶a̶̶̶n̶̶̶ ̶̶̶E̶̶̶m̶̶̶p̶̶̶i̶̶̶r̶̶̶e̶̶̶ ̶̶̶a̶̶̶n̶̶̶d̶̶̶ ̶̶̶H̶̶̶R̶̶̶E̶̶̶ ̶̶̶n̶̶̶a̶̶̶m̶̶̶e̶̶̶s̶̶̶

**Comment by Idhrendur** [comment]
So this would replace the importing of names from Vic2?

**Comment by derHochmeister** [comment]
Yes, because Vic2 unique government names are actually really too few and HoI4 Vanilla names already cover them.

**Comment by Idhrendur** [comment]
But then you'd get cases where you have one name in Vic2 and then it changes on conversion. If that happened to my country, I'd find that very annoying.

Plus, it's just not a big enough issue to address. [All features start at -100 points, after all.](https://technet.microsoft.com/en-us/library/dn167709.aspx)
