### ISSUE TITLE
HOI4: Crash after I begin to fabricate a claim for war

### ISSUE THREAD

**Issue by Asmodaus** [Idhrendur/paradoxGameConverters#301]
Crash after I begin to fabricate a claim for war

HOI4 1.3.3

Link to mod
http://dropmefiles.com/fG91j

**Comment by derHochmeister** [comment]
First thing, you're using an old version of the converter, the one that used the placeholder leader. Try converting your save with the latest release.

**Comment by Asmodaus** [comment]
I downloaded the latest version from the github.
If this is not the version where to download the latest one? give me a link

**Comment by Idhrendur** [comment]
I haven't had a chance to look at it (it may be a few days before I do). However, the latest version is the one on the releases tab here: https://github.com/Idhrendur/paradoxGameConverters/releases/tag/Vic2ToHoI4-0.2A

**Comment by Asmodaus** [comment]
Thanks!
