### ISSUE TITLE
Error tith try build realese

### ISSUE THREAD

**Issue by Asmodaus** [Idhrendur/paradoxGameConverters#302]
D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4>set /
p version=Version Number?:
Version Number?:1

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4>call
"\vsvars32.bat"
""\vsvars32.bat"" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4>msbui
ld.exe "Frontend\ParadoxConverters.Frontend\ParadoxConverters.Frontend.sln" /p:C
onfiguration=Release /m
"msbuild.exe" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4>xcopy
 "Frontend\ParadoxConverters.Frontend\ParadoxConverters.Frontend\bin\Release" "V
ic2ToHoI4-1"  /Y /E /I
Не найден файл: Release
Скопировано файлов: 0.

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4>copy
"Vic2ToHoI4\Data_Files\Vic2toHoI4DefaultConfiguration.xml" "Vic2ToHoI4-1\Configu
ration\"
Системе не удается найти указанный путь.
Скопировано файлов:         0.

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4>copy
"Vic2ToHoI4\Data_Files\SupportedConvertersDefault.xml" "Vic2ToHoI4-1\Configurati
on\"
Системе не удается найти указанный путь.
Скопировано файлов:         0.

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4>cd Vi
c2ToHoI4

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4\Vic2T
oHoI4>call "build.bat"

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4\Vic2T
oHoI4>del *.zip /q
Не удается найти D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters
-Vic2ToHoI4\Vic2ToHoI4\*.zip

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4\Vic2T
oHoI4>call "\vsvars32.bat"
""\vsvars32.bat"" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4\Vic2T
oHoI4>del Release /q
Не удается найти D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters
-Vic2ToHoI4\Vic2ToHoI4\Release

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4\Vic2T
oHoI4>rmdir Release /S /Q
Не удается найти указанный файл.

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4\Vic2T
oHoI4>del ReleaseIntermediate/q
Не удается найти D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters
-Vic2ToHoI4\Vic2ToHoI4\ReleaseIntermediate

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4\Vic2T
oHoI4>rmdir ReleaseIntermediate /S /Q
Не удается найти указанный файл.

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4\Vic2T
oHoI4>msbuild.exe Vic2ToHoI4.sln /p:Configuration=Release /m
"msbuild.exe" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4\Vic2T
oHoI4>cd Release
Системе не удается найти указанный путь.

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4\Vic2T
oHoI4>del *.pdb
Не удается найти D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters
-Vic2ToHoI4\Vic2ToHoI4\*.pdb

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4\Vic2T
oHoI4>del *.ipdb
Не удается найти D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters
-Vic2ToHoI4\Vic2ToHoI4\*.ipdb

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4\Vic2T
oHoI4>del *.iobj
Не удается найти D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters
-Vic2ToHoI4\Vic2ToHoI4\*.iobj

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4\Vic2T
oHoI4>cd ..

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4>xcopy
 "Release" "..\Vic2ToHoI4-1\Vic2ToHoI4"  /Y /E /I
Не найден файл: Release
Скопировано файлов: 0.

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4>copy
"\..\..\VC\redist\x86\Microsoft.VC140.CRT\msvcp140.dll" "..\Vic2ToHoI4-1\Vic2ToH
oI4\msvcp140.dll"
Системе не удается найти указанный путь.

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4>copy
"\..\..\VC\redist\x86\Microsoft.VC140.CRT\vcruntime140.dll" "..\Vic2ToHoI4-1\Vic
2ToHoI4\vcruntime140.dll"
Системе не удается найти указанный путь.

D:\Games\paradoxGameConverters-Vic2ToHoI4\paradoxGameConverters-Vic2ToHoI4>cd ..

D:\Games\paradoxGameConverters-Vic2ToHoI4>cd "Vic2ToHoI4-1"
Системе не удается найти указанный путь.

D:\Games\paradoxGameConverters-Vic2ToHoI4>call "\7z.exe" a -tzip -r "..\Vic2ToHo
I4-1.zip" "*" -mx5
""\7z.exe"" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

D:\Games\paradoxGameConverters-Vic2ToHoI4>cd ..

**Comment by Idhrendur** [comment]
Sorry for the lack of build instructions here, I assume everyone comes from the forum thread where I do have instructions. Here's a copy:

**Building the Project**
Once you've gotten the project from source control, you'll need to configure your system to build it. Currently, the project is configured to be built with Visual Studio 2015 (make sure to install both C++ and C# if given the choice). You should be able to build it using a different set of tools, but you will need to configure them appropriately (if you do, feel free to add the project files or make files to the repository).

You will also need to install the latest version of Boost somewhere on your system (anywhere is good). Once that has been done, you will need to set the environment variable BOOST_INCLUDE to the install location of Boost on your system (D:/boost/boost_1_60_0/ on mine), and BOOST_LIB to the location of the Boost libraries within that installation (D:\boost\boost_1_60_0\stage\lib on my system). If you later install a newer version of Boost, you need merely to update those variables to point at the new location. If you are using tools other than Visual Studio, you will likely need to set additional include and library directories within these tools.

Finally, if you wish to package up the build converter using the automated batch files, you will need to install 7-Zip. Once you've done so, set the environment variable SEVENZIP_LOC to the location where it is installed (C:\Program Files\7-Zip on my system). After that, you should be able to simply double-click build_Vic2ToHoI4_release.bat in the main converter directory and have the converter build for you.

**Debugging**
To run the project under Visual Studio itself, you will need to change some settings. In the Solution Explorer, right-click on Vic2ToHoI4 and then click on Properties. In the dialog that opens, select Debugging, and then in the Working Directory field, change the existing setting to $(TargetDir). Visual Studio should now be able to find the data files when you attempt to run the converter from within Visual Studio.

You will need to either place a Vic2 save named input.v2 in the Release directory, or to set the command arguments setting to indicate the save you wish to test with.

The parser runs too slowly under debug mode for that mode to be of any use in debugging the project (it seems to be on the order of hours, but it could be worse. I've never seen it run to completion). Instead, make a release build, and put the line
'#pragma optimize("", off)'
before any functions you wish to examine and
'#pragma optimize("", on)'
after them. If you then place a breakpoint in those functions and run the debugger on the release build (make sure a save file named input.v2 is in the release folder), the data will display correctly in the debugger. If you are investigating a crash and don't know which functions to examine, the call stack seems always correct, so an initial run can show you where the crash happens, you can insert the lines, and then you can run it again to find out why it's crashing.

**Comment by Asmodaus** [comment]
And where can I download the converter already ready? Only experienced users have access to the forum in the right topic. I'm not allowed to go there by the system.

**Comment by Hamiller78** [comment]
Ready-to-use versions of the converters can be downloaded from the release page: https://github.com/Idhrendur/paradoxGameConverters/releases
