### ISSUE TITLE
Fascist puppet of democratic nation status unclear

### ISSUE THREAD

**Issue by Hamiller78** [Idhrendur/paradoxGameConverters#303]
A fascist puppet of a democratic state in a conversion gets a question mark icon in the diplomacy screen instead of the chess piece icon. I have to investigate if the puppet status works and why it gets this icon.

**Comment by derHochmeister** [comment]
The converter hasn't been updated for DoD icons for Fascist puppets. Therefore, it doesn't find the icon.

The solution is an edit to the countrypoliticsview.gfx, which I'm doing for the next release.

**Comment by Hamiller78** [comment]
Thanks for the info. I'll leave this open for now. I should test play the puppet state anyway to see if the autonomy system works.

**Comment by Idhrendur** [comment]
@IohannesIohannium: I finally merged that file, and it fixed things right up. Thanks!
