### ISSUE TITLE
Vic2HoI4 update

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#304]
I'm giving here an update to the datafiles of the converter, as well as some suggestions. I don't know how to pull request, guys, I'm sorry.

Update: https://www.mediafire.com/?qs9gvgc99146d90

Changelog:

- ~~More country mapped, to have special party and name flavors. Such countries are the ones in Darkest Hour, the HoI4 leftovers, the HRE and the Roman Empire~~

- ~~Great Power and Uncivilized NSs now have icons (#249)~~

- ~~Recontrolled tech mappings. Vic2 techs for 1919 mapped to 1936 ones, and 1936 ones to circa 1938 ones. This is to get all vanilla HoI4 starting techs (#197)~~

- ~~Restored election events, adding as well a new one (#280)~~

- ~~Updated some flags of the 1.4 update (ALG, BIH, BUR, KGZ, LKA, MAR, MDA, SVN, TJK, TKM, TUN, UZB, KUK)~~

- ~~Blanked out DoD NF trees~~

- ~~Added company mappings to vanilla factories~~

- Added some data-files to implement: post-colonial cores (#250), faction mappings (#243, possibly #226/#250), unitsound mappings (#290)

- ~~Added missing flags (copyright thing doesn't work on public domain/historical stuff)
SIDENOTE: Dxx flags have not been added since there is no PD image to base on~~

- ~~Ported over new flags from EU4Vic2 converter~~

- ~~Finally added HPM province mappings, correct and with correct VPs (#94)~~

- Corrected Vanilla province mappings (#94)

- Corrected the starting bookmark description
*Now there is a [ideology]_GATHERING_STORM_DESC for a possible generated bookmark
*The generic descriptions has been updated

- ~~Fixed interface errors (#303)~~

SIDENOTE: about the name mappings, only some countries have industry names, even lesser have female names and only majors have callsigns. This is how Vanilla handles it, and how I handled it here.

**Comment by derHochmeister** [comment]
I'm pinning @kratostatic here now, hoping he'll merge these new files.

**Comment by Hamiller78** [comment]
No need to pull kratostatic from his work on the EU42Vic2 converter. I can take care of this.

**Comment by Hamiller78** [comment]
I think the new national focus files from Death Or Dishonor are supposed to be empty, so that they don't get their special trees which don't make sense in the context of a converted game.

**Comment by derHochmeister** [comment]
Yeah, maybe it's better. But triggerless as they are now, they still can't
appear.

**Comment by Hamiller78** [comment]
Wouldn't they appear if there was a Romania in the converted world? I honestly don't know.
But in any case they caused entries in HOI's debug log, because they contain country tags of countries which don't exist in the converted world.
In any case I appreciate your work and I think I can learn a lot about modding HoI from you. I started with understanding focus tree files and am working my way around from there. ;-)

**Comment by derHochmeister** [comment]
I'm not sure what happened. It seems like the update has been forgotten here or am I wrong? I can get the reluctance on vanilla province mappings, but all other things are correct, I can swear, and there's no broken copyright.

**Comment by Idhrendur** [comment]
Not forgotten, just choose a more gradual process to pull it all in, plus not having much time, plus trying to work out all the nuances of my current feature before I focus on this. :-)

**Comment by Idhrendur** [comment]
I've merged in the changed country mappings. I'll push it in a little while. In the meanwhile, I've added a strikethrough on the first post so I can keep track of what's unmerged.

**Comment by derHochmeister** [comment]
Because a new thread would be confusing, these files have to be added to the upgrade as well. In case of overwrite with my previous archive, overwrite.

The new features added by this second upgrade are:
- FAQs updated
- Country mappings revised to make mods' Libya be Libya
- Special cosmetic tags to fix Nazi Germany, Soviet Union and PRC colors
- Restored localisation for the new ideologies' events
- Restored province name upgrader event

[00_HOI4.zip](https://github.com/Idhrendur/paradoxGameConverters/files/1287506/00_HOI4.zip)

About the province renaming event, I can understand you'd prefer it split into different events and based upon culture, religion or something else. The main problem is, there is no sure tag owning that, no there is "culture" at all in HoI4. Better modernize them and be sure that *Edo* and *Christiania* get their names *Tokyo* and *Oslo*, because it is highly improbable they'd not have got these new names.

**Comment by Idhrendur** [comment]
Alright, I've added flags in, for the most part. There were a number where they were the exact same as the Vic2 flags and I couldn't find a common source with a quick google. Can you provide the sources for these ones so we can be absolutely sure we aren't copying from Vic2 without permission?

CHE_monarchy
CHI_republic
DEN_monarchy
DEN_fascist
DOM_monarchy
DOM_communist
ECU_communist
ECU_fascist
ECU_monarchy
ELS_communist
ELS_monarchy
ENG_communist
ENG_fascist
ETH_communist
ETH_fascist
FRA_communist
FRA_fascist
GER_communist
GXI_communist
GXI_fascist
GXI_republic
HAI_communist
HAI_fascist
HEK_fascist
HND_communist
HND_fascist
HON_communist
HON_fascist
HON_monarchy
HON_republic
ICL_communist
IRE_communist
IRE_fascist
IRE_monarchy
IRQ_communist
IRQ_monarchy
ITA_communist
JAN_republic
JAP_communist
JAP_fascist
KAL_monarchy
LAT_communist
LAT_fascist
LIB_communist
LIB_fascist
LIB_monarchy
LIT_communist
LIT_fascist
LUX_communist
LUX_fascist
LUX_republic
MAN_republic
MEW_monarchy
MGL_fascist
MGL_monarchy
NAS_monarchy
NEP_communist
NEP_fascist
NEP_republic
NIC_communist
NIC_fascist
NIC_monarchy
NZL_communist
NZL_fascist
OMA_monarchy
ORA_republic
ORI_monarchy
PER_communist
PER_fascist
PHI_communist
PHI_fascist
PHI_monarchy
PNM_communist
PNM_fascist
PNM_monarchy
POL_communist
POL_fascist
POR_communist
POR_fascist
REB _fascist
REB _republic
REB
ROM_communist
ROM_fascist
ROM_monarchy
RUS_fascist
SAF_fascist
SCH_monarchy
SIA_communist
SIA_fascist
SIA_republic
SPA_communist
SWI_communist
SWI_fascist
SWI_monarchy
SXI_communist
SXI_fascist
SXI_republic
TIB_communist
TIB_fascist
TPG_republic
TRE_fascist
TRE_monarchy
TUN_monarchy
UCA_communist
UCA_fascist
UCA_monarchy
URU_communist
URU_fascist
URU_monarchy
USA_communist
USA_fascist
USA_monarchy
VEN_fascist
VNZ_communist
VNZ_republic
WIA_monarchy
WLL_communist
WLL_fascist
WUR_monarchy
WUR_republic
XBI_communist
XBI_fascist
YEM_communist
YNN_communist
YNN_fascist
YNN_republic
YUG_fascist

**Comment by IohannesIohannium** [comment]
Besides Cherokee (monarchy-straightly copied from EU4), Hesse-Kassel (fascist), Jan Mayen (all, but _seriously_), Orissa (monarchy-straightly copied from EU4), Trieste (monarchy and fascist), UPCA (fascist and communist), Wallonia (communist and fascist) and the ones below, they are the same in both Vic2 and HoI4. If you want them checked as well, ask me. These below are the ones that are only in Vic2 and Real Life:

- Kalat monarchy: https://commons.wikimedia.org/wiki/File:QalatFlag.svg
- Mewar monarchy: https://commons.wikimedia.org/wiki/File:Mewar.svg
- Nassau monarchy: https://en.wikipedia.org/wiki/Duchy_of_Nassau
- Orange Free State republic: https://en.wikipedia.org/wiki/Orange_Free_State
- Schleswig monarchy: https://en.wikipedia.org/wiki/Duchy_of_Schleswig
- Taiping republic: https://en.wikipedia.org/wiki/Empire_of_China_(1915%E2%80%9316)
- Tunisia monarchy: https://en.wikipedia.org/wiki/File:Tunisian_flag_till_1831.svg
- UPCA monarchy: https://en.wikipedia.org/wiki/File:Flag_of_Guatemala_(1851-1858).svg
- Venice fascist (bordure removed): https://en.wikipedia.org/wiki/Venice
- Wiang Chhan monarchy: https://en.wikipedia.org/wiki/Kingdom_of_Vientiane
- Württemberg monarchy: http://www.crwflags.com/fotw/flags/de-wu817.html (last one)
- Württemberg republic: https://en.wikipedia.org/wiki/Kingdom_of_W%C3%BCrttemberg

I hope you don't plan to remove the ones that are present in both games, however. In my opinion, it makes no sense to create variants only because you are playing a modded game rather than vanilla.

If you wish me to create new flags for the ones that are _unsourced_, tell me which ones, I'll try to come up with a design.

**Comment by Idhrendur** [comment]
Doh! I forgot to check if they matched the HoI4 ones, which is a perfectly acceptable case for what we're doing. I'll go back through next time I have a chance and add all those. And thanks for providing sources for the others!

**Comment by IohannesIohannium** [comment]
I'll re-draw the ones with no other source than Vic2 later (Jan Mayen aside), to avoid copyright issues.

**Comment by IohannesIohannium** [comment]
I found a source for Trieste fascist and monarchy: http://www.crwflags.com/fotw/flags/it-tries.html (See Historical section).

Here the other flags that were found only in Vic2, redrawn with unique designs: 
[0.zip](https://github.com/Idhrendur/paradoxGameConverters/files/1352417/0.zip)

**Comment by Idhrendur** [comment]
Alright! That leaves these flags (while the Trieste emblem is on that source, there's enough going in the flags that I'd feel more comfortable if they're redrawn):

MAN_republic.tga
ORI_monarchy.tga
REB _fascist.tga
REB _republic.tga
REB.tga
RUS_fascist.tga
TPG_republic.tga
TRE_fascist.tga
TRE_monarchy.tga
UCA_monarchy.tga
WIA_monarchy.tga

**Comment by IohannesIohannium** [comment]
I already fixed you Orissa (ORI). Also, I provided you the source of
Taiping (TPG), UPCA (UCA) and Vientiane (WIA), just look up in previous
messages. About Rebels, not like there is a different flag. Russia
(fascism) is the same as HoI Soviet (fascist).
I'll look up Manchu Republic and see better about Trieste if I can come up
with a good design.

**Comment by Idhrendur** [comment]
I finally wrapped up merging in your province mappings. Thank you for them, you were right that they were much better than the originals. If you'd like to make updates or corrections to my merging and meddling, this file is what you should work from: https://github.com/Idhrendur/paradoxGameConverters/blob/Vic2ToHoI4/Vic2ToHoI4/Data_Files/province_mappings.txt

With that done, the only files left here are for new features, and referenced in their own issues, so I'm going to close this out.
