### ISSUE TITLE
More dynamic province naming

### ISSUE THREAD

**Issue by kratostatic** [Idhrendur/paradoxGameConverters#317]
A comment on the forum thread noted a while back that a lot of the province names (particularly in the new world) can be a bit strange in converted worlds.  The existing decisions for New York and New Orleans are a good first step for this and I was thinking that I could start by recognising the conditions for these and changing the provinces' names in the converter.

If I can't sensibly use the localised names in the EU4 game (and a quick search shows that they aren't in the save so that probably won't work even before taking into account which name to use for many-to-1/many-to-many mappings) then this will obviously be a pretty huge undertaking.  A sensible midpoint might be to rename all the american provinces using mostly native american names, as they are in EU4 before they are colonised.

**Comment by derHochmeister** [comment]
So... we should add decisions for Native Americans to rename their cities if they haven't been wiped out already by Europeans?

A list of what renamings should be done would actually help the development.

**Comment by kratostatic** [comment]
I was more thinking of changing some (or most) of the default province names to Native American versions and then have decisions for the relevant Europeans to rename the important ones.  The other thing I was thinking was actually coding the logic for your decision so that it happens inside the converter.  Both of these I'd do myself (the first isn't a huge problem anyway).

You've done New York and New Orleans already.  Others could be Washington DC (no idea what to call it), maybe add some of the Californian ones like Los Angeles (City of Angels) and San Francisco (Saint Francis), although those kept their Spanish names on being conquered in actual history so maybe have a short time limit on those.  Also Rio de Janeiro (January River) and maybe Sao Paulo (Saint Paul's, obviously something different for the Arabic group) and Buenos Aires.  Montreal might be worth doing although again it didn't change in real life and I don't know what else to call it.

I can't think of any others which would are obviously named after British/Spanish cities and/or are so big they would have to have a name in the colonising language.

**Comment by derHochmeister** [comment]
So... I'll code renaming decisions for:
-Prince Edward Island
-New Orléans-Louisiana (already in)
-New York (already in)
-New Bedford
-New Plymouth
-Washington DC
-Los Angeles
-San Francisco
-Falklands (if owned by Spaniards)
-Rio de Jainero
-São Paulo
-Buenos Aires

Based on culture groups, Germanic-Beneluxian, Scandinavian, British, Italian, Iberian, French, anybody else.

**Comment by derHochmeister** [comment]
![renaming-table](https://user-images.githubusercontent.com/24550392/28317050-a8ad823a-6bc5-11e7-9d92-d28c41b33ccf.png)

This table shows how I'll put up names. I think for all cities, renaming can be done only once, in 1836. If you have better name ideas or you think I'm missing some more core cultures, please tell, I'll add.

**Comment by kratostatic** [comment]
Most of that looks great!  Where did you get the Washington ones from, those look cool?

French Falklands should be Îles Malouines.  French Prince Edward should probably be Prince Louis Island.

The Scandinavian ones are difficult but maybe use Norwegian cities - Norway are most likely to colonise, Denmark sometimes do but often eat Norway and a Sweden which colonises is probably a human who has probably eaten Norway.  Ny Bergen, Trondheim and Oslo?

New York City in Spanish should be Nueva Zaragoza or else the city should be Nueva Barcelona and the state Nueva Cataluña.

"Good heavens!" is a very mild curse in (British, old fashioned) English so maybe something else for Buenos Aires in English (Fairwind?)

I think for core cultures those are good.  If I start seeing a lot of test saves with other colonisers then we can add more.

And yeah, rename once at the start of the game.

**Comment by derHochmeister** [comment]
Washington literally means "the one from Wass(h)a". I adapted it to each language.

About Scandinavian, Oslo did not exist by that time, at first. Also, I used mainly Swedish cities.

I like your idea for Spaniard New York.

About Good Heavens, yep, I know it. I wanted to do some easter egg.

Other colonizers could be the Slavs, with enough luck. So, I guess I'll add a column for the whole Slavs (Balkan, Polish and Russian). And, just to be sure, a Sino-Japanese one because players may want to be weird.

**Comment by derHochmeister** [comment]
I think I did put all culture groups (beside animals). About Slavics, they're mainly based upon Russian, as Sino-Japanese are on Chinese. For Chinese and Indians, Angels and Saints have been changed with respective religions.
![renaming-table](https://user-images.githubusercontent.com/24550392/28356609-01ae73dc-6c69-11e7-94d5-da4957cfb721.png)

**Comment by kratostatic** [comment]
Looks pretty good!  I'm sure that there will be some awkward ones here and there but we'll need to see what happens when people actually use it.

Should I rename the base name to the "native" one in the localisation file?  I'm thinking it might be easier to have decisions based on one culture group rather than like 12.

**Comment by derHochmeister** [comment]
Yeah, the last column should be used as "default", then the other ones will be used for renaming, so it works.

**Comment by kratostatic** [comment]
Implemented in 1.0H.  May want to integrate the decisions so that the converter does them automatically at some point in the future, or we may not.
