### ISSUE TITLE
AI seldom hires an army

### ISSUE THREAD

**Issue by Asmodaus** [Idhrendur/paradoxGameConverters#320]
HOI4. For some reason, in most countries, AI either does not hire troops at all, or hires very little. Although the number of recruits is large, and the equipment is many. There is a war on several fronts, and the AI does not hire anyone. why? how to fix?

**Comment by Hamiller78** [comment]
Is that in the current version of HoI4 and the converter? I saw it in an older version, when HoI4 was in version 1.3.3. I had to downgrade to 1.3.1., where the problem didn't occured. But I haven't seen it with the later converter versions.

**Comment by Idhrendur** [comment]
Unless we see this in a current version, we'll consider it closed.
