### ISSUE TITLE
Add FAQ item for non-english players

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#321]
If I read this correctly, someone playing in (say) French would get a Vic2 mod that defaults to English. The localisations are there, but the setting is wrong. An update to the FAQ would provide instructions on how to change the setting. Alternately, there may be an easier way to accomplish this.

https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-40#post-23124054

"Hello,

it seems i have an issue this time on the converter :

I used it a lot and stop playing one year ago, i start again this month. So i use the last one (the G version). I play in french (im french myself) in EU4, but the mod i obtain is in english. I'm pretty sure it was in french when i was using it. The problem is that, as the EU4 is in french, the conversion mess with a lot of name of country (the Z/X named country), same type of issue when you do CK2/EU4 with a english CK2 and a french EU4 for an exemple.

Why my converted save is in english ? when what should i do to have it in french ?

Thank you very much,

++

EDIT : I found it !

I suddenly remember what i was doing ! 

So for people experiencing the same issue : 

Go in the mod of the converted save, then in setting.txt, in it there is a language line, language=l_english, change it in what you want (l_french for me). As suspected, it made everything works great (no more X20, Z03...)

See ya !"

**Comment by kratostatic** [comment]
I think it might be possible to extract the language used from the save file (I'm sure I've seen a reference to localisation in it at some point) and edit the settings file automatically in the conversion.  Though I suspect this will have similar problems as editing the defines file.

**Comment by kratostatic** [comment]
FAQ was updated with 1.0H
