### ISSUE TITLE
Peace AI for the new ideologies may not be triggering

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#322]
https://forum.paradoxplaza.com/forum/index.php?threads/the-vic2-to-hoi4-converter-project-development-thread.915440/page-44#post-23126051

"I noticed something weird with these war focuses some minors get, they result in white peace when the defender falls. For some reason the attacker does not annex or puppet anything. This here is one example:

Spoiler
focus = {
id = WarAZRTUR
icon = GFX_goal_generic_major_war
text = "War with Azerbaijan"
bypass = {
has_war_with = AZR

}
x = 24
y = 0
cost = 10
available = {
has_war = no
date > 1936.10.1
}
completion_reward = {
add_named_threat = { threat = 3 name = WarAZRTUR }
create_wargoal = {
type = annex_everything
target = AZR
}
}
ai_will_do = {
factor = 10
modifier = {
factor = 0
strength_ratio = { tag = AZR ratio < 0.8 }
}
modifier = {
factor = 0
OR = {
has_war_with = EGY
has_war_with = GRE
has_war_with = PER
has_war_with = SER
}
}
}
}
My guess is that it happens because the Turks are absolutists and the ideology does not have related peace AI.
Edit: Mod & save uploaded. Converted mod has been changed by me a bit but I doubt it's the cause here."

**Comment by derHochmeister** [comment]
The solution would be to stick the absolutists with the fascist AI or to create a brand new one for them.

**Comment by Idhrendur** [comment]
That's where I'm confused. Don't we already give the ideology an AI?

**Comment by derHochmeister** [comment]
We gave them and the radicals the neutrality AI, which will always do nothing in peace deals but getting their own cores (if any).

Switching radicals to democratic AI and absolutists to fascist AI would make it look more consistent.

**Comment by Idhrendur** [comment]
Ah, I see! Thanks for explaining.

**Comment by Hamiller78** [comment]
Perhaps I can also refine the focusses later to give them a core in a border province and make it a smaller conflict.

**Comment by Idhrendur** [comment]
In commit a90139c, I updated the AIs for the ideologies. Hopefully that should help a little. Further work is in in issue #364.
