### ISSUE TITLE
issues with adjacencies.bin

### ISSUE THREAD

**Issue by whatthebanana** [Idhrendur/paradoxGameConverters#326]
```
2017-08-03 17:52:40    [INFO] Importing province adjacencies
2017-08-03 17:52:40   [ERROR] Could not open C:\Users\something\Google drive\Documents\Paradox Interactive\Victoria II/map/cache/adjacencies.bin
```
Eu4 to Vic 2.
I tried to reload those caches and re-convert, but it didn't work and had the same issue.Is it because the google drive thing, or some other problems?Thanks!

**Comment by Idhrendur** [comment]
It might be the google drive thing, but I've usually seen that happen when you don't have the Vic2 expansions. Do you have them both?

**Comment by whatthebanana** [comment]
It turns out it is the Google Drive thing. Thanks for your help anyway. :)

**Comment by Idhrendur** [comment]
I'm glad you got things working!
