### ISSUE TITLE
Add localisations for generated political events

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#329]

**Comment by derHochmeister** [comment]
If you mean the ones I made for absolutism and radical, then it is already in this (https://github.com/Idhrendur/paradoxGameConverters/issues/304), the second upgrade I posted.

**Comment by Idhrendur** [comment]
Nope, those have been replaced as part of the who mechanism for handling dropping ideologies. That mechanism changes the event numbers, so localisations need to be dynamically set up.

**Comment by Idhrendur** [comment]
No, wait, I was taking a wrongheaded approach. Those will be very useful, thanks!

**Comment by Idhrendur** [comment]
@derHochmeister: So, I redid how the revolution events for ideologies work, and have been making the localisations work. For Absolutism and Radical, there are some new events. Would you mind writing localisations for them? They're the equivalents of political.4 and political.12, and political.5 and political.10. That is, an event that increases popularity for the ideology and can fire once, and another that does the same but can fire repeatedly.

**Comment by derHochmeister** [comment]
If you are adding new events, it'd be better to just link me the new rows you added, so I can know exactly what strings the localisation needs.

**Comment by Idhrendur** [comment]
Sure! This is the full list of missing localisations, by localisation key and language. There are a handful that are missing from the base game in just some languages. I've opened a bug report for those, but if you wanted to put in something in the meanwhile I wouldn't object.

**Comment by derHochmeister** [comment]
Still, not knowing what the options' effects are, I can't do localisations. What does `absolutist_fifty_percent.a` do? What does `-.b`? And so on for all those.

Thanks for providing me what are the missing strings, by the way.

**Comment by Idhrendur** [comment]
I don't have access to HoI4 at the moment, so I can only provide the event numbers and not the titles. However:

* absolutist_add_popularity and radical_add_popularity are like political.4 and political.12. The options are the same as the originals.
* absolutist_military_defections and radical_military_defections are like political.5 and political.11 (or it might be political.10, but the parallel should be obvious). The options are the same as the originals.
* fascism_ideological_sympathies.a.tt is a tooltip missing from HoI4 and probably doesn't matter. Not sure of the event id off the top of my head.
* absolutist_fifty_percent and radical_fifty_percent are like political.18, political.19, and political.20 (demand referendum), and the options are the same as the originals.
* communism_fifty_percent.t in spanish is missing from HoI4, and I opened a bug report about it.
* absolutist_revolution_event and radical_revolution_event are like political.21, political.22, and political.23. The options are the same.
* absolutist_suppressed_event and radical_suppressed_event are like political.24, political.25, and political.26. These events are where revolutions died out. The options should be the same.
* abandon_neutral.d_absolutist and abandon_neutral.d_communism are equivalents to the other descriptions for political.27.
* A bunch of other localisations are missing for abandon_neutral, but only in some languages. These are bugs in HoI4 that I've reported.

**Comment by derHochmeister** [comment]
Okay, I did not add missing vanilla strings, because that is more a vanilla issue, but we could later add them. So, here the localisation files for the new events, already with a name that is unique.

[New strings.rar](https://github.com/Idhrendur/paradoxGameConverters/files/1314636/0.zip)

**Comment by Idhrendur** [comment]
Thanks! I'll get these added in soon, and then probably a release!

**Comment by derHochmeister** [comment]
I hope the release will be after the integration of this https://github.com/Idhrendur/paradoxGameConverters/issues/304.

If you still feel the province mappings are not good, you can try test it. I can ensure they are correct and checked. I just forgot to update that copyright year.

**Comment by Idhrendur** [comment]
I've got some of it integrated, but not all. All things being equal, I'd prefer to get it all in before releasing, but it's been awhile since the last release.

I *did* integrate your mappings in the Americas, but in a way that leaves the file more organized and clear.
