### ISSUE TITLE
Improve const-correctness of pointers

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#330]
I've been using this pattern to define pointers:
const type* variable;

As I recently learned in Effective C++, this makes the pointer const, but not the data it points to! Instead, I should be using this pattern:
const type* const variable;

I should give the code a touch-up to fix this pattern.

**Comment by kratostatic** [comment]
Will this and #331 also be relevant for EU4 to Vic2?  I might as well add this to list of improvements to do whenever I'm messing about with the code.

**Comment by Idhrendur** [comment]
This, #331, and #335 would all be relevant. I'll probably be adding more as I read more of Effective C++. Would you like me to label them as EU4toVic2 as well? With luck, I'll have time to work on them and thus provide examples of what it looks like in code.

**Comment by kratostatic** [comment]
Possibly, the only issue with that would be you presumably want to close these at some point when you've done with fixing up V2toHOI4 which may very well not coincide with when I've sorted EU4toV2.  I'll think about it for a couple of days; I might create my own issue(s) for EU4toV2.

**Comment by dtremenak** [comment]
This is incorrect; you might want to read it again..."const type* variable" is a non-const pointer to a const object, not a const pointer to a non-const object.  "type* const variable" is a const pointer to a non-const object.  Quoting Stroustrop: "...think about '*' as capturing the largest leftward unit that it can. 'Const' captures the smallest unit, left or right, that it can."

Typically you want to use "const type* variable" if you are using raw pointers...most of the time you don't care if the pointer itself is const (pointers are a basic type, and convention calls for non-const basic types for many variables, such as all function parameters...if you would not write "const int", do not write "type* const").

Also, almost anywhere you CAN write "const type* const", you could write "const type&" instead, and have safer, easier to read code.  Do that instead ;)

**Comment by Idhrendur** [comment]
@dtremenak, long time no see! Thanks for pointing out that error. Now that it's right way round in my head, I can see why const type* const would be less desirable.

Incidentally, still interested in adding another C++ programmer to your team? I'm more eager to move than I was a year ago, and wouldn't object to being on a team where someone knows the language better than I do.

**Comment by dtremenak** [comment]
@Idhrendur Yeah, I know I haven't been around much lately...been travelling quite a bit, and not getting much time for the Paradox hobby.  When I do, it's usually Stellaris, and that's not a great motivator for getting back into the converters ;)  I still get all the emails though, and I'll speak up if something shows up that I think a brief comment could help.

FWIW, I think Effective C++ is a great book and I'm glad you're taking the time to go through it and apply it here.  Years ago I read a comment somewhere that said "Nobody ever got fired for following Scott Meyers' recommendations" - and it's true.  You'll only pick up good habits there.  Once you think you've gotten it down, you might want to give "Effective Modern C++" a try, too...the new C++11/14 features are really great, but learning and applying them takes time.

I don't expect our team specifically to be hiring in the next few quarters at least, sorry (unless someone leaves, which I don't think is likely).  I'll let you know if an opportunity comes up, though.

**Comment by Idhrendur** [comment]
Thanks for the feedback! Effective Modern C++ is also on my list, as are "More Effective C++", "Exceptional C++", "Modern C++ Design", and "Effective STL". It's quite the list, but it's exciting to have a list again!
