### ISSUE TITLE
Add an option for only the default HoI4 ideologies to be used

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#344]
It's been requested. More details forthcoming.

**Comment by derHochmeister** [comment]
It'd require a lot of coding, that's for sure, whether it be "just make the other ideologies disappear" or "completely remove them at my will".

**Comment by Idhrendur** [comment]
Given the work I put in for dropping minor ideologies and getting everything straight, I think it shouldn't be too bad. But yeah, *that* was a lot of work.

**Comment by Idhrendur** [comment]
I've got the initial code in, and focus trees are converted. However, governments get mapped poorly, which makes me wonder if they also can get mapped poorly if minor ideologies are dropped.

**Comment by Idhrendur** [comment]
Governments are now mapped properly, but I need to double-check parties are converted properly.

**Comment by Idhrendur** [comment]
Checked, and they aren't, but that's a different issue (#380)
