### ISSUE TITLE
New colonial-split cultures

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#345]
It is kinda unsatisfactory to see that, while English colonies in the New World will fall under "Yankee" or "Dixie" culture, different from the "British" one, colonizing them as a German or as an Indian would make them of your culture, thus making the de-colonization process more difficult and causing cultural cores going weird.

Therefore, I am currently doing a way to convert new colonial cultures, three for each Vic2 culture group but natives (one for Americas, one for Oceania, one for Africa).

I'll also edit the cultural union decision to avoid weird situations where to form Poland-Lithuania you would have to conquer (e.g.) Couronian Fiji.

EDIT: Vanilla post-colonial cultures remain untouched. Yankees and Dixies still exist.

**Comment by kratostatic** [comment]
YES!

How were you thinking of doing this exactly?  I had an idea of editing the cultures files from the code and creating the cultures that were needed, but I'm not really ready to implement that yet (I need to get a bit happier with the parser yet).  If I know what you're doing there might be a "hybrid" solution that would be easier than a pure code or pure data files solution.

Also for the cultural unions it might be best for there to be a decision for each continent, or at least limit the existing one to the Old World (the only vanilla "cultural union" I can think of in the New World is Gran Columbia) and/or continuous territories.

**Comment by derHochmeister** [comment]
I acted the same way as creating a new culture and mapping it thru the use
of regions.

About Gran Colombia, it has already a special decision, so I can restrict
the generic cultural unions to the Old World.

Il 04 Set 2017 20:42, "kratostatic" <notifications@github.com> ha scritto:

**Comment by kratostatic** [comment]
Implemented in 1.0H.
