### ISSUE TITLE
Certain Free Colonies in america infinitely switch tags with "a new government" making annoying flashing and name changing as well as giving them tons of prestige

### ISSUE THREAD

**Issue by SenpaiX64** [Idhrendur/paradoxGameConverters#348]
This happened in one of my conversion to Argentina/Uruguay. Argentina kept switching tags to Uruguay and back using the A new government decision. It looks really annoying and causes the country to gain endless prestige making it number 1 in a matter of days.

![v2_2](https://user-images.githubusercontent.com/31791552/30238288-3770aed2-9512-11e7-85c3-3e3981ac9d4d.png)
![v2_3](https://user-images.githubusercontent.com/31791552/30238291-4372294a-9512-11e7-9095-62ea20fa4bc4.png)
![v2_4](https://user-images.githubusercontent.com/31791552/30238294-4ee4d07a-9512-11e7-8253-7d4dcfed94ba.png)

**Comment by derHochmeister** [comment]
It is a bug of my decisions I didn't manage to find. I'll immediately fix it up. Sorry for the decision-spam.

**Comment by kratostatic** [comment]
fixed by pull request #349

**Comment by kratostatic** [comment]
Oh and @SenpaiX64 , if you want you can download the file referenced in that pull request to fix the issue in your game - just replace the file of the same name in the mod.
