### ISSUE TITLE
Revisit how cultural unions are done

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#35]
The current rules for generating unions exclude a lot of possible uses for expanding that mechanic. Revisit how the entire thing is done in order to make this better.

**Comment by Idhrendur** [comment]
Many more cultures should have cultural unions as possible breakaway nations. Though Vic2 may require that they become their own cultural groups for that to work.

Mayhaps eventually add new nations for potential breakaway nations.

**Comment by Idhrendur** [comment]
Also see point one in this post: https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-177#post-20563139

**Comment by derHochmeister** [comment]
This was fixed.

**Comment by Idhrendur** [comment]
No, it wasn't.

**Comment by derHochmeister** [comment]
In the current release, almost any culture has a precise Vic2 breakaway nation.

What is this issue, precisely? I'd fix it if I knew and I could.

**Comment by Idhrendur** [comment]
Actually, I think that was it and I just never closed this.
