### ISSUE TITLE
HoI4 Stability and War support

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#351]
HoI4 is removing national unity and the converter must be soon adapt to this change.

As scripted in the Dev. Diary, two new values are instead used, Stability and War Support.

I suggest to get stability be determined by a formula based on consciousness and jingoism, while War support should be calculated from jingoism minus the consciousness.

Until we know the main values in the game, we won't be able to do a good enough formula, but it is better to be prepared.

I suggest, however, to keep national unity conversion, in case someone might want to play on an older version of HoI4.

**Comment by IohannesIohannium** [comment]
For stability, I suggest using the formula we use for national unity, but minus 10 (party popularity will add that "10" back)

For war support, I suggest using a "survey" of the population's war policies:
- Each 1% of jingoists gives a +1% of war support
- Each 1% of pro-military gives a +0.5% of war support
- Each 1% of anti-military gives a +0% of war support (they're mostly "meh" with war)
- Each 1% of pacifists gives a -0.25% of war support ("war? i'd rather not")

This should be furtherly reduced by war exhaustion (100% war exhaustion reduces of 20% war support).

**Comment by Idhrendur** [comment]
This is mostly complete, with #524 being a more narrow focus on what remains.
