### ISSUE TITLE
Verify a megacampaign will convert

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#354]
I like this group, and prefer to smooth things out for them. Do a quick check that the mod and save will convert. They're capable of improvements beyond that point.

Mod and save linked here: https://forum.paradoxplaza.com/forum/index.php?threads/our-doom-and-our-pride-multiplayer-megacampaign.1043616/page-2#post-23302612

**Comment by derHochmeister** [comment]
My megacampaign went just fine converter.

Maybe I can see the save and the mod to see if there is a problem?

**Comment by Idhrendur** [comment]
I don't expect any problems, but they use the fan-based CK2 to EU4 converter and a lot of custom changes. This is just a quick spot check I'm doing well in advance of the need, and the issue is a just a 'note to self' kind of thing. No need for anyone else to worry about it.

**Comment by Idhrendur** [comment]
And their game fell apart, so it doesn't matter. They're restarting in CK2 and it might be some time before they get to EU4 again.
