### ISSUE TITLE
Errors with flags

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#355]
The new release of today of the HoI4 converter seems to have returned on making a different flag for each Vic2 ideology, causing so impossibility for absolutist and radical to get their own flags and spamming the folder with _ancap, _autocratic, ...

Also, for some weird reason, some generated flags have problems with alpha-channel, making them turn transparent or semi-transparent.

EDIT: As well, some flags were removed from the conversion folder, thus leading the converter believe they were unimportant. The problem is, we removed also needed files like YUG_communist, as the converter will now use the generic monarchic flag for it...

**Comment by derHochmeister** [comment]
Here is a file containing all the flags that were unjustly removed. They are vanilla Vic2 or HoI4 tags, as well as some from the EU4 Vic2 converter. Secret Denmark has been restored, as it is possible to do a megacampaign with it. The ones you wanted to remove were, almost surely, the colonial ones pasted from EU4Vic2, but you also removed other ones which are needed.

They are extempt from copyright for being historical or original creation.

[forgotten_flags.zip](https://github.com/Idhrendur/paradoxGameConverters/files/1326742/forgotten_flags.zip)

However, the problem with the Vic2 ideology-flag generation still remains and I don't know why did you code it back, as it is completely useless.
