### ISSUE TITLE
Unknown unit type: bomber

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#356]
The new version of the HoI4 converter seems to spam "unknown unit type: bomber" in the log. I haven't tried it yet in gameplay but it is pretty annoying.

**Comment by derHochmeister** [comment]
It was a mod I used in Vic2 that had that unit type.

**Comment by Idhrendur** [comment]
Which mod? We could make sure they actually get converted (I already added units from other mods to the list).

**Comment by derHochmeister** [comment]
Ultimate Mod. It is an ambitious project of covering history in Vic2 from 1604 to 2023, I use it only to have a 1936 start to test.

The new unit types are Bomber, Carrier, Special Operation Infantry, Submarines and Transport Planes. No new technology invented.

I find it bad that old units in Vic2, however, simply vanish. They should get their modernized counterparts in a numerically reduced version.

**Comment by Idhrendur** [comment]
Can you list out the names as they're presented in the units folder of the mod? Both filename and the name from inside the files, just in case.

**Comment by IohannesIohannium** [comment]
Man, I'll just give you the files here, it'll be better.
[bomber.txt](https://github.com/Idhrendur/paradoxGameConverters/files/1368602/bomber.txt)
[carrier.txt](https://github.com/Idhrendur/paradoxGameConverters/files/1368606/carrier.txt)
[specops.txt](https://github.com/Idhrendur/paradoxGameConverters/files/1368605/specops.txt)
[submarine.txt](https://github.com/Idhrendur/paradoxGameConverters/files/1368604/submarine.txt)
[transport_plane.txt](https://github.com/Idhrendur/paradoxGameConverters/files/1368603/transport_plane.txt)
