### ISSUE TITLE
Idk what is wrong with my map

### ISSUE THREAD

**Issue by mandrivnyk133** [Idhrendur/paradoxGameConverters#361]
I have tried several times, changed some settings but result is the same all the time
<img width="960" alt="untitled" src="https://user-images.githubusercontent.com/32285067/30839598-00955f8e-a241-11e7-8216-7f48608b56d8.png">

**Comment by Idhrendur** [comment]
Check log.txt in the converter folder for any errors or warnings. It looks like conversion is not completing.

**Comment by derHochmeister** [comment]
I know this bug. When you play with the mod active, you have to disable vanilla history folder (just add a tilde in the name).

**Comment by mandrivnyk133** [comment]
The method with tilde really worked. Thanks!

**Comment by Idhrendur** [comment]
Sounds like the raplace_path bug being talked about on the forums. I'm told that Paradox is aware and planning to fix it.

**Comment by Idhrendur** [comment]
I added a FAQ entry for this. Hopefully Paradox will fix this issue and we can remove that entry in the future.
