### ISSUE TITLE
Music doesn't play at start sometimes

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#362]
"Other than that and the music not playing upon start, which is old issue, I have not encountered issues."
https://forum.paradoxplaza.com/forum/index.php?threads/vic2-to-hoi4-converter-release-thread.948992/page-25#post-23315475

"Wait, the music doesn't play on start? And it's been doing that for awhile? That's weird. Does it do the same if you turn off all mods?"
https://forum.paradoxplaza.com/forum/index.php?threads/vic2-to-hoi4-converter-release-thread.948992/page-26#post-23323898

"The music problem is a bit weird. It is quite random how it happens. Usually when I start new game one song might play or not. Pressing the big play button on music player fixed the issue yesterday. The small play button did nothing. But I'll have to do some tests to see how consistent the problem is. I dont have any issues in vanilla or kaiserreich (music mod or not)."
https://forum.paradoxplaza.com/forum/index.php?threads/vic2-to-hoi4-converter-release-thread.948992/page-26#post-23323985

"That's really bizarre. Let me know if you find out more about it. I'll open up an issue so we can investigate more."
https://forum.paradoxplaza.com/forum/index.php?threads/vic2-to-hoi4-converter-release-thread.948992/page-26#post-23324979

**Comment by derHochmeister** [comment]
The game can't find due to modded files in the conversion the musics called hearts_of_iron, night_witches, primo_victoria, stalingrad and wolfpack.

Why did we mod music in the first time? Avoiding tag-specific music? I don't think it is worth the effort as it'd make no sense to use a music taught for Russia to be used for Bolivia as well.

**Comment by Hamiller78** [comment]
Oh, those are the Sabaton songs I think. I deactivated the Sabaton music DLC when I tried a conversion because I recorded the game for YouTube. The music player of HoI4 then gets stuck when it tries to play a song of adeactivated music DLC. But that's a HoI4 bug I assume.
So I am not sure if this is really a problem of the mod.

**Comment by Johuotar** [comment]
Ahh, I forgot to say that I don't have allied music pack dlc activated.

**Comment by IohannesIohannium** [comment]
@Hamiller78 Nope, the bug is not linked with DLC deactivation, the song player will stop when it'll hit a Sabaton music. I suggest to remove music modding, as it is actually unnecessary. What's the point of having a song designed for Soviet Union to be played by Rosa Luxembourg as well?

**Comment by Hamiller78** [comment]
Okay, I looked it up. We indeed have definitions for all music DLCs in our blank mod, which probably cause issues with these DLCs if you don't have them or have them deactivated.
In the normal HoI4 directories I don't see anything similar. Perhaps Paradox changed their method of music definitions in one of their updates?

**Comment by Idhrendur** [comment]
Yeah, I added those definitions because I was seeing errors from tags referenced in the originals that didn't end up in converted games. And I can confirm that if I deactivate music DLCs the new scripts throw errors because they can't find the music files. I'm not quite sure what the resolution is.

**Comment by IohannesIohannium** [comment]
I get the thing about tags errors, but at least that didn't stop the music.
Instead, having the Sabaton DLC activated and hitting one of their musics
stops the music playing because no music is found.

**Comment by Idhrendur** [comment]
Well, that would be a preferred solution. If I can't find a way to detect the DLC and act accordingly, I'll just remove those files.

**Comment by Idhrendur** [comment]
https://forum.paradoxplaza.com/forum/index.php?threads/vic2-to-hoi4-converter-release-thread.948992/page-27#post-23394316

"I've been looking into this and can't replicate it. If you edit your mod to remove the music directory, does the problem go away?"

**Comment by IohannesIohannium** [comment]
I can ensure it does.

**Comment by Idhrendur** [comment]
Awesome! I'll make the changes, then.
