### ISSUE TITLE
HoI4 Conversion too pacifist

### ISSUE THREAD

**Issue by Quemares** [Idhrendur/paradoxGameConverters#364]
I converted a Vic2 to HoI4 save and it turns out that while playing, the AI had no interest in moving their armies. Like at all. France had 100 divisions just idle in Paris for example, and all the wars that were started were forever stuck in 50% because neither side would move their armies from their initial position. I ended up with 10 idle wars unless I did joined a side and won because the enemy wouldn't do anything about it.

**Comment by IohannesIohannium** [comment]
I think this is more the incompetent Vanilla AI behaviour rather than mod's fault.

**Comment by Quemares** [comment]
I was curious about that (Maybe HoI4 AI is less agressive than Vic2) but playing the Vanilla game, I noticed that at least, the AI would declare war and go forth trying to win. On my converted save, it will declare war and not do anything at all. It just sits idle even if I decide to get into the war and start taking its territories.

**Comment by IohannesIohannium** [comment]
It may be tied to the units. The ones I get each time I convert are always with no organization and no way to rise it up. And units with no organization will never go outside home country.

**Comment by Idhrendur** [comment]
@IohannesIohannium Could you provide a sample save that gets the units with no organization? I don't see that myself.

**Comment by IohannesIohannium** [comment]
I don't know why, but the file lines are correct and do not mention organization at all... Maybe it was just a bug with my conversion? After having tried a second conversion, it resulted to be so. Sorry for alarming you people.

**Comment by Idhrendur** [comment]
@Quemares: Can you upload a Vic2 save that has this problem, as well as any mods, so that I can try and replicate this issue?
