### ISSUE TITLE
Absolutism focus does not seem to give the absolutism idea anymore

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#367]
It's because of my fix to the rest of the focus.

https://forum.paradoxplaza.com/forum/index.php?threads/vic2-to-hoi4-converter-release-thread.948992/page-26#post-23330663

**Comment by IohannesIohannium** [comment]
The focus-entry in question is this:

```
	focus = {
		id = absolutism_focus
		icon = GFX_focus_hun_elect_a_king
		prerequisite = { focus = collectivist_ethos }
		mutually_exclusive = { focus = nationalism_focus focus = internationalism_focus focus = radical_focus }
		x = 20
		y = 2
		cost = 10
		available_if_capitulated = yes
		available = {
			OR = {
				has_government = absolutism
				has_government = neutrality
			}
		}
		completion_reward = {
			add_ideas = absolutism
		}
		ai_will_do = {
			factor = 5
			modifier = {
				factor = 2
				any_neighbor_country = {
					is_major = yes
					has_government = absolutism
				}
			}
			modifier = {
				factor = 0
				AND = {
					is_historical_focus_on = yes
					NOT = { has_government = absolutism }
				}
			}
		}
	}
```

The error is that is it not absolutis**m**, but absolutis**t**. The rest of the tree goes ok.

**Comment by Idhrendur** [comment]
That was actually fixed in this commit: https://github.com/Idhrendur/paradoxGameConverters/commit/7c47dc4604ac3c5514cdf416b32bc636212b56cc

But as pointed out, the idea name shouldn't have changed when the other items did.

**Comment by IohannesIohannium** [comment]
As @johuotar said, you changed also the idea code, which you shouldn't have done.

add_ideas = absolutis**m** should be written instead of absolutis**t**.

**Comment by Idhrendur** [comment]
Right, that's what I'm saying.

**Comment by Idhrendur** [comment]
The pull request somehow didn't merge right, so I just redid this.
