### ISSUE TITLE
AI only takes white peace to end a war

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#368]
Reported here: https://forum.paradoxplaza.com/forum/index.php?threads/vic2-to-hoi4-converter-release-thread.948992/page-27#post-23332922

and here: https://forum.paradoxplaza.com/forum/index.php?threads/vic2-to-hoi4-converter-release-thread.948992/page-27#post-23337821

**Comment by IohannesIohannium** [comment]
You modded the AI to have no wish to annex, liberate, puppet, take states or force governments. I think you should restore the vanilla values (or better ones), so the AI will finally say "hey, I won this war. I now want this, man!"

**Comment by Idhrendur** [comment]
I thought I removed only the country-specific bits from those files. Any particular suggestions for fixes? I'm way too busy to be able to dig through the AI files and understand them, let alone fix them, for the near future.

**Comment by IohannesIohannium** [comment]
We need to mod up a serious AI for all the ideologies, as HoI4 one is
mainly country-specific. It'll take a lot of time to mod things up.

**Comment by Idhrendur** [comment]
Hasn't been reported since the last couple of releases, so I think it's fine now.
