### ISSUE TITLE
Impassable states

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#383]
We should somehow manage to replicate the vanilla impassable states, to avoid AI destroying their troops somewhere in the Sahara.

The line that should be added in the state history is `impassable = yes`, and I think we should add that also in the province mappings so that it'll generate states that are impassable with all the provinces of a state X that are counted so, and another with the provinces of the same state X that are not, calling the first one "Further X".

I'll take care of adding it in the province mappings if the idea gets added in the code.

**Comment by IohannesIohannium** [comment]
Before going any further, I'd like to say what Vic2 provinces I'd deem as impassable with this map. The zones are Deep Amazonia, Sahara, Rub 'al-Khali, Northern Siberia, Arunachal Pradesh and the Australian Desert.

![impassablevic2todo](https://user-images.githubusercontent.com/24550392/31851190-ddcf799c-b660-11e7-8312-979eb184e533.png)

**Comment by Idhrendur** [comment]
Now done. Instead of having it need changes to the mappings, I had the converter read what HoI4 provinces are impassable and set those ones as impassable.
