### ISSUE TITLE
Add warning if relevant .exe is not in the suggested folder.

### ISSUE THREAD

**Issue by kratostatic** [Idhrendur/paradoxGameConverters#384]
To give an obvious warning if people select the wrong folder.  Current warning is kind of generic and inscrutable.

@Idhrendur I don't know if you do this in V2-H4 already but if not it might be worth adding.

**Comment by Idhrendur** [comment]
Thanks! It looks like I'm actually not, though I thought I had put in those kind of checks.

**Comment by kratostatic** [comment]
Fixed in 1.0H.
