### ISSUE TITLE
Megacampaign not converting

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#389]
In particular, the log gives the error

    Could not open output/Wessex1836_01_01/history/countries/V18 - BroA<rec.txt

Uploads can be found on this forum post: https://forum.paradoxplaza.com/forum/index.php?threads/vic2-to-hoi4-converter-release-thread.948992/page-27#post-23413273

**Comment by IohannesIohannium** [comment]
It's a codificafion problem. The country file is named *Broërec* and the converter f**ks up any diacritic.

**Comment by Idhrendur** [comment]
Actually, it looks like it was the less than symbol in the name. Fortunately, commit f5f3151fda94874bb4606dfb8b2b484c234efb3c fixed this for issue #376, and that fix worked here.
