### ISSUE TITLE
Too few armies may be converted

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#398]
Or it might be WAD. Initial report here: https://forum.paradoxplaza.com/forum/index.php?threads/vic2-to-hoi4-converter-release-thread.948992/page-28#post-23423059

Uploaded files here: https://forum.paradoxplaza.com/forum/index.php?threads/vic2-to-hoi4-converter-release-thread.948992/page-29#post-23493526

**Comment by IohannesIohannium** [comment]
Probably a WaD. Tell him to try with an higher manpower ratio in conversion.

**Comment by Idhrendur** [comment]
The primary concern was missing tanks. Turned out they were being incorporated into the main divisions of his converted army.
