### ISSUE TITLE
Problems with modding new Vic2 countries

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#399]
I added Trapalandia and I'm adding Alaska and Macedonia for the next update.
However, since the three don't have a EU4 country to start from in most of the cases, they get a basic "British" culture and a basic "Protestant" religion, as well as London as capital.

I'd be glad if we could make it so the converter can recognize that those lack a Vic2 file and not trying to overlap it with England's file, if they don't start from a EU4 country.
TRL (Trapalandia) should have Horse culture and Shamanist religion, with capital 2131 (Falklands)
LSK (Alaska) should have Yankee culture and Protestant religion, with capital 3 (Kenai/Anchorage)
MKD (Macedonia) should have Macedonian culture* and Orthodox religion, with capital 806 (Skopje)

About Macedonian culture, I'm adding it in the next update, just to avoid Serbia being legitimized to own more than what it should.

EDIT:
I will add also further countries in a future, them being:
-ALI (the Alien Invaders), Alien culture, Noreligion religion, with capital 1077 (Krasnoyarsk)
-MIA (Khawitmau/the Land of the Cats), Cat culture, Kemetic religion, with capital 1767 (Luxor)
-UND (the Undead Horde), Undead culture, Noreligion religion, with capital 744 (Florence) or 917 (Jerusalem), just choose you.

**Comment by IohannesIohannium** [comment]
(To mods who'll see this, the labels to use are "Coding", "enhancement" and "EU4ToVic2", thanks. Feel free to delete this message after labelling)

**Comment by Idhrendur** [comment]
If I'm understanding this, you have neither an EU4 country nor a Vic2 country file? You'll need at least one of those, as the converter has to get the data from somewhere. I can't recall if the converter knows to look in it's own files though. If it doesn't it should.

**Comment by IohannesIohannium** [comment]
You got it completely right. And the converter, it doesn't and it should. I'm asking you to make it so it can be, and instructing me on how to make it happen in data files.

I tried putting it in the blankmod history folder, it only resulted in those three countries being forced to have always the same blank, inexistant history, with no stats at all but those I made for "default".

**Comment by kratostatic** [comment]
This will be sorted.

By the way what are you doing for Macedonian exactly?  If it's in roughly modern Macedonia and Serbian culture in EU4 it becomes Macedonian?

**Comment by IohannesIohannium** [comment]
I'm doing Macedonian because it'd be also helpful in case of a megacampaign (HoI4 might soon benefit of a MKD tag), and also because surely they are not Serbs. Romantic nationalism of Vic2 era also gave the basis for the Macedonian people to get a national identity, altho divided between the Serbs, the Bulgarians and, fore, the Turks.

It works as:
-if Serb AND in core-Bulgaria/North Greece/TFYRofMacedonia, Macedonian
-if Bulgarian AND in core Serbia/North Greece/TFYRofMacedonia, Macedonian

If you find other ethnicities that may have been under same treatment, I may add them as well, if that is your question and you wish that.

**Comment by kratostatic** [comment]
That seems good, maybe do if Bulgarian AND owned by Bulgaria, Bulgarian.  Or maybe I'll just make sure that a Bulgaria owning FYROM territory also accepts Macedonian.  I think no matter what we do here someone will disagree so go with what makes most sense to you.

I don't know about anything else similar other than Slovene which we already do.  If I find any other similar cultures I'll let you know.

**Comment by IohannesIohannium** [comment]
I don't know if I can use tags in culture mappings, but your idea sounds reasonable.

**Comment by kratostatic** [comment]
I'm fairly sure it is, and if it isn't I'll make it possible!

Oh and a warning,  the last CK2 patch just added a Cat culture (and Bears but those are sorted already).  I've no idea what the primary nation for Cats should be called or where the capital should be (Barcelona for Cat-alonia?) but that's probably another one to add!

**Comment by IohannesIohannium** [comment]
I saw, but unfortunately, they didn't update the CK2EU4 culture scheme to convert those, defaulting to a "noculture". If they updated, I'd already be working on adding Cats, probably somewhere in Egypt.

**Comment by IohannesIohannium** [comment]
I found a solution to this thing. I simply added this into the Taiping-n-CSA decision, thus using a decent loophole (fixing also governments).

I'll handle files. The decision will fix primary culture, religion, government, and capital of these nations if they aren't already on-map.
