### ISSUE TITLE
NGF/SGF cores

### ISSUE THREAD

**Issue by TheAtom** [Idhrendur/paradoxGameConverters#406]
Related to #143 
NGF and SGF should not be given cores and removed from unions.txt. They are not cultural unions, but regular countries. In vanilla V2, their creation decisions check for control of the cores of German Empire (with appropriate culture) and the NGF/SGF cores are added only when the decision is taken. If the cores are already present, it is impossible to create NGF/SGF by their decisions, and they are both releasable countres.

**Comment by IohannesIohannium** [comment]
I'll fix it in the next update.

**Comment by kratostatic** [comment]
@TheAtom A note about the unions file at the moment - it isn't just used for cultural unions but also for adding in cores for cultures who don't have them, particularly from CK2 converted saves but also for cultures which exist in Vicky 2 but are not converted from EU4 cultures.  At the moment the main example of the latter I can think of is Slovenian; in the past we have dealt with Slovak in the same way and we're presumably about to do the same kind of thing with Macedonian in the next version.

With regards to 143 - that is more of a general problem to do with how to assign cultural cores and the like, and the Riga problem.  In fact once the Riga problem is solved I reckon that issue can probably be closed.

**Comment by kratostatic** [comment]
Did this get fixed in the end?  If not we can sort it out next time.

**Comment by IohannesIohannium** [comment]
Yes. North- and South Germany have been removed from unions.txt as
requested.


The Riga problem, although, still exists. A workaround would be modding the
decision to form (North) Germany not to require Russian- or PLC-owned cores.

**Comment by kratostatic** [comment]
Great!

I think the Riga problem is mentioned in one of the other culture issues, and I have some thoughts about it anyway of which that is one, so I'll close this one.
