### ISSUE TITLE
Converter screws up EU4 savegames

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#407]
It can't read `map_area_data = { ... }`, which will so not let the converter have province mappings.

The converted save is simply an unedited 1.I.1805 vanilla start.

**Comment by kratostatic** [comment]
A 1.23 save?  If so that's whats broken this time :)

**Comment by TheAtom** [comment]
In a save from the same date, I get
`map_area_data{
}`
in the save file, without `=`. Doesn't look consistent with Paradox files format to date.

**Comment by IohannesIohannium** [comment]
The way to solve it is to make the converter ignore it. I removed this row of code from the save file and the conversion went fine. In my save, it was at row 217~218.
 ```
map_area_data{
}
```

**Comment by TheAtom** [comment]
Thinking further about it, this should be parsable as-is. A whitespace between `map_area_data` and `{` would make it a single key (without value) named `map_area_data`, followed by an unnamed `{}` block (such blocks appear for instance in CK2 saves). Perhaps the whitespace is optional (much like for example between a key name and `=`and then `{`).

**Comment by ElectroEsper** [comment]
Did what Iohanneslohannium said, now I got a "No Government" for every country.

**Comment by Idhrendur** [comment]
As currently formulated, changing the grammar to have it not require the equals would also make it ambiguous. Instead, I automated the trick of deleting the section as a quick fix. I'll be working on a more permanent solution in a separate branch as I have time. In the meanwhile, the quick fix should work but a new release will need to be put together.
