### ISSUE TITLE
EU4Vic2 1.23~1.24 update

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#408]
Really huge, dare I say.
I did my best, but ~~two~~ _one_ things are still to be recontrolled:
-~~province mappings~~
-governments. The converter seems to not find anymore the countries' governments.

**[UPDATE ZIP](https://github.com/Idhrendur/paradoxGameConverters/files/1484583/00_EU4.zip)**

CHANGELOG:

- M&T religious, governmental, cultural, colonial-nation compatibility (most of https://github.com/Idhrendur/paradoxGameConverters/issues/315)
- Better renaming decisions (https://github.com/Idhrendur/paradoxGameConverters/issues/317)
- Added some new religions for M&T conversions
- WTWSMS cultural and religious compatibility
- NNM compatibility for: news, decisions, religions, cultures (most of https://github.com/Idhrendur/paradoxGameConverters/issues/38)
- Improved cultural localisation file (https://github.com/Idhrendur/paradoxGameConverters/issues/338)
- Fixed d_medina flags for 1.23, based on the Muhammad CK2 symbol
- Updated FAQs in case of language change of the mod and the savegame
- Removed ACW bookmark, for no history would exist
- Removed starting Vic2 Vanilla wars, because it'd lead to weird behaviour
- Added decision for Deccan to become Hyderabad if Muslim
- Added decision for Aquileia and Carinthia to become Slovenia if Yugoslavic
- Added decision for Latin Empire to form Rome if no Byzzies around
- Added decisions for Sino-Uighurs to form the cliques if they are not China nor is there Yuan, based on capital
- Added Latin Empire localisation for republic and communism
- Added historical Siculo-Arabic (Maltese<=>South Italian) and Mozarabic<=>Spanish ethnoreligious switchings
- Compatibility with Zombies' mod (a bare noculture, but still)
- Special new colonial dynamic cultures (https://github.com/Idhrendur/paradoxGameConverters/issues/345)
- Added Alaska and possibility for colonies to become it
- Added some missing flags
- Added icons to the new decisions the converter adds
- Added Macedonia and a Macedonian culture, which forms from Bulgarian in Serbian lands et viceversa
- Updated to 1.23 (countries, cultures, governments, provinces) (https://github.com/Idhrendur/paradoxGameConverters/issues/314)
- Updated Duchy of Medina-Hijaz of CK2
- Added Langobardia as a formable nations for Old Lombard nations that survived EU4
- Updated to CK2-2.8 (countries, cultures and religions). Flags have been generated mostly thru batch, so they may be hideous (https://github.com/Idhrendur/paradoxGameConverters/issues/268)

Sidenote, for the following update I plan to recontrol how the culture conversion file is done and also to eventually clean up tags we added to Vic2 that aren't that necessary in any scenario.

**Comment by IohannesIohannium** [comment]
Update for 1.24. As always it is to add on the previous one (here above) and to overwrite files there.

[**Update patch**](https://github.com/Idhrendur/paradoxGameConverters/files/1556769/1.24EU.zip)

Changelog:

- 1.24 tags and provinces updated
 --Flags are based either on existing current or historical flags or on edits of them (Madya-as is simply the name spelt out using the Filipino syllabary)
- Recontrolled province mappings to avoid weird wasteland enclaves
- Recontrolled and fixed Central Africa mappings to avoid a huge Luba blob

Tested on a 1.24 1805 save (edited to avoid https://github.com/Idhrendur/paradoxGameConverters/issues/407 and with colonies portrayed as their future countries)

**Comment by IohannesIohannium** [comment]
(Pinning @kratostatic, feel free to delete this as soon as he notices)

**Comment by IohannesIohannium** [comment]
I'd like to report a bug with my files. Since I created a history/countries folder to add Langobardia, the converter refuses to create country histories for anybody else. This may cause problems.

**Comment by WilhelmStein** [comment]
Tried using the last converter version (1.0Ga) and the conversion failed due to "Old province x does not exist(bad mapping?)" errors. Updated the converter with your patch and I got the same errors. Is that due to the tibetian provninces?

**Comment by IohannesIohannium** [comment]
Control issue https://github.com/Idhrendur/paradoxGameConverters/issues/407,
this may be source of that problem.

2018-01-13 10:20 GMT+01:00 Baron Wilhelm Stein <notifications@github.com>:

**Comment by kratostatic** [comment]
All of this has now been put into 1.0H (well a couple of bits had to be changed about - keeping the wars in history was crashing Vicky 2 for example), which will be released very soon.  Thanks again for all of this @IohannesIohannium and hopefully we won't hit another bug like #407 again!
