### ISSUE TITLE
Communism and fascism disappearing

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#418]
Even when they exist in the game, they are deemed as inexistant by the converter. This may lead to problems.

**Comment by Idhrendur** [comment]
I'm not seeing this happen in my test save. Instead, I see all ideologies as present. Which ideology setting are you using?

**Comment by IohannesIohannium** [comment]
I'm using a 1914 WW1 scenario, with all ideologies enabled, at least by what the save file is telling me. May it be tied with no country being communist- or fascist-ruled?

**Comment by Idhrendur** [comment]
Depending on the settings used in conversion, yes. The default setting ('keep_major') only uses the government forms of GPs, others get dropped. The 'keep all' form will have all of them. The 'keep_default' one will use only the normal HoI4 ideologies (so no absolutist or radical).

**Comment by IohannesIohannium** [comment]
Solved by just re-controlling config file.
