### ISSUE TITLE
Some province localisation problems

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#430]
Looks to be a problem with the text conversion routines.

Ones I noticed:

798 ->11887
775 -> 9611
777 -> 9595
797 -> 3956

**Comment by IohannesIohannium** [comment]
The converter can't handle the hacek (reverse-circumflex of, e.g., š). Unless you find a way for it to bear it, the following substitutions would make fine:
š -> sh
ž -> zh

**Comment by IohannesIohannium** [comment]
Found the problem. The converter changed _š_ into  (a character that is read as [SCI]), and _ž_ into  (a character that is read as [PM]). The converter should, instead, correct them into the original _š_ and _ž_.

**Comment by IohannesIohannium** [comment]
Other problem: ' (apostrophe) changed into  (character shown as [PU2]). Same as above.

**Comment by Idhrendur** [comment]
You've been looking at this more recently than I have. I don't think there's any internal conversion of characters happening. If you check the localization files, are there differences there? What about if you look at the localisation files in a hex editor (other tools might render the same stream of binary in different ways because they expect differences)?

**Comment by IohannesIohannium** [comment]
HoI4 and Notepad++ both agree that there are no š and ž, but weird control
codes. Yet in Vic2 sources sure they are.

**Comment by IohannesIohannium** [comment]
This is now a sub-issue of #563, about the very same problem.

**Comment by Idhrendur** [comment]
I'll close it, then.
