### ISSUE TITLE
Making the converters more dynamic and better at cooperating

### ISSUE THREAD

**Issue by WilhelmStein** [Idhrendur/paradoxGameConverters#431]
Note: When I talk about a megacampaign I am refering to playing through ck2, eu4, vic2 and hoi4.

So, I have noticed that since each game keeps certain kind of data in it's saves, it might be considered impossible to pass some data from one game to another.  For example, as I have already touched upon it here #382 , an eu4 save would be needed in order to get a dynasty's name and put it in HoI4, when dealing with monarchies. Another such example would be if we wanted 2 said dynasties that were really friendly but one of which was overthrown, we would want that info to be displayed somehow, and perhaps even have a relevant National Focus.

I propose the relevant converters be incorporated into one, that essentially keeps for each megacampaign important info from previous games. It would be rather interesting and given that Vic2 is only 100 years, we could essentially limit unwanted behaviour. 

For instance, say that a Vic2 monarchy succumbs to revolution and becomes communist or fashist or anarcho-liberal. Then, if a reactionary party takes back control, the converter would already have done some calculations internally when converting from Vic2 to HoI4 and thus see from the Eu4 files how old the monarch was, if he had any heirs, their stats, when generating the HoI4 ruler. Thus, if at the end of Eu4 a ruler had no heirs and was old, a new dynasty could be generated for HoI4, otherwise, the old one would be essentially be "put back" into the throne.

Said changes would make this awesome converter collection easier to use, more organized and make it less about being real life hsitorical and more megacampaign historical ;)
Thoughts?

**Comment by Idhrendur** [comment]
I've opened issues #432 and #433 as specific implementations of this idea.
