### ISSUE TITLE
Incorporating Attila:TW convesion

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#434]
A project, https://github.com/ijedi1234/Attila2CK2, advocates to export Attila:total War saves into CK2.

Having it reached the way to export to EU4, I think we should possibly have it convert also to Vic2 and HoI4.

I'll take care of the new cultures and religions that are generated.

**Comment by WilhelmStein** [comment]
Instead of having to "take care" of any new religions and cultures that each mod provides, wouldn't it be more prudent to making a template of sorts for religions and cultures, as to be more modder  and user friendly?

**Comment by IohannesIohannium** [comment]
What I meant was, I will edit the data files of the culture and religion mappings to Vic2 to incorporate the new EU4 data created.

**Comment by IohannesIohannium** [comment]
Solved in #461
