### ISSUE TITLE
Make the converters use files that will add flavour for future games

### ISSUE THREAD

**Issue by WilhelmStein** [Idhrendur/paradoxGameConverters#442]
I think the converter should give the option to load a file through each conversion that would add specific national ideas, missions , decisions, religions and more. That way, a modder could support custom nations throughout a megacampaign.

**Comment by Idhrendur** [comment]
Can you break this down into more specific tasks? Maybe talk it through on the development threads a bit, first. I'd prefer to keep issues to be pretty specific to implementable items.
