### ISSUE TITLE
No Government for every countries

### ISSUE THREAD

**Issue by ElectroEsper** [Idhrendur/paradoxGameConverters#446]
Title says it all.
Using a 1.23.1 save, unmodded.
Using the  fix for version 1.0Ga. ( and the "bad mapping" fix by edit on save file)

Part of the log giving out the related error.

> 2018-01-18 18:00:08    [INFO] Converting world
> 2018-01-18 18:00:08    [INFO] Converting countries
> 2018-01-18 18:00:08    [INFO] Parsing governments mappings
> 2018-01-18 18:00:08 [WARNING] No government mapping defined for 
> 2018-01-18 18:00:08    [INFO] Getting idea effects
> 2018-01-18 18:00:08   [DEBUG]     AFG has an Upper House of 15 reactionary, 55 conservative, and 30 liberal
> 2018-01-18 18:00:08   [DEBUG]     AFG ruling party is AFG_liberal_2
> 2018-01-18 18:00:08 [WARNING] Undefined government type '' while setting reforms for AFG
> 2018-01-18 18:00:08 [WARNING] Undefined government type '' while setting reforms for AFG
> 2018-01-18 18:00:08   [DEBUG]     Setting literacy for AFG to 0.05
> 2018-01-18 18:00:08   [DEBUG]     AFG has tech school traditional_academic

Does this for every nation as far as I know. 
Load in game menu, then when I select a country and hit play just crash.

Attached my log.txt
[log.txt](https://github.com/Idhrendur/paradoxGameConverters/files/1648352/log.txt)

**Comment by IohannesIohannium** [comment]
Seems I duplicated this issue in https://github.com/Idhrendur/paradoxGameConverters/issues/453

**Comment by kratostatic** [comment]
Fixed in 1.0H.
