### ISSUE TITLE
Set cut-off date for westernization

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#45]
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-183#post-20609398

**Comment by kratostatic** [comment]
This was a solution for the over-westernised world issue.  I believe that this issue is now resolved or at least a lot closer so this should not be necessary.  In addition changes to westernisation mean that this would only effect pre 1.18 saves.
