### ISSUE TITLE
What's going on with all these ProvinceMapper releases?

### ISSUE THREAD

**Issue by Drofseh** [Idhrendur/paradoxGameConverters#459]
https://gyazo.com/8cc923e54564bdc8406258bd54aa1c46
There have been 75 versions released in the last 3 hours.
It's taking over my github notifications and driving every non-ProvinceMapper release several pages back in the releases.
@Idhrendur

**Comment by Idhrendur** [comment]
Oh my! Something has gone terribly wrong with the automated deployments. Thank you for pointing it out.

**Comment by Drofseh** [comment]
You're welcome! Hope it's an easy fix.

Let me know if you want this issue closed now or if I should leave it open until the problem is sorted out.

**Comment by Idhrendur** [comment]
It was easy enough to stop the CI system, but I'm not sure why it happened in the first place.

I was going to leave the issue open until I had finished cleaning up the excess releases.
