### ISSUE TITLE
Compressed file format changed

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#460]
It looks like EU4 compressed saves have slightly changed again. The frontend should be updated to handle them automatically. A sample save is attached to this post: https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-60#post-23807398

**Comment by kratostatic** [comment]
I think that post was deleted.

**Comment by Idhrendur** [comment]
So it was. How annoying.

**Comment by Idhrendur** [comment]
It was easy enough to make my own save. It should be good now.
