### ISSUE TITLE
Gringo culture

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#462]
I agree it needs a better name.

However, coding it as `americano` would cause such culture to overlap with the same-coded one that comes from Italians.

**Comment by kratostatic** [comment]
Can't we change the Italian one?  We'll get a lot more Spanish than Italian colonisers,

**Comment by IohannesIohannium** [comment]
Gonna do it in the 1.25 update.

**Comment by IohannesIohannium** [comment]
Solved in #461
