### ISSUE TITLE
Conversion failed afer 00m 16s - EU4ToVic2

### ISSUE THREAD

**Issue by popsicklehammer** [Idhrendur/paradoxGameConverters#463]
# Conversion failed afer 00m 16s - EU4ToVic2
## Log file:
![image](https://user-images.githubusercontent.com/36441114/36145168-cc30f792-10b0-11e8-915b-1b099ae1358a.png)

## Note:
I didn't select anything in "CK2 Export Directory", as i dont know what to select, and it isn't glowing red as the others, when they were empty.

**Comment by IohannesIohannium** [comment]
May we see the save file?

**Comment by popsicklehammer** [comment]
Save:
https://drive.google.com/open?id=1JQ6yihHTJ5Q0e9Pv6wtNZXlrSRbznKsP

**Comment by IohannesIohannium** [comment]
Your file had some problem. I managed to save it through EU4 again and thus getting a conversion mod. I already fixed the flag of your country (Valhalla).

[output.zip](https://github.com/Idhrendur/paradoxGameConverters/files/1719718/output.zip)

**Comment by popsicklehammer** [comment]
Thanks for the fast response :)
