### ISSUE TITLE
'Communists demand referendum' event can fire even when communism isn't converted

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#473]

**Comment by IohannesIohannium** [comment]
Have the converter set a global flag for each could-be-disappeared ideology, e.g., `communist_enabled`, by an event that it generates will fire at gameplay's start.

Then, edit the events referring to such ideologies as to check, is there the global flag or not.

**Comment by Idhrendur** [comment]
I'm pretty sure most of those events are dynamically created, so better to make sure they are just never created if they shouldn't exist.
