### ISSUE TITLE
Forts and AA don't appear on the map when built

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#475]
I have a report that forts and AA don't appear on the map when built. Probably because we don't set their positions.

**Comment by IohannesIohannium** [comment]
Validating them through the nudge would make them appear on map correctly, but we can't do it as the bare converter.

**Comment by Idhrendur** [comment]
The converter now outputs some default locations. They may not be _good_ default locations, but they're there.
