### ISSUE TITLE
Loading problem

### ISSUE THREAD

**Issue by AlipheeseFateburn** [Idhrendur/paradoxGameConverters#477]
Hi. I encountered an issue with my converted saves from Eu4 to Vic2. When I try to load any of the converted saves the game just crashes while on the phase *Loading Database II*. The funny thing is that sometimes this problem disappears and I can actually play the game with my converted saves. Is there any way to solve this problem? I tried reinstalling and installing Vic2 many times. I have the DLCs needed and Vic2 up to date.

**Comment by Idhrendur** [comment]
This is being discussed quite a bit on the release thread: https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026

There's a hotfix that may help. If not, I believe a new release is not too far off that should remedy the problems.

**Comment by AlipheeseFateburn** [comment]
Do I need to have Eu4 on the forum account too to see the thread?

**Comment by Idhrendur** [comment]
You do.

**Comment by kratostatic** [comment]
Should be sorted by the new release.
