### ISSUE TITLE
HoI4 Cornflakes update

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#478]
This is a good start for an update to the converter for the part regarding datafiles.

**The update**: [1.5HOI4.zip](https://github.com/Idhrendur/paradoxGameConverters/files/1794242/00_HOI4.zip)

**The changelog:**

- Some new flags from EU4toVic2
- Some missing Vic2 flags
- Updated for non-humans (Vic2 weird stuff)
- New ideological icons for absolutist monarchies (the army-hand-thing is let for dictatorship)
-- Absolute monarchies get Saint Stephen's crown from a focus tree in the game
-- Prussian Constitutionalism get the Prussian Pickelhaube from a focus tree
-- Theocracies get the Spanish Inquisition icon
- New special political puppets for Absolutists
- Added MKD flags
- Added names for some cultures
- Some better absolutist portraits already in-game
- Added missing default party, base focuses, and idea localisations for non-English
- Added Kaiser Wilhelm II portraits
- Code added decisions to make the Ottomans switch name with Turkey and back
- Added possibility to "export" cultures into HoI4:
-- Created culture country ideas
-- The converter will simply add to each country's history the lines:
```
 	add_ideas = {
 		culture_[CULTURE]
 	}
```
where [CULTURE] is the primary culture's string in the savefile.
- Cleant up Waking the Tiger new additions that would make nosense in althist (decisions, foci, etc)

**Things required by the coding team to work:**
- Set stability and war support, while also not removing national unity in case people liked to play with older versions
- Set cultural conversion (if they want)

**Things I'll outline in a future update:**
- Actually giving better icons to the cultural ideas (if they are kept)
- Porting over the cultural union decisions from Vic2
- Fixing the Ottomans/Turkey name decision

**Comment by Idhrendur** [comment]
I've either incorporated everything, or put it into a new, smaller, more distinct issue.
