### ISSUE TITLE
Update common/autonomous_states

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#483]
The folder has been updated and more files have specific tags. We need clean version without the tags.

**Comment by IohannesIohannium** [comment]
Blanking them out (wtt_imperial_associate.txt, wtt_imperial_protectorate.txt, wtt_imperial_subject.txt) would be the best, as they only exist to show the Manchurian-Japanese relation in OTL WW2.

**Comment by Idhrendur** [comment]
Agreed.
