### ISSUE TITLE
Update common/on_actions

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#489]

**Comment by IohannesIohannium** [comment]
The new file 03_wtt_on_actions.txt references Sino-Japanese ties and also some German events, none of which would make sense in althist. Blanking out it would be the best solution.

**Comment by Idhrendur** [comment]
Looks like it's just this one

on_coup_succeeded = {
		effect = {
			#Turn elections on for democracies created from coup
			random_other_country = {
				limit = {
					has_government = democratic
					original_tag = ROOT
				}
				set_politics = {
					elections_allowed = yes
				}
			}
		}
	}
