### ISSUE TITLE
Move portrait information

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#490]
It used to be in common/portraits/00_portraits.txt, and now is elsewhere

**Comment by IohannesIohannium** [comment]
They just moved it to `[game folder]/portraits/00_portraits.txt`. Nothing is changed of the file.

**Comment by Idhrendur** [comment]
Good to know. I'm just working down the list in a diff view, so hadn't yet gotten to seeing where they moved them.
