### ISSUE TITLE
Update common/scripted_triggers/elections_scripted_triggers.txt

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#491]

**Comment by IohannesIohannium** [comment]
Files that would need full blanking out are PRC_scripted_triggers.txt, WTT_china_political_struggle_triggers.txt, WTT_scripted_triggers.txt, and WTT_warlord_scripted_triggers.txt. Other files that, instead, just reference tags (such references could be hash'ed out) are 00_scripted_triggers.txt and laws_war_support.txt.
About 00_scripted_triggers_FR_loc.txt, it is a mere file to fix gendering and prepositions of country names in French, thus giving no problem even if it references tags.

**Comment by Idhrendur** [comment]
laws_war_support.txt references ideologies, so needs to be dynamically adjusted appropriately.
