### ISSUE TITLE
Update events

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#495]
We have a lot of them changed, and 1.5 changed them.

**Comment by IohannesIohannium** [comment]
All the ones with prefix WTT_ have been already fixed in #478 , along with ss_recruitment_event.txt

stability_events.txt and Decision_events.txt give no problem, the latter one referencing tags but being "triggered_only" by decisions that are deleted.

**Comment by Idhrendur** [comment]
Looking at it, stability_events.txt has at least one event that has ideology-dependent bits with democracy. Those either need to be removed, or the event being included needs to depend on the ideology existing.

**Comment by Idhrendur** [comment]
Many of the political decisions have been removed, replaced by political decisions.
