### ISSUE TITLE
Update interface/countrypoliticsview.gfx

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#497]

**Comment by IohannesIohannium** [comment]
The parts added in Vanilla are Sino-Japanese subjects (no need for them in althist, as said in #483 ), and lines that can be easily added at the end of the file giving no problem:
				
```
	spriteType = {		
		name = "GFX_event_leader_frame"		
		textureFile = "gfx//interface//event_leader_frame.dds"		
	}
	spriteType = {		
		name = "GFX_leader_marshal_unknown"		
		textureFile = "gfx/leaders/leader_marshal_unknown.dds"		
		legacy_lazy_load = no
	}
```

Yet, I'd like to add, I did some edits myself on the file that is in #478 (adding absolutist special icons and puppets), thus needing to edit the file from there.
