### ISSUE TITLE
Conversion issues

### ISSUE THREAD

**Issue by AlipheeseFateburn** [Idhrendur/paradoxGameConverters#508]
Hi, it's me again. I finished my Megacampaign in Vic2 and wanted to convert it to HoI4. Unfortunately. I met an issue while trying to convert the file. The converter suggest that it's a complication created by mods but the truth is I didn't use any mods, neither in Eu4 nor Vic2.
I'll attach the log file below.
Thank you for your time.
[log.txt](https://github.com/Idhrendur/paradoxGameConverters/files/1823301/log.txt)

P.S I added some countries during the Eu4 gameplay using the custom nation feature.

**Comment by IohannesIohannium** [comment]
Have you stated using the conversion mod in the configuration/using the frontend? If not, here the problem.

**Comment by Idhrendur** [comment]
You weren't using Poland1836_01_01 for your game? If so, you need to include it, too.

**Comment by AlipheeseFateburn** [comment]
Ah, so that was the problem. I forgot to add the Polandd1836_01_01 in the Vic2 Mods configuration. I manage to convert the file. Thanks for your assistance and I would suggest making it a little more clear in the converter {maybe it's my perception so bad that I didn't realise what to do}.

Now I got a problem with the "access denied" while copying but I'll figure it out myself.
Again, thanks for your time and help.
