### ISSUE TITLE
HoI4 bookmark

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#515]
It would be a fine addition to the converter if the "Interesting countries" got actually filled with such.

The converter could generate the bookmark and giving each country a description based on continent (Vic2 continent of capital province) and ruling party's ideology (localisations I'll create later on).

The syntax goes like this:
```
		"[TAG]"={
			history = "[TAG]_GATHERING_STORM_DESC"
			ideology = [ruling ideology]
			ideas = {
				culture_[primary culture]
			}
		}
```
(Obviously, values in square brackets refer to variables)

The countries generated should be the Great Powers, then the generic "---", then finally the Secondary Powers. A `minor = yes` line needs to be added to these latters (just before the `history = ...`).

Secondary Powers, although, won't appear in the bookmark unless they have a focus tree. Thus, there is the need to create a "Secondary Powers" generic tree.

Here an example of a modded WWI start conversion:
![image](https://user-images.githubusercontent.com/24550392/37874642-0c28e570-3033-11e8-98cf-0e96d357fc0c.png)

**Comment by Idhrendur** [comment]
@Johuotar actually implemented this feature back in b89de26. Unless you mean something in addition to it?

**Comment by Idhrendur** [comment]
Sorry, wrong link. It's doing the generation, but it's not into a release yet, is all. This should be the proper link: 124ef49

**Comment by IohannesIohannium** [comment]
Oh, good. Well, integrate anything I said earlier that is not in already, and it's fine.
