### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#526]
I've been trying to clean up the errors HoI4 throws. Early on, we had almost 9000 errors, but HoI4 loaded. Somewhere along the line of fixing errors, HoI4 stopped loading.

**Comment by Idhrendur** [comment]
Fixes to decisions (b278e7697b984ad68078d5feaf69477c66716dbc) is good

**Comment by Idhrendur** [comment]
Blank some division names (871924b6e85022e246f2b0d7e4ffe2e59e3c1fbc) is not good, therefore caused the crash.

**Comment by Idhrendur** [comment]
Confirmed, removing the blanked files fixes the crash. But I don't know why this should be.

**Comment by IohannesIohannium** [comment]
I suggest generating the files for the countries in the mod, by basing it on the primary culture. The file is supposed to use historical names for divisions, although in an althist they'd be mostly senseless.

The coding is:
```
[TAG]_INF_01 =
{
	name = "[Infantry Division]"
	for_countries = { [TAG] }
	can_use = { always = yes }
	division_types = { "infantry" }
	fallback_name = "%d [Infantry Division]"
	ordered = { } #Can be left blank
}
```

This is repeated in [TAG]_CAV_01 (Cavalry Division/"cavalry"), [TAG]_MOT_01 (Motor Division/"motorized"), [TAG]_MEC_01 (Mechanized Division/"mechanized"), [TAG]_ARM_01 (Armoured Division/"light_amor" "medium_armor" "heavy_armor" "modern_armor"), [TAG]_PAR_01 (Airborne Division/"paratrooper"), [TAG]_MAR_01 (Marine Division/"marine"), and [TAG]_MNT_01 (Mountain Division/"mountaineers").

The culturetoGraphics file could be updated with the entry-name for the equivalent of "Infantry Division" and so forth.

**Comment by Idhrendur** [comment]
Right, long-term that's what we want to do. But in the short term, we need to remove the existing ones, and the simple method of just blanking the files causes HoI4 to crash.

**Comment by IohannesIohannium** [comment]
As we did by "Jigme Wanchuck", we could simply generate a copy of the German division file as placeholder for now for the countries (`[TAG]` simply means the tag of the country, with the file itself being named `[TAG]_names_divisions.txt`): https://pastebin.com/iQ0Fc6p8

**Comment by Idhrendur** [comment]
Which, again works for the countries we have in the mod. The immediate problem is the files for the countries that don't exist. They create 1289 lines worth of errors in the log, and we need some way of blanking them. Once that's done, then we can worry about adding new ones.
