### ISSUE TITLE
Can't Select a Nation

### ISSUE THREAD

**Issue by sungross** [Idhrendur/paradoxGameConverters#533]
I just converted my EU4 save to Victoria 2 using 1.0HA. The map loads in fine, however, I cannot seem to be able to select a nation, either by clicking on it on the map or from the list. I'm not sure if this is an old issue or not, but any help would be appreciated!

**Comment by Idhrendur** [comment]
Yep, it's a known issue on the current version of EU4 to Vic2. From the forums, I'm told the solution is to edit bookmarks.txt (or whatever its called) to swap the bookmarks around. Just don't try to use the 1821 one, as it's a theoretical one.
