### ISSUE TITLE
Cleanup errors from loading test saves

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#549]
We're at the final stretch! The obvious errors have been fixed. The test saves convert. They even load, but with errors. These errors should be resolved.

**Comment by IohannesIohannium** [comment]
"Invalid achievement" and "Mod file should be UTF-8 but using anyway" errors should be skipped as they post no threat to gameplay.

**Comment by Idhrendur** [comment]
Agreed. I'm getting more "Wrong ideology: Error in trigger:has_government", which I'm slowly eliminating.

I'm also getting "Invalid focus scripted in trigger. has_completed_focus = SOV_women_pilots (Error in trigger:has_completed_focus)", btu I have no clue where that could be coming from.

**Comment by Idhrendur** [comment]
[JingoisticDiplo.zip](https://github.com/Idhrendur/paradoxGameConverters/files/2058492/JingoisticDiplo.zip)

This conversion is still getting the following errors:
[14:06:57][triggerimplementation.cpp:3799]: Wrong ideology: Error in trigger:has_government
[14:06:57][triggerimplementation.cpp:3799]: Wrong ideology: Error in trigger:has_government
[14:06:57][triggerimplementation.cpp:3799]: Wrong ideology: Error in trigger:has_government
[14:06:57][triggerimplementation.cpp:3799]: Wrong ideology: Error in trigger:has_government
[14:06:57][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = SOV_women_pilots (Error in trigger:has_completed_focus)
[14:06:57][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = SOV_women_pilots (Error in trigger:has_completed_focus)
[14:06:57][triggerimplementation.cpp:3799]: Wrong ideology: Error in trigger:has_government

The last wrong ideology is from the division namelist we can't remove without making HoI4 crash. The invalid focus is in all conversions and seems spurious. But I can't find the source of the first four wrong ideology. This conversion only has democratic and neutrality, but I've cleaned up all extra communism references with another conversion. So it should be just references to fascist we left in the conversion, or references in the HoI4 install we haven't replaced. But from my search, we've replaced everything. Can you find something?

In the meanwhile, I've got a save with no democratic to look at.

**Comment by IohannesIohannium** [comment]
I could find other bugs:

- The generated bookmark is missing the "Other countries" option. It should be put after the great powers with the following coding:

```
		"---"= {
			history = "OTHER_GATHERING_STORM_DESC"
		}
```

- Localisation of Portugese[sic] isn't converted into Braz_por. A little edit (#557) will solve the problem.

- Spanish apostrophe was mistakenly rewritten as "/rquote". Issue should get solved with the pull request above.

- Beside the four default languages, localisation is completely blank from lack of source. I don't know how to solve this without actually involving edit to Vic2 localisations.

- "â" is reduced to a dash. You could find _Bandar-e 'Abb-s_ from original Vic2 _Bandar-e 'Abbâs_ or French _Île de P-ques_ for _Île de Pâques_. "ž" got itself corrupting to _ÅŸ_ and, somehow, "Ö" works perfectly fine and gets converted as such.

- Although originating from Vic2 coding, Adjective State look awful outside English, for order (e.g. French should have, e.g., *Piémont Français*) or missing declension (French *Provence Française*, German *Deutsches Österreich*, Spanish *Indias Occidentales Españolas*).

**Comment by IohannesIohannium** [comment]
Also, I hashed out the referenced ideologies from our modified version of /portraits/00_portraits.txt.

The errors were solved. My log is this: https://pastebin.com/VjTct89s

**Comment by Idhrendur** [comment]
Good catches! I separated the issues you found out as #561, #562, #563, and #564. The bookmark problem I'll get in the next release, the rest I'll work on after.

And really good catch on the portraits! I may have to dynamically generate it, or might decide to postpone it for this release. I'm getting impatient, after all!

**Comment by Idhrendur** [comment]
Modifying 00_portraits.txt didn't seem to help. Try using the test saves (and their associated configuration files), particularly JingoisticDiplo and NoDemocracy1933. I've cleaned up what I can from those ones, but there's still a lot.

**Comment by Idhrendur** [comment]
Well, I've gone through the test saves and cleaned up what errors I could. I'll count this done, but if you end up having any insights into eliminating the rest, I'll happily apply those insights
