### ISSUE TITLE
Converted Save, Vic2 instantly crashes

### ISSUE THREAD

**Issue by Firecage** [Idhrendur/paradoxGameConverters#55]
I converted my Theodoro campaign to Vic2. All went well. Had to delete the map caches though due to the maplogic loading crashes.

So after that it all goes well. I get to the main menu, get to the screen where you choose nations, I choose Theodoro, 1 second after the game starts, it crashes. No warnings, no nothing.

**Comment by Idhrendur** [comment]
Try asking for help on the forum thread. I suspect one of the items in the FAQ is relevant, but we can better look through things there.
