### ISSUE TITLE
"The path to log could not be detected"

### ISSUE THREAD

**Issue by ALEPH001** [Idhrendur/paradoxGameConverters#551]
Hi, community, I have been trying to convert my EU4 savegame to Victoria 2 off youtube, following the procedure to have this be done. However, I have a serious issue that tells me the following "The path to log could not be detected, and need to be set manually here in the frontend. Was expecting to exist at C:Users\Zach\Videos\EU4toVic2converter\EU4ToVic2\log.txt" I know this is pretty specific but I have no idea how to fix this.

**Comment by ALEPH001** [comment]
Note "EU4toVic2converter" is the file I made for this mod.

**Comment by kratostatic** [comment]
What Idhrendur said.  Also, what video is this?  There are instructions linked in the first page of the forum, every forum post with a release, every Reddit post with a release and I believe on Steam, so a video shouldn't be needed (it _shouldn't_ be a very complicated process)

**Comment by ALEPH001** [comment]
![image](https://user-images.githubusercontent.com/39656706/40748015-f94348fa-6413-11e8-9e40-f0712ad0ebab.png)

**Comment by ALEPH001** [comment]
![image](https://user-images.githubusercontent.com/39656706/40748071-1dcf2df6-6414-11e8-8e94-c5f1dfca7a2b.png)

**Comment by ALEPH001** [comment]
I downloaded the newest update "EU4ToV2-1.0Ha.zip," went to winrar and extracted the files into the folder I made in the videos document. If you see something wrong in these files, please do point them out.

**Comment by Idhrendur** [comment]
Thanks for what you've shown us so far. Can you screenshot the rest of the screens from the frontend as it runs, as you keep clicking next?

**Comment by ALEPH001** [comment]
![image](https://user-images.githubusercontent.com/39656706/40749180-fe3fc5d2-6417-11e8-9a52-81181a8ef051.png)

**Comment by ALEPH001** [comment]
![image](https://user-images.githubusercontent.com/39656706/40749251-3d25410a-6418-11e8-9eeb-67d2f4a8e17f.png)

**Comment by ALEPH001** [comment]
![image](https://user-images.githubusercontent.com/39656706/40749293-55ffb8b8-6418-11e8-965f-ccd5670f0658.png)

**Comment by ALEPH001** [comment]
![image](https://user-images.githubusercontent.com/39656706/40749321-68d97956-6418-11e8-87f9-603c884daf7e.png)

**Comment by ALEPH001** [comment]
I reinstalled winrar making sure it is 64 bit, I made sure that I extracted all from the download into the mod file I created, and am still met with these errors and I'm stumped on how to fix this. 
The save I attempted to use was not ironman and had no mods enabled, I also did not rename my saves.

**Comment by Idhrendur** [comment]
I'm not sure about the log file error, but for the actual error causing you problems, just save your game in EU4 as uncompressed.

**Comment by ALEPH001** [comment]
Wow that's all I had to do, thank you.

**Comment by Idhrendur** [comment]
That problem is likely the bookmarks file problem described on the release thread on the paradox forums. I forget the details, but essentially you need to edit the bookmarks file in your mod to swap the order of the 1821 and 1836 bookmarks.
