### ISSUE TITLE
Generated bookmark problem

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#561]
The generated bookmark is missing the "Other countries" option. It should be put after the great powers with the following coding:

```
		"---"= {
			history = "OTHER_GATHERING_STORM_DESC"
		}
```

**Comment by IohannesIohannium** [comment]
Adding to this, secondary powers missing a focus tree different from "generic" would be invisible.

I suggest copying the generic focus tree and, removing the line of "default selection", making it choose only those secondary powers without an own one already. This would result into the game thinking they have a focus tree and making them appear on the bookmark screen.
