### ISSUE TITLE
Text transformation problems

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#563]
"â" is reduced to a dash. You could find _Bandar-e 'Abb-s_ from original Vic2 _Bandar-e 'Abbâs_ or French _Île de P-ques_ for _Île de Pâques_. "ž" got itself corrupting to _ÅŸ_ and, somehow, "Ö" works perfectly fine and gets converted as such. (EDIT) Proof: 
![image](https://user-images.githubusercontent.com/24550392/40853260-bc0d28b4-65cd-11e8-80aa-3b9a6d1a71f7.png)

**Comment by Idhrendur** [comment]
I kind of suspect that Vic2 isn't really using 8859-15 encoding, but perhaps the 1252 coding page. That needs to be further researched, and if true, the code updated appropriately.

**Comment by IohannesIohannium** [comment]
Adding to the madness, here it is how "š" is somehow both supported and unsupported by the latest release.

![image](https://user-images.githubusercontent.com/24550392/40921007-8c120182-680e-11e8-8890-82f1feaedec6.png)

**Comment by Idhrendur** [comment]
Turns out this is two separate problems, so I opened the second as issue #608
