### ISSUE TITLE
Political Events problem

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#589]
"The newest version of the converter creates a "PoliticalEvents" file witch screws over the original game's one and bugs out some stuff in "converterPoliticalEvents" & "political decisions".  (the decision to call a referendum for ideology X uses political.18/19/20 and those don't exist in the converter file). Also, the localization is missing for most decisions."

Save attached in this post: https://forum.paradoxplaza.com/forum/index.php?threads/vic2-to-hoi4-converter-release-thread.948992/page-38#post-24354976

**Comment by IohannesIohannium** [comment]
For missing decisions localisation, were there a list of, I could create them.

**Comment by Idhrendur** [comment]
Yeah, unfortunately I don't know either.

**Comment by Idhrendur** [comment]
I'm looking at this now, but as I do so here's the save:
[Greece.zip](https://github.com/Idhrendur/paradoxGameConverters/files/2164469/Greece.zip)

**Comment by Idhrendur** [comment]
It seems the converter needs to generate the proper events and link them to the equivalent hold_the_<ideology>_national_referendum decisions:

    country_event = {
        id = political.<id>
        title = political.<id>.t
        desc = political.<id>.d
        picture = <appropriate_ideology_picture>

        is_triggered_only = yes

        option = {
            name = political.<id>.c
            set_politics = {
                ruling_party = <ideology>
                elections_allowed = <no, unless democratic and then yes>
            }
            add_stability = -0.05
        }
    }

I'm a little surprised to see we have no mechanism to import events and instead have to do them completely in code. So for now this is completely in code!

**Comment by Idhrendur** [comment]
Turns out the relevant events are the ones I've internally marked as 50% events. I've got code in place to update the relevant decisions, I just need to properly look up the event numbers.
