### ISSUE TITLE
Name errors in EU4 to Vic2 to HoI4 conversions

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#591]
As mentioned in this forum post (https://forum.paradoxplaza.com/forum/index.php?threads/vic2-to-hoi4-converter-release-thread.948992/page-38#post-24393865), games converted from EU4 to Vic2 cause some non-breaking errors in Vic2 to HoI4. Sample log here: https://forumcontent.paradoxplaza.com/public/369231/log.txt

Also, it seems we look at the culture file twice. If possible, that might be worth simplifying.

**Comment by IohannesIohannium** [comment]
It seems just some codification-mojibake problem, again.

About the culture-files from Vic2 going weird, the problem seems not to occur with the file in #517.

I can ensure Vic2 uses Windows-1252 for all its files and suppose that HoI4 uses UTF-8.

**Comment by Idhrendur** [comment]
I've not been able to replicate this with sample saves, and I asked for the save several weeks ago. I'm going to close it for now.
