### ISSUE TITLE
Multiple VPs per state

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#598]
When converting to HoI4, only one VP is generated per state, constrasting with the Vanilla, where more VPs are in the same state.

I suggest, every Vic2 province gets a VP generated with normal calculation and state-capitals (i.e., the ones that get a VP already as per the current converter) would get their value doubled.

Either this to be implemented as default conversion or as an option (along with the "debug" mode making every HoI4 province a VP).

**Comment by Idhrendur** [comment]
I would like to see more VPs, but I'm not sure this would be a good idea. At the very least, it would really throw off the VP calculations (which are all state-based things anyways). And we've already had complaints of too many VPs in some areas.
