### ISSUE TITLE
Democratic war foci

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#601]
They should be bypassed (War Plan X, Embargo X, and Enact War Plan X) if the country is at war with the target. The same foci should be deemed as "impassable" if the target is democratic.

This just to avoid, e.g., a democratic UK waging war against Germany, peacing out turning the latter democratic, and DoW it again a few months after because of the focus.

**Comment by IohannesIohannium** [comment]
Solved by #603

**Comment by Idhrendur** [comment]
Thanks!
