### ISSUE TITLE
No Source for Boma (#1983) in older converted games

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#66]
Older converted games give the warning that there is no source for Boma. This goes away by the 1.6 version save.

**Comment by derHochmeister** [comment]
Solving it in the next update. Boma will be added from the EU4 province of Loango to the missing mappings, like in next versions.

**Comment by derHochmeister** [comment]
Fixed in https://github.com/Idhrendur/paradoxGameConverters/issues/291

**Comment by kratostatic** [comment]
And implemented in cace4b779a5d6dd0f163b16bb4e4bbbbe0fe2625 .
