### ISSUE TITLE
Missing province mappings for 1.12 and 1.13 games

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#67]
No mapping for province 774
No mapping for province 1219
No source for Mongo (province 1823)
No source for Fasher (province 1841)
No source for Junaynah (province 1842)

Also, factories are not accepted by any countries for this version.

**Comment by derHochmeister** [comment]
Fixing it in the next release.

**Comment by derHochmeister** [comment]
Mappings fixed in https://github.com/Idhrendur/paradoxGameConverters/issues/291

**Comment by kratostatic** [comment]
And implemented in cace4b779a5d6dd0f163b16bb4e4bbbbe0fe2625 .
