### ISSUE TITLE
Missing province mappings in 1.14 and 1.15 saves

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#68]
No mapping for province 1305
No source for Dampier (province 2502)

Additionally, no countries can accept factories.

**Comment by derHochmeister** [comment]
Fixing it in the next release.

**Comment by derHochmeister** [comment]
Mappings fixed in https://github.com/Idhrendur/paradoxGameConverters/issues/291

**Comment by kratostatic** [comment]
And implemented in cace4b779a5d6dd0f163b16bb4e4bbbbe0fe2625 .
