### ISSUE TITLE
log.txt is missing

### ISSUE THREAD

**Issue by Hajn04** [Idhrendur/paradoxGameConverters#705]
if i start the eu4 to vic2 converter is says that log.txt is missing if i try to reinstall it it's the same issue

**Comment by IohannesIohannium** [comment]
Of course it's missing, it's a log. Have you tried putting a blank file as
"log.txt" and then converting?

**Comment by Idhrendur** [comment]
There's an item in FAQ about that issue.

**Comment by Hajn04** [comment]
[log.txt](https://github.com/ParadoxGameConverters/paradoxGameConverters/files/3334034/log.txt)
ok, but i have this error

**Comment by Idhrendur** [comment]
Two, that's an old version. Go to eu4tovic2 and grab the latest development build.

**Comment by Hajn04** [comment]
the newest version i could find was for 1.26, is there a newer? and if could you pls send the link because i can't find a newer

**Comment by IohannesIohannium** [comment]
Partly working for the current version of EU4, there's my unofficial patch
to this project:
https://github.com/IohannesIohannium/BalkanizeMod/files/3208270/EU4ToVic2.zip

Before converting hash out Tripura area from EU4/map/area.txt and
/region.txt (unknown reason)

**Comment by Idhrendur** [comment]
Go to the eu4toVic2 project (not this one, this one is the wrong one entirely) and get the windows development build. For various reasons, I'm not allowed to link it directly, but it's really not that hard to find.
