### ISSUE TITLE
Techs should affect tech group

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#8]
If techs are above the average for a tech group, count that country as a member of the tech group.

**Comment by derHochmeister** [comment]
Isn't this already solved?

**Comment by kratostatic** [comment]
So as discussed on the forum thread thread this will become the default method of tech group conversion.

**Comment by kratostatic** [comment]
As of commit 4fb8a7e14d7b4855d709608062ac2041e9a4904e this is fully implemented.
