### ISSUE TITLE
Convert cores

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#82]
Every nation that has a core within a Vic2 state should get a core (and possibly a claim) on the resulting HoI4 state.

**Comment by Idhrendur** [comment]
Cores are created, but several countries that only consist of cores seem to be dropped during conversion. This needs investigation and fixing before this issue is closed.

**Comment by thatsgerman** [comment]
The countries drop due to an old issue that countries without a valid capital cause the game to crash, thus any country without a valid capital was destroyed (so all countries that are core only).

**Comment by Idhrendur** [comment]
The cores show up, but the error log complains that there is no country from the tag in the core.

**Comment by thatsgerman** [comment]
I believe in the output of the hoI4Country.cpp there is a check if the capital == 0 it does not ouptut it. Same for the countries file (the one with "V00 = "countries/Venezuela.txt"")

**Comment by Idhrendur** [comment]
That's what I was figuring as I went to bed last night. The trick will be to assign capitals, not to remove the checks.

**Comment by thatsgerman** [comment]
Hard fix is to give the states map a list of core owners and then for countries with 0 capital, look through states and get a list of all core states they have, putting their capital in the one with the most industry (best way to determine capital?). Easy fix is to set capital state to 1 which is obviously wrong but it does not cause the game to crash and puts them into the game.

**Comment by Idhrendur** [comment]
I didn't realize it would accept obviously bad capitals! I got most of them by giving core-only countries a capital in a state where they have a core. I gave the very few others a capital of 1 and write a warning. We can do something better in the future.

This did make some of the country colors come out different. I'm not sure what's up with that.
