### ISSUE TITLE
Update province mappings

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#94]
There's a lot missing, and some rather weird borders. Lakes need to be converted to. And in general, it should be closely looked over to check for correctness.

**Comment by Idhrendur** [comment]
Mostly done now. Still needs review to check for correctness.

**Comment by derHochmeister** [comment]
I mostly controlled and mapped them correctly, but they were rejected here for being in a different order than your usual.

If you test it up, you'll see borders are correct.

**Comment by Idhrendur** [comment]
I've been working on merging @IohannesIohannium's changes in, so this'll fit under 0.3
